### PR TITLE
Replace hardcoded separator with ·

### PR DESCRIPTION
**Pull request by caglar10ur**
Unicode middle dot is safe to use with guestinfo and solves the
ambiguity between ```1|2|3``` and ```dmesg | grep vmxnet```

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
We might need to change `ui/vic-ui/swf/src/main/flex/com/vmware/vicui/constants/AppConstants.as` too. @jooskim?

**Comment by anchal-agrawal** [comment]
lgtm

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
