### PR TITLE
[ci skip] Updating to latest from oss review

### PR DESCRIPTION
**Pull request by mdubya66**
Latest files received after legal review. Files are delivered "as is".

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM :sheep: :it: 

Also looks like this PR didn't skip CI (https://ci.vmware.run/vmware/vic/1448) :)

**Comment by mdubya66** [comment]
yeah, you need to do it in the commit message i guess.

**Comment by gigawhitlocks** [comment]
LGTM

**Comment by mdubya66** [comment]
lgtm

**Pull request merged**
