### PR TITLE
Support restart of datastore objects

### LINKED ISSUE #2145: Portlayer panics when datastore creation attempted after VCH restart
If the VCH is restarted, the portlayer will panic when the docker persona attempts an idempotent creation of the image store.  Reboot was triggered with a `shutdown -r now` within the VCH.

```

time="2016-05-20T19:41:40Z" level=info msg="Refreshing image cache from datastore."
2016/05/20 19:41:40 http: panic serving 192.168.218.235:40416: runtime error: index out of range
goroutine 256 [running]:
net/http.(*conn).serve.func1(0xc4202da780)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xdf95a0, 0xc42000e090)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/pkg/vsphere/datastore.(*Helper).rootDir(0xc4201624e0, 0xc4203cc4e0, 0x2b)
        /Users/ztucker/go/src/github.com/vmware/vic/pkg/vsphere/datastore/datastore.go:322 +0x87
github.com/vmware/vic/pkg/vsphere/datastore.(*Helper).Stat(0xc4201624e0, 0x7fa15c62a9a8, 0xc42000e490, 0xc4203cc4e0, 0x2b, 0x6, 0xffb156, 0x6, 0xc420308f01)
        /Users/ztucker/go/src/github.com/vmware/vic/pkg/vsphere/datastore/datastore.go:235 +0x40
github.com/vmware/vic/lib/portlayer/storage/vsphere.(*ImageStore).GetImageStore(0xc42063f460, 0x7fa15c62a9a8, 0xc42000e490, 0xc420308f10, 0x24, 0x16, 0x16, 0x0)
        /Users/ztucker/go/src/github.com/vmware/vic/lib/portlayer/storage/vsphere/image.go:149 +0xe2
github.com/vmware/vic/lib/portlayer/storage.(*NameLookupCache).GetImageStore(0xc42063f4a0, 0x7fa15c62a9a8, 0xc42000e490, 0xc4203cc3c0, 0x24, 0x0, 0x0, 0x0)
        /Users/ztucker/go/src/github.com/vmware/vic/lib/portlayer/storage/image_cache.go:81 +0x225
github.com/vmware/vic/lib/portlayer/storage.(*NameLookupCache).CreateImageStore(0xc42063f4a0, 0x7fa15c62a9a8, 0xc42000e490, 0xc4203cc3c0, 0x24, 0x0, 0x0, 0x0)
        /Users/ztucker/go/src/github.com/vmware/vic/lib/portlayer/storage/image_cache.go:110 +0x98
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).CreateImageStore(0x1994348, 0xc42086be00, 0xc4206bdb40, 0xc42086be00, 0xd90820)
        /Users/ztucker/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/storage_handlers.go:128 +0x94
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).CreateImageStore-fm(0xc42086be00, 0xc4206bdb40, 0x30003c420675a01, 0xc4206bdb30)
        /Users/ztucker/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/storage_handlers.go:113 +0x3e
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage.CreateImageStoreHandlerFunc.Handle(0xc42032bc10, 0xc42086be00, 0xc4206bdb40, 0x19446e0, 0xc4206bdb30)
        /Users/ztucker/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage/create_image_store.go:17 +0x3a
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage.(*CreateImageStore).ServeHTTP(0xc4207865e0, 0x1950360, 0xc420301930, 0xc42086be00)
        /Users/ztucker/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage/create_image_store.go:51 +0x18f
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x1950360, 0xc420301930, 0xc42086be00)
        /Users/ztucker/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc4201744e0, 0x1950360, 0xc420301930, 0xc42086be00)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x1950360, 0xc420301930, 0xc42086be00)
        /Users/ztucker/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc42023dec0, 0x1950360, 0xc420301930, 0xc42086be00)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x1950360, 0xc420301930, 0xc42086be00)
        /Users/ztucker/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc420667740, 0x1950360, 0xc420301930, 0xc42086be00)
        /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4207c1c00, 0x1950360, 0xc420301930, 0xc42086be00)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4202da780, 0x1950ee0, 0xc420308bc0)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```

### PR DESCRIPTION
**Pull request by fdawg4l**
Fixes #2145

If the root directory was greater than 1 path element, we'd ignore the
nested directory if it existed. A path existing isn't an error
condition in this case. Set the root to the existing dir and move on.

Added test to exercise this restart condition.

### CODE REVIEW

**Comment by jzt** [comment]
LGTM

**Comment by emlin** [comment]
LGTM

**Comment by fdawg4l** [comment]
.

**Comment by fdawg4l** [comment]
.

**Pull request merged**
