### PR TITLE
Build vic-machine for linux, windows and mac

### LINKED ISSUE #923: vic-machine binary for Windows
We need a binary of vic-machine that runs on Windows since many vSphere users prefer Windows.

### PR DESCRIPTION
**Pull request by emlin**
Fixes #923

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by andrewtchin** [comment]
lgtm

**Comment by emlin** [comment]
rebased the branch

**Comment by emlin** [comment]
rebased the branch

**Pull request merged**
