### PR TITLE
Update vendor/govmomi to release 0.11.2

### LINKED ISSUE #2968: VIC cannot install into a NSX-T system: error not implemented for type mo.OpaqueNetwork
bin/vic-machine-linux create --target 1.2.3.4 --user root --password xxxxx --no-tls --name VCH-1234-4355 --force
WARN[2016-11-01T14:11:28-05:00] Configuring without TLS - all communications will be insecure 
INFO[2016-11-01T14:11:28-05:00] ### Installing VCH ####                      
INFO[2016-11-01T14:11:30-05:00] Validating supplied configuration            
INFO[2016-11-01T14:11:30-05:00] Using default datastore: local-0             
ERROR unknown Action error: not implemented for type mo.OpaqueNetwork. See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

### PR DESCRIPTION
**Pull request by dougm**
Fixes #2968 (NSX-T)

Avoid possible VirtualMachine.Device NPE seen in #2818

Fix for #2878 (docker image update still required)

### CODE REVIEW

**Comment by dougm** [comment]
Seems github suppresses vendor/ changes?  Diff here w/o all the clicking: https://github.com/vmware/govmomi/compare/v0.10.0...v0.11.2

**Comment by emlin** [comment]
please hold on this fix. It will remove the dangling vm from ci, but I'm still using that for some test.

**Comment by emlin** [comment]
I'm fine with it now, thanks.
LGTM 👍

**Comment by hmahmood** [comment]
lgtm

**Comment by vburenin** [comment]
LGTM

**Comment by dougm** [comment]
.

**Comment by dougm** [comment]
.

**Pull request merged**
