### PR TITLE
[skip ci] Gitignore eclipse files

### PR DESCRIPTION
**Pull request by dnance**
Fixes #

### CODE REVIEW

**Comment by mdubya66** [comment]
please add [skip ci] to the merge comment. lgtm.

**Comment by dnance** [comment]
[skip ci]

**Comment by mlh78750** [comment]
@anchal-agrawal, @dnance is in the org and no cla is needed now.

**Comment by travisfinch** [comment]
If @dnance is a VMware employee, there is no need to sign the CLA (although it looks like he signed it). The bot leaves instructions for what VMware employees need to do if they get prompted to sign a CLA for one of our projects: https://cla.vmware.com/employee

**Comment by mdubya66** [comment]
lgtm

**Pull request merged**
