### PR TITLE
WIP Add sleep when opening readers in vicadmin [full ci]

### LINKED ISSUE #2872: Longevity failure: missing output.log in vic-admin bundle
After almost 4 hours of runtime, hit the following issue:

```
    '-rw-r----- 0/0           65542 2016-10-24 05:13 docker/verbose
-rw-r----- 0/0           99683 2016-10-24 05:13 vpxd:vpxd.log
-rw-r----- 0/0         1608331 2016-10-24 05:13 vicadm/heap
-rw-r----- 0/0            1325 2016-10-24 05:13 lsmod
-rw-r----- 0/0          159458 2016-10-24 05:13 hostd/HostSystem:host-10 @ /stress-datacenter/host/cls/homer.eng.vmware.com
-rw-r----- 0/0          194449 2016-10-24 05:13 VCH-0-2745/vmware.log
-rw-r----- 0/0             996 2016-10-24 05:13 ip-addr
-rw-r----- 0/0              41 2016-10-24 05:13 vicadm/block
-rw-r----- 0/0             204 2016-10-24 05:13 free
-rw-r----- 0/0             129 2016-10-24 05:13 sys-block
-rw-r----- 0/0             265 2016-10-24 05:13 proc-self-fd
-rw-r----- 0/0          448810 2016-10-24 05:13 docker/heap
-rw-r----- 0/0              68 2016-10-24 05:13 disk-by-label
-rw-r----- 0/0          179702 2016-10-24 05:13 vic-init/heap
-rw-r----- 0/0         4398735 2016-10-24 05:13 portlayer/heap
-rw-r----- 0/0           77659 2016-10-24 05:13 vicadm/verbose
-rw-r----- 0/0            3624 2016-10-24 05:13 ps
-rw-r----- 0/0           21785 2016-10-24 05:13 mad_yalow-2f6aac4425b2734f7a6f5e520d4ff53e4d6eec2d523163321cdb4ea9835f4d5e/tether.debug
    [ Message content over the limit has been removed. ]
...--- 0/0         2463173 2016-10-24 05:13 var/log/vic/docker-personality.log
-rw-r----- 0/0        13957528 2016-10-24 05:13 var/log/vic/init.log
-rw-r----- 0/0            1537 2016-10-24 05:13 proc-mounts
-rw-r----- 0/0             519 2016-10-24 05:13 ip-link
-rw-r----- 0/0              41 2016-10-24 05:13 portlayer/block
-rw-r----- 0/0         3512627 2016-10-24 05:13 var/log/vic/port-layer.log
-rw-r----- 0/0            7734 2016-10-24 05:13 netstat
-rw-r----- 0/0            8462 2016-10-24 05:13 vicadm/concise
-rw-r----- 0/0          262130 2016-10-24 05:13 hostd/HostSystem:host-17 @ /stress-datacenter/host/cls/nelson.eng.vmware.com
-rw-r----- 0/0           21651 2016-10-24 05:13 portlayer/verbose
-rw-r----- 0/0             381 2016-10-24 05:13 df
-rw-r----- 0/0            5029 2016-10-24 05:13 vic-init/concise
-rw-r----- 0/0           14378 2016-10-24 05:13 portlayer/concise
-rw-r----- 0/0          213235 2016-10-24 05:13 hostd/HostSystem:host-19 @ /stress-datacenter/host/cls/milhouse.eng.vmware.com
-rw-r----- 0/0              41 2016-10-24 05:13 docker/block
-rw-r----- 0/0         3646174 2016-10-24 05:13 var/log/vic/vicadmin.log' does not contain '2f6aac4425b2734f7a6f5e520d4ff53e4d6eec2d523163321cdb4ea9835f4d5e/output.log'
```

The final bundle that was collected actually has the output.log in it, so maybe some sort of delay/race in grabbing the file by vic-admin?

[14-1-Longevity-VCH-0-2745-container-logs.zip](https://github.com/vmware/vic/files/548994/14-1-Longevity-VCH-0-2745-container-logs.zip)

### PR DESCRIPTION
**Pull request by sgairo**
Fixes #2872

### CODE REVIEW

**Comment by caglar10ur** [comment]
Just my 2 cents, sleeping (pick some random value) is not a solution to fix races at all as it depends the environment...

**Comment by sgairo** [comment]
@caglar10ur I agree, if anything this will confirm what I think the problem is and also this is (hopefully) for GA today so its a cheat around until there is more time.

**Comment by hickeng** [comment]
@sgairo do you have a hypthesis for what is occurring? If the 404 is coming from vSphere then I'd be very surprised if a 5ms delay had any effect at all - that's well within the margin of error for connection establishment.

**Comment by sgairo** [comment]
@hickeng We were thinking that maybe the curl command gets an EOF while the tarball is streaming down in the http response before output.log makes it. What would you suggest?

**Comment by jzt** [comment]
@hickeng Do you think it has anything to do with VC not completing some filesystem operations by the time the tarball is created? The container stops and exits (according to the Robot test, who waits) and then the log bundle is grabbed.. is it possible the container's log hasn't flushed to the filesystem or something by the time this happens even though the container has exited?

**Comment by hickeng** [comment]
@jzt output.log is created (empty) as soon as the VM is powered on.

If you had a truncated tarball you should get a warning - however what's showing in the vicadmin logs is a 404 response from the log reader.

If we are seeing this consistently in vsan deployments and not in non-vsan then I suggest it's something related to either our vsan configuration or our usage. Irrespective it's very unlikely that a 5ms timeout will have any impact beyond random.

You could try adding logging for:
* which host you're attempting to download logs from
* which host the VM is assigned to
if those are different this could be related ownership of the vsan object

**Comment by mdubya66** [comment]
This has been pulled from v0.8.

**Pull request closed without merging**
