### PR TITLE
Fix bug #1346 so that extension registration works on Windows VC

### PR DESCRIPTION
**Pull request by gigawhitlocks**
A bug was found ( #1346 ) that seems to stem from an unassigned heartbeat start time -- this change fixes that.
It also removes an extraneous `Infof` call during vic-machine validation (as a second commit for clarity)

Manually tested against `--target=10.153.199.35`

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by caglar10ur** [comment]
https://ci.vmware.run/vmware/vic/2552 suggests that you need to run gofmt

**Comment by gigawhitlocks** [comment]
Yarrrr emacs is supposed to run gofmt when I save...

**Comment by caglar10ur** [comment]
Classic Emacs... :trollface:

**Comment by gigawhitlocks** [comment]
Ah gofmt actually doesn't reorg imports

**Comment by andrewtchin** [comment]
lgtm

**Comment by gigawhitlocks** [comment]
poke

**Comment by stuclem** [comment]
Thanks for fixing my bug @gigawhitlocks!

**Comment by gigawhitlocks** [comment]
poke

**Pull request merged**
