### PR TITLE
Use VM runtime host for datastore HTTP access [full ci]

### LINKED ISSUE #3397: Datastore access to VM logs limited to VM host when using shared storage
VM files open for writing such as vmware.log, output.log and tether.debug can only accessed by the ESX host where the VM is currently running.  In the case of shared storage, there can be multiple hosts with access to the Datastore - we must use a service ticket for the host where the VM is running to download these files.

### PR DESCRIPTION
**Pull request by dougm**
Required when accessing VM files on shared storage as the VM's runtime host owns the file locks.

Fixes #3397

### CODE REVIEW

**Comment by dougm** [comment]
credit to @hickeng for the vicadmin changes.

**Comment by hickeng** [comment]
LGTM - validated on vsphere having vmotioned running container to new host.

**Comment by cgtexmex** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Pull request merged**
