### PR TITLE
Utilize persona image cache for container create

### LINKED ISSUE #411: Unpack image metadata and pass it to create
Depends on #195 

The image metadata is an opaque blob to the port layer - the docker personality need to unpack this data and marshal it correctly for the call to create container.

### PR DESCRIPTION
**Pull request by cgtexmex**
The docker persona image cache will be used for container create.  Previously a call to imagec was required to get the appropriate layer and config data to pass to the portlayer. 

Fixes #411

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by jzt** [comment]
LGTM

**Comment by caglar10ur** [comment]
can you also remove the imagec's resolv parameter and supporting code with this PR?

**Comment by sflxn** [comment]
@caglar10ur I think @cgtexmex was just trying to remove the use of imagec for this PR for create.  @jzt has a PR to convert imagec to a lib so maybe your request is not needed, esp for this PR.

**Comment by jzt** [comment]
@sflxn @caglar10ur Yeah, it would be nice to not have to rebase imagec again :)

**Comment by caglar10ur** [comment]
Sure, in that case here it comes. drum roll..... LGTM

**Comment by cgtexmex** [comment]
@caglar10ur I've created https://github.com/vmware/vic/issues/1250 to address removing resolv...

**Pull request merged**
