### PR TITLE
Re-enable docker kill tests [full ci]

### LINKED ISSUE #1946: Failure in docker kill test: signal container with default signal
Build 3922 failed with the following issue:

```
time="2016-08-12T15:53:27Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerKill] 00df61b827972916bda8adbc9eb698597289a16644bd1c515630994253214113" 
time="2016-08-12T15:53:27Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerKill] [331.580167ms] 00df61b827972916bda8adbc9eb698597289a16644bd1c515630994253214113" 
time="2016-08-12T15:53:27Z" level=error msg="Handler for POST /v1.21/containers/00df61b827972916bda8adbc9eb698597289a16644bd1c515630994253214113/kill returned error: Cannot kill container 00df61b827972916bda8adbc9eb698597289a16644bd1c515630994253214113: [POST /containers/{id}/signal][500] containerSignalInternalServerError  &{Code:<nil> Message:ServerFaultCode: A general system error occurred: vix error codes = (3016, 0).\n}" 
```

[integration_logs_3922_57a4eb202703eeb7bb9e386dc590256b22fa1ee9_1471018933.zip](https://github.com/vmware/vic/files/415749/integration_logs_3922_57a4eb202703eeb7bb9e386dc590256b22fa1ee9_1471018933.zip)

### PR DESCRIPTION
**Pull request by dougm**
Adds an explicit "modprobe vmxnet3" to the tether (see issue #2327)

Fixes #1946

### CODE REVIEW

**Comment by dougm** [comment]
cc @hickeng

**Comment by hickeng** [comment]
@dougm Could you put the change into `isos/bootstrap/bootstrap` instead. We should avoid making any assumptions about binaries existing in the container filesystem after switch_root (i.e. callable from within tether).

**Comment by dougm** [comment]
@hickeng will do

**Comment by hickeng** [comment]
LGTM

**Comment by dougm** [comment]
.

**Comment by dougm** [comment]
.

**Comment by dougm** [comment]
LGTM

**Pull request merged**
