### PR TITLE
Move kvstore to vch folder

### LINKED ISSUE #3003: kvstore susceptible to races when two VCH use same image store directory
See #2995. In the investigation to #2995 @fdawg4l found a race issue for kvstore. See comment https://github.com/vmware/vic/issues/2995#issuecomment-258231620

I'm closing #2995 as won't fix, but the kvstore issue found needs to be fixed and will be tracked in this bug.

### PR DESCRIPTION
**Pull request by fdawg4l**
The key value store was being rooted inside the image store folder, but the storage layer namespaces this folder.  Keep the key value store in the VCH folder to avoid collisions with other VCHs.

Fixes #3003

### CODE REVIEW

**Comment by fdawg4l** [comment]
For post 0.7.0.

**Comment by fdawg4l** [comment]
ping @jzt and @cgtexmex

**Comment by jzt** [comment]
LGTM, thanks for doing this.

**Comment by cgtexmex** [comment]
LGTM

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by fdawg4l** [comment]
.

**Comment by fdawg4l** [comment]
.

**Pull request merged**
