### PR TITLE
Cleanup the ps auxwww test

### PR DESCRIPTION
**Pull request by mhagen-vmware**
As part of: https://github.com/vmware/vic/pull/3245/files

The username checking portion was just taken out, this puts it back in more accurately to test what we wanted.

### CODE REVIEW

**Comment by mdubya66** [comment]
LGTM for merge post GA.

**Comment by sgairo** [comment]
LGTM

**Comment by mdubya66** [comment]
Approved for Merge

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
