### PR TITLE
Use ubuntu ping instead of busybox ping [full ci]

### PR DESCRIPTION
**Pull request by hickeng**
There are issues with busybox ping that result in dropped packets and hung
processes. These appear to be issues with the busybox impl rather than OS
based so switch to different ping impl.

Workaround #2669

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by caglar10ur** [comment]
♻️

**Comment by hickeng** [comment]
sigh - for whatever reason ping doesn't seem to exist in the latest ubuntu.
This will need to move to ubuntu:trusty

**Comment by caglar10ur** [comment]
photon?

**Comment by hickeng** [comment]
@caglar10ur photon doesn't have it by default either

**Comment by mdubya66** [comment]
debian 

```(mwilliamson) dubs:~/Downloads $ docker run -it debian
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
6a5a5368e0c2: Pull complete
Digest: sha256:677f184a5969847c0ad91d30cf1f0b925cd321e6c66e3ed5fbf9858f58425d1a
Status: Downloaded newer image for debian:latest
root@6479d68a9da2:/# ping www.google.com
PING www.google.com (216.58.194.196): 56 data bytes
64 bytes from 216.58.194.196: icmp_seq=0 ttl=37 time=0.397 ms
64 bytes from 216.58.194.196: icmp_seq=1 ttl=37 time=0.464 ms
64 bytes from 216.58.194.196: icmp_seq=2 ttl=37 time=0.476 ms
^C--- www.google.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.397/0.446/0.476/0.035 ms
root@6479d68a9da2:/#```

**Comment by hickeng** [comment]
poke

**Comment by hickeng** [comment]
poke

**Pull request merged**
