### PR TITLE
Restart on unhandled signal

### PR DESCRIPTION
**Pull request by hickeng**
This triggers a component restart on unhandled signals as well as "clean" exits.
SIGTERM and SIGQUIT are both handled by Go so the waitstatus is Exited.

SIGTERM and others are unhandled so require us to check for Signalled as well.

Upping the default debug level as this was a pain to debug with Info and TP3 will have issue to diagnose.

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by hickeng** [comment]
poke

**Comment by hickeng** [comment]
poke

**Pull request merged**
