### PR TITLE
Add pkg/version and use it with some cmd/

### PR DESCRIPTION
**Pull request by caglar10ur**
pkg/version adds -version flag to the caller so that we can get
detailed build info;

$ bin/imagec -version
v0.4.0 git:e422f47-dirty build:2016/07/25@05:13:55 runtime:go1.7rc3

$ bin/vicadmin -version
v0.4.0 git:e422f47-dirty build:2016/07/25@05:18:25 runtime:go1.7rc3

$ rpctool -version
v0.4.0 git:e422f47-dirty build:2016/07/25@05:15:07 runtime:go1.7rc3

### CODE REVIEW

**Comment by dougm** [comment]
Very nice.  Would be good to put the flags in a single place so it'll be easier to update.  Makefile variable or even a scripts/version-linker-flags.sh that outputs the flags?

**Comment by caglar10ur** [comment]
I think reorganized it as you suggested @dougm

**Comment by dougm** [comment]
lgtm

tho maybe 'ldflags' or 'version-ldflags' instead of 'flags'

**Comment by caglar10ur** [comment]
done (flags -> ldflags)

**Comment by dougm** [comment]
:sheep: :it:

**Comment by emlin** [comment]
The change looks good, then if trigger build after version tag, we'll get a new version release in the binary.
Just a few questions.
1. Do we need drone build ID? For example 3308.
2. Do we think about consolidate this module version with vic-machine version? I understand that might have different requirement, but probably will introduce confusion if they are different.

**Comment by caglar10ur** [comment]
@emlin we could add drone id here. We could also consolidate this with vic-machine, I just didn't want to touch it for now but I can take a look at it.

**Comment by emlin** [comment]
@caglar10ur it's fine to leave vic-machine version command there.
Just if you have drone build included, I can make changes in vic-machine to leverage the flags and versions in vic-machine

**Comment by caglar10ur** [comment]
@emlin please see the new revision

**Comment by emlin** [comment]
nice. LGTM 👍

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
