### PR TITLE
[skip ci] document more docker comands

### PR DESCRIPTION
**Pull request by npakrasi**

### CODE REVIEW

**Comment by mdubya66** [comment]
hi, will we be documenting the various options for each command and their support level? similar to what @sflxn did in 

https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/CLI-COMPATIBILITY.md
https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/API-COMPATIBILITY.md
https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/COMPOSE-COMPATIBILITY.md

**Comment by mdubya66** [comment]
lgtm

**Comment by stuclem** [comment]
@mdubya66 yes we should provide that extra granularity. Opened https://github.com/vmware/vic/issues/1355 to track this for onsite beta.

**Comment by andrewtchin** [comment]
lgtm

**Comment by stuclem** [comment]
:recycle:

**Comment by stuclem** [comment]
:recycle:

**Pull request merged**
