### PR TITLE
rename robot tests so they execute in order

### LINKED ISSUE #1413: Tests are running in wrong order
We are running the tests in the lexical order (eg; 1, 10, 11, 12, 2, 20, 21, 23 ...) instead of using their numerical value.

### PR DESCRIPTION
**Pull request by cgtexmex**
Change renames the robot tests so that they are executed in the
named order.  Additionally, fixed a few cut and paste errors.

Fixes #1413

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by gigawhitlocks** [comment]
omg :+1: yes brilliant PR

**Comment by cgtexmex** [comment]
rebase

**Pull request merged**
