### PR TITLE
Remove systemd-networkd from bootstrap

### PR DESCRIPTION
**Pull request by hickeng**
Given we've removed systemd-networkd from the appliance because the tether
is doing link management, there's no need for it in bootstrap either. This
also removes the multi-user target as the login services are entirely
unnecessary for containerVMs.

Towards: #1724

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

One question, we can still start ssh after this change right?

**Comment by hickeng** [comment]
@caglar10ur This is for the containerVM - the change for the appliance has already gone in and actually enables ssh by default again (for now - see my comment on your related PR).

**Comment by hickeng** [comment]
poke

**Pull request merged**
