### PR TITLE
Fix erroneous layout in vicadmin

### LINKED ISSUE #2008: Improper CSS layout on VIC Admin page
vicadmin

### PR DESCRIPTION
**Pull request by kjplatz**
Fixes #2008 

Incorrect dynamically generated HTML would cause errors when displaying the vicadmin page.  This PR addresses that issue.

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by sgairo** [comment]
LGTM

**Comment by kjplatz** [comment]
bing

**Comment by kjplatz** [comment]
.

**Comment by kjplatz** [comment]
.

**Pull request merged**
