### PR TITLE
Revert: symlink /proc/mounts to /etc/mtab

### PR DESCRIPTION
**Pull request by hmahmood**
I left this out in my previous commit for the tether unit test fixes. The `df` seems to work without the symlink though -- something that this was supposed to fix. See #1642 . This only needs to happen in the container VM. Same goes for unmounting `/run`.

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by hmahmood** [comment]
@caglar10ur @hickeng could you please review?

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by hmahmood** [comment]
♻️

**Pull request merged**
