### PR TITLE
[specific ci=1-44-Docker-CP-Online]return error if nfs volume mount failed

### LINKED ISSUE #5942: Nightly 5-22: NFS simultaneous write to file failed
8/6, build 12979, vSphere 6.5
[5-22-NFS-Volume.zip](https://github.com/vmware/vic/files/1206539/5-22-NFS-Volume.zip)

NFS simultaneous write failed somewhere.  No indication of failures in the logs.  Test 'Simultaneous Container Write to File' during check

### PR DESCRIPTION
**Pull request by emlin**
fixes #5942 

Based on discussion this afternoon with @matthewavery @anchal-agrawal @mhagen-vmware @mdubya66 , we don't want to have nfs volume mount failed silently as described in issue #4850, cause in the case, if user didn't realize the volume is not mounted, and continue to write to the volume store, the data will eventually go to container r/w layer, and after container is gone, the data is lost permanently.

So the decision for 1.2 is that we fail the container if nfs volume mount failed. With this fix, if volume store mount failed in tether, container will quit immediately, and vm is powered off with following error:

```
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch s
Aug 21 2017 22:20:20.581Z INFO  Environment saved in testnfs2/testnfs2.env                           │tatus: container VM has unexpectedly powered off.
```
Do not get back the real error message is because we lack of channel to get tether error from PL, that should be addressed in #4850 in future release.

### CODE REVIEW

**Comment by matthewavery** [comment]
lgtm - glad this ended up being a simple change :) This is a good fix for us right now. Hopefully we can revisit #4850 and #3636 in the future so that we will be able to propagate an error all the way back to the user.

**Comment by caglar10ur** [comment]
Should we also check the err for the case above?

**Comment by emlin** [comment]
> Should we also check the err for the case above?

I ever checked with @matthewavery for that line, and he said that even if this mount error is not checked, the udev will fail eventually. But I think fail here should be better.

**Comment by emlin** [comment]
no any other change except rebase with master, and remove caglar's code, cause that's already merged to master

**Comment by caglar10ur** [comment]
👍

**Pull request merged**
