### PR TITLE
Initial DRS test plan[skip ci]

### LINKED ISSUE #859: DRS: placement and vMotion of containerVMs
This is primarily a testing exercise to ensure that:
* we do not inhibit correctly placement of VMs during power on.
* fully auto DRS can still vMotion VMs as expected - this should be assessed against similarly loaded clusters with non containerVMs.

This has a performance facet - does the power on placement decision materially impact container start time?

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Fixes #859

### CODE REVIEW

**Comment by matthewavery** [comment]
LGTM

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by rajanashok** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
