### PR TITLE
Don't try to autocomplete the password field

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Got a request from Pietro for a small change to the password field in vicadmin. This is a mostly-cosmetic change that shouldn't affect functionality at all, but will make for happier "scanners and customers" I am told. :)

Not attached to an issue -- this is super minor.

### CODE REVIEW

**Comment by gigawhitlocks** [comment]
yeah @anchal-agrawal I can do that when I merge

**Comment by zjs** [comment]
> that shouldn't affect functionality at all

Doesn't this have the functional change of preventing (many) password managers and browsers from auto-filling passwords?

**Comment by hickeng** [comment]
Interestingly, vIDM allows for autocomplete (frustratingly when asking for an RSA token).

**Comment by gigawhitlocks** [comment]
@zjs theoretically yes, but notably Chrome ignores this attribute!

**Pull request merged**
