### PR TITLE
[skip ci] More updates for vic-machine ls, delete, inspect

### PR DESCRIPTION
**Pull request by stuclem**
[skip ci] 

Fixes https://github.com/vmware/vic/issues/842 and a bit of other tidying up. https://github.com/vmware/vic/issues/842 has been reviewed and approved already by @emlin.

### CODE REVIEW

**Comment by stuclem** [comment]
Purely doc-related, so I think that I can LGTM myself.

**Comment by emlin** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @emlin

**Comment by stuclem** [comment]
:recycle:

**Pull request merged**
