### PR TITLE
Delete vmdk on vsphere datastore before deleting directory [full ci]

### LINKED ISSUE #2974: remove image (rmi) is throwing Error response from daemon: [DELETE /storage/{store_name}/info/{id}][500] DeleteImage default  &{Code:0xc4207cb4d0 Message:Cannot delete file [sharedVmfs-0]
This might be similar issue to #2384, which happens on VSAN datastore. But this issue occurs in iscsi

VIC build: vic_6402
Harbor build: harbor_0.4.5_beta
vSphere build: ob-4584207 

Steps:
1. ./vic-machine-darwin create --name VCH1 --target <vc-ip> --user administrator@vsphere.local --password '<pwd>' --compute-resource cls --no-tls --thumbprint D9:3F:BF:6B:DC:81:69:D5:D4:25:58:8C:F4:1A:23:04:66:16:67:B3 --image-store sharedVmfs-0 --bridge-network VICDVPG --insecure-registry 10.xx.xx.xx:80
2. Pull an image to local registry (ubuntu)
3. Do docker login (admin user in Harbor)
4. Tag and Push that image to Harbor registry (ubuntu)
5. Now, Pull it back from Harbor
6. Do docker images cmd to ensure images are listed in VCH
7. Run the image (ubuntu) - worked as expected
8. Remove the container (docker -H rm <cotainer-id>)
9. Remove the image (docker -H <vch-ip> rmi <image-id>

Expected behavior:
docker -H rmi should remove the image successfully

Actual behavior:
vidyasangkar-m01:/ vlakshmivenkat$ docker -H  <vch-ip>:2375 images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
10.xx.xx.xx:80/project1/ubuntu   14.0                57d6e0738b71        2 weeks ago         127.1 MB

vidyasangkar-m01:/ vlakshmivenkat$ docker -H  <vch-ip>:2375 rmi 576e0738b71

Fails with error "Error response from daemon: [DELETE /storage/{store_name}/info/{id}][500] DeleteImage default  &{Code:0xc4207cb4d0 Message:Cannot delete file [sharedVmfs-0] VCH1/VIC/42312345-4bad-6834-65e0 c86737425257/images/56465e1e45d2c75acefb40a7594bc6af78fb012f8b40c0029cb50f7933486b59}"

[container-logs.zip](https://github.com/vmware/vic/files/565254/container-logs.zip)
[logs.zip](https://github.com/vmware/vic/files/565255/logs.zip)

### PR DESCRIPTION
**Pull request by fdawg4l**
FOR POST 0.7.0!

VC insists the vmdk is removed first before removing the directory if
deletable=False is set in the vmdk file.

Also use Operation logging instead of `log` for easier debugging.

Fixes #2974

### CODE REVIEW

**Comment by mdubya66** [comment]
do you mean post 0.7.0?

**Comment by fdawg4l** [comment]
Yeah, that.  Thanks!  Will fix!

**Comment by matthewavery** [comment]
lgtm - looks great!

**Comment by emlin** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by fdawg4l** [comment]
.

**Pull request merged**
