### PR TITLE
add a convenience target called most

### PR DESCRIPTION
**Pull request by caglar10ur**

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by dougm** [comment]
lgtm

Maybe 'most' (subset of all) vs 'quick', but doesn't matter much of course.

**Comment by caglar10ur** [comment]
quick -> most

**Comment by fdawg4l** [comment]
I love obscure make targets!  LGTM!

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
