### PR TITLE
Attempt to detect EOF from Swagger during docker attach

### PR DESCRIPTION
**Pull request by sflxn**
Swagger is catching EOF but returns an untyped error to us with a
string that contains a string with 'EOF' in it.  We now check for
this substring.

This should help with #1129 a little.  We still need to address
the timeouts and checking if the container's process has stopped.

### CODE REVIEW

**Comment by caglar10ur** [comment]
Uhhhh, that means I can return an error message "This is not EOF" and caused a termination, no? Why we are not adding a new error type (EOF etc.) and returning that? That way we can type assert instead of string matching.

**Comment by sflxn** [comment]
No, you can't send a "This is not EOF" message.  All returnable errors in go-swagger are checked first.  The 'unknown' errors are internal go-swagger client errors that it returns.  There is no way for you to return an unknown error with that message or any message.

**Comment by caglar10ur** [comment]
OK, lgtm then

**Comment by jzt** [comment]
lgtm

**Comment by sflxn** [comment]
lgtm.  no changes since the previous two lgtm other than rebase and wait for a successful CI.

**Pull request merged**
