### PR TITLE
Correct string reference in vicadmin test [full ci]

### LINKED ISSUE #2673: Incorrect string comparison in vicadmin test
From https://ci.vmware.run/vmware/vic/5693
```
------------------------------------------------------------------------------
Get VICAdmin Log                                                      | FAIL |
'time="2016-10-12T04:02:23Z" level=info msg="Launching vicadmin pprof server on 127.0.0.1:6061" 
time="2016-10-12T04:02:23Z" level=info msg="Current UID/GID = 1000/1000" 
time="2016-10-12T04:02:23Z" level=debug msg="[ END ] [main.init.1:99] [185.185404ms] " 
time="2016-10-12T04:02:23Z" level=debug msg="[BEGIN] [main.(*server).listen:50]" 
time="2016-10-12T04:02:23Z" level=debug msg="[ END ] [main.(*server).listen:50] [1.965612ms] " 
time="2016-10-12T04:02:23Z" level=info msg="listening on :2378" 
time="2016-10-12T04:02:23Z" level=debug msg="[BEGIN] [main.(*server).serve:126]" 
time="2016-10-12T04:02:23Z" level=debug msg="[BEGIN] [main.(*server).handleFunc:106]" 
time="2016-10-12T04:02:23Z" level=debug msg="[ END ] [main.(*server).handleFunc:106] [7.654?s] " 
time="2016-10-12T04:02:23Z" level=debug msg="[BEGIN] [main.(*server).handleFunc:106]" 
time="2016-10-12T04:02:23Z" level=debug msg="[ END ] [main.(*server).handleFunc:106] [6.513?s] " 
    [ Message content over the limit has been removed. ]
...49Z" level=debug msg="[BEGIN] [main.datastoreReader.open:372] big_mcnulty-643031e6f8127b020f83525b7bf039116d1ed4388c447212b6659f0a66b1347a/tether.debug" 
time="2016-10-12T04:04:49Z" level=debug msg="[BEGIN] [main.httpEntry:236] big_mcnulty-643031e6f8127b020f83525b7bf039116d1ed4388c447212b6659f0a66b1347a/tether.debug" 
time="2016-10-12T04:04:49Z" level=debug msg="[ END ] [main.httpEntry:236] [316.616?s] big_mcnulty-643031e6f8127b020f83525b7bf039116d1ed4388c447212b6659f0a66b1347a/tether.debug" 
time="2016-10-12T04:04:49Z" level=debug msg="[ END ] [main.datastoreReader.open:372] [67.54985ms] big_mcnulty-643031e6f8127b020f83525b7bf039116d1ed4388c447212b6659f0a66b1347a/tether.debug" 
time="2016-10-12T04:04:49Z" level=info msg="big_mcnulty-643031e6f8127b020f83525b7bf039116d1ed4388c447212b6659f0a66b1347a/tether.debug has size 16467" 
time="2016-10-12T04:04:49Z" level=debug msg="[ END ] [main.tarEntries:201] [2m4.518427331s] " 
time="2016-10-12T04:04:49Z" level=debug msg="[ END ] [main.(*server).bundleLogs:228] [2m4.519354289s] " 
time="2016-10-12T04:04:49Z" level=debug msg="[ END ] [main.(*server).bundleContainerLogs:181] [2m4.656153818s] " ' does not contain 'Launching vicadmin server'
```

The following file is checking for a specific string which was changed in: https://github.com/vmware/vic/commit/99a982aeaf6a72a641dee7639e81aa36214abcbb

https://github.com/vmware/vic/blob/master/tests/test-cases/Group9-VIC-Admin/9-1-VICAdmin-ShowHTML.robot#L44

### PR DESCRIPTION
**Pull request by hickeng**
Broken by #2621 

Fixes #2673

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by hmahmood** [comment]
lgtm

**Comment by hickeng** [comment]
poke

**Comment by hickeng** [comment]
poke

**Pull request merged**
