### PR TITLE
Add Entrypoint check back

### PR DESCRIPTION
**Pull request by caglar10ur**
It was dropped by mistake via
https://github.com/vmware/vic/commit/176dc15c709ea02b4e851236eda69fe57c0a8aac#diff-6e989557b980355774bd4187364245fbR1653

### CODE REVIEW

**Comment by sflxn** [comment]
lgtm

**Comment by mdubya66** [comment]
Either we should include a test for this use case or we should make sure an issue is opened to do that.

**Comment by mdubya66** [comment]
lgtm - @sflxn  please pick up the test defect and get that in ASAP.

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
