### PR TITLE
Finish dogfood test plan and automation[skip ci]

### LINKED ISSUE #1849: Write and execute dogfood test plan
As a developer on VIC before deploying VIC into our development process, I want to be assured that it has been tested to work so that we have a reasonable belief that it won't halt development once deployed.

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Fixes #1849

### CODE REVIEW

**Comment by matthewavery** [comment]
lgtm

**Comment by rajanashok** [comment]
LGTM

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
