### PR TITLE
Initial docker kill functionality

### PR DESCRIPTION
**Pull request by sflxn**
Add docker kill to personality server and added PostContainerSignal
to the portlayer rest server to support it.  Needs portlayer vSphere
support and Docker Wait infrastructure to complete the full functionality.

Part of #378

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by jzt** [comment]
LGTM :shipit:

**Comment by sflxn** [comment]
Poke

**Pull request merged**
