### PR TITLE
Remove githooks from project [skip ci]

### PR DESCRIPTION
**Pull request by cgtexmex**
Local githooks were initially used as part of the project.  Those
are no longer (if they ever were) being used.  This change removes
the githooks folder and the githooks instructions in the readme

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by dougm** [comment]
lgtm - as long as CI still checks both

**Comment by cgtexmex** [comment]
@dougm yes CI checks via a "make all" -- this will call check which will do the whitespace & copyright check

**Comment by cgtexmex** [comment]
rebase

**Pull request merged**
