### PR TITLE
Docker compose and implementation of version and some network commands

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Implement a bunch of tests that were previously written and write a new compose test.

### CODE REVIEW

**Comment by mdubya66** [comment]
is docker compose supported in 1.0? it's not listed in https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md either way.

**Comment by mhagen-vmware** [comment]
Not sure whether we support it in 1.0 or not, just finishing up my spreadsheet requirements.

**Comment by mdubya66** [comment]
lgtm

**Comment by matthewavery** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
