### PR TITLE
[skip ci] bump to 1.7.1 - the rest refers to golang:1.7 so no change is needed

### PR DESCRIPTION
**Pull request by caglar10ur**

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by cgtexmex** [comment]
lgtm

**Comment by mdubya66** [comment]
should we wait to stabilize the CI before merging this? also given we are trying to tag 0.6.0 should we wait until after that happens? @hickeng

**Comment by mdubya66** [comment]
Add [full ci] to this and when it passes it should be fine to merge.

**Comment by dougm** [comment]
This one should have been skip ci, since it only runs in the Vagrant devbox.

**Comment by mdubya66** [comment]
ah.

**Comment by caglar10ur** [comment]
@mdubya66 we already use 1.7.1 since it's released as we use golang:1.7 in our scripts which points to latest 1.7 version

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
