### PR TITLE
Fixing dhcp client problems

### LINKED ISSUE #1397: docker: Failed to ping portlayer
**VIC Version:**

0.1 / master / #2626

**Code**

On trying to test new build #2626, I hit the following problem when running docker cmds:
```
docker -H 10.27.33.118:2376 --tls run -it busybox
Unable to find image 'busybox:latest' locally
docker: Failed to ping portlayer: Get http://127.0.0.1:8080/_ping: dial tcp 127.0.0.1:8080: getsockopt: connection refused.
See 'docker run --help'.
```

I could not connect to the logs via a browser either, but I could SSH.
Some log snippets:

init.log
```
time="2016-07-07T14:33:54Z" level=info msg="Launching command []string{\"/sbin/port-layer-server\", \"--host=localhost\", \"--port=8080\", \"--insecure\", \"--sdk=https://administrator%40vsphere.local@10.27.51.103\", \"--datacenter=CNA-DC\", \"--cluster=/CNA-DC/host/Mgmt\", \"--pool=/CNA-DC/host/Mgmt/Resources/COR_RP\", \"--datastore=isilion-nfs-01\", \"--vch=docker-appliance\"}"
time="2016-07-07T14:33:54Z" level=info msg="port-layer exit code: 1"
time="2016-07-07T14:33:54Z" level=error msg="unable to encode []*metadata.ExitLog (slice) for guestinfo..sessions|port-layer.diagnostics.exitlogs: *metadata.ExitLog is an unhandled type"
time="2016-07-07T14:33:54Z" level=info msg="Reload triggered"
time="2016-07-07T14:33:54Z" level=info msg="Triggered reload"
time="2016-07-07T14:33:54Z" level=info msg="Loading main configuration"
time="2016-07-07T14:33:54Z" level=info msg="Loaded executor config"
time="2016-07-07T14:33:54Z" level=info msg="setting ip address 10.27.33.118/20 for link client"
time="2016-07-07T14:33:54Z" level=warning msg="address 10.27.33.118/20 already set on interface client"
time="2016-07-07T14:33:54Z" level=info msg="setting ip address 10.27.33.118/20 for link client"
time="2016-07-07T14:33:54Z" level=warning msg="address 10.27.33.118/20 already set on interface client"
time="2016-07-07T14:33:54Z" level=info msg="setting ip address 10.27.33.118/20 for link client"
time="2016-07-07T14:33:54Z" level=warning msg="address 10.27.33.118/20 already set on interface client"
root@docker-appliance [ /var/log/vic ]#
```

portlayer.log
```
time="2016-07-07T14:29:12Z" level=info msg="Launching portlayer server server on 127.0.0.1:6063"
time="2016-07-07T14:29:12Z" level=fatal msg="configure_port_layer ERROR: Failed to connect to https://10.27.51.103/sdk: Post http
s://10.27.51.103/sdk: dial tcp 10.27.51.103:443: connect: network is unreachable"
```

I will copy down the full logs and attached them shortly.

**Expected behavior:**

**Actual behavior:**

### PR DESCRIPTION
**Pull request by hmahmood**
Fixes #1397

### CODE REVIEW

**Comment by emlin** [comment]
Would you mind to have a separate PR for vendor changes? That will be easy for @mdubya66 to track.

**Comment by hmahmood** [comment]
I don't know how I can do that without breaking the build.

**Comment by emlin** [comment]
you can check in the vendor code first.

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by hickeng** [comment]
LGTM

**Pull request merged**
