### PR TITLE
Go swagger speedups

### LINKED ISSUE #2653: Backport speed-ups from up-stream for go-swagger.
Backport speed-ups from up-stream for go-swagger.

### PR DESCRIPTION
**Pull request by vburenin**
Fixes #2653

### CODE REVIEW

**Comment by fdawg4l** [comment]
@casualjim , can you take a look at these since you're our expert?

**Comment by vburenin** [comment]
@fdawg4l These changes are mine from upstream. I just back-ported them.

**Comment by vburenin** [comment]
btw, generated code remains the same except some random differences due to inconsistent order of map keys. It is intentional behavior of Go maps.

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by vburenin** [comment]
LGTM

**Comment by jzt** [comment]
LGTM

**Pull request merged**
