### PR TITLE
Fix log persistence on vCenter

### LINKED ISSUE #2079: Persist appliance log bundle on shutdown
Currently when the appliance shuts down, all of the logs are dropped due to stateless filesystem. Generally this isn't an issue as they can be pulled via vicadmin however it leaves a hole between VM poweron and vicadmin initialization during which we're unable to tell what has occurred.

The log bundle is the contents of /var/log/vic/ at a minimum - ideally it would include the rest of the local contents from the full vic-admin log bundle.

The most simplistic approach is exactly the one used for the containers - leverage a file backed serial port and write the log bundle to that. In this scenario we would configure the port with Replace instead of Append.

On completion:
- [ ] appliance log bundle is persisted on shutdown

### PR DESCRIPTION
**Pull request by hickeng**
This fixes the log persistence code in a slightly hacky fashion.
We do not get to collect the datastore version of the log in the log
in some scenarios (type unknown) because the file is locked when the
appliance is powered on. Straight vmfs on local datastore this isn't an
issue but it shows up on fibrechannel shared storage on VC. Don't know for
vSAN. As such removing the check from the CI tests.

Also revising the format of the flag logging per Emma's request and
addressing minor issue in bash-helpers.

Fixes #2079

### CODE REVIEW

**Comment by emlin** [comment]
lgtm

**Comment by caglar10ur** [comment]
Will try vsan in 10 min

**Comment by caglar10ur** [comment]
LGTM (for the https://github.com/vmware/vic/issues/3256 part) having vsan/vcenter issues so still not sure whether we can grab the log

**Comment by caglar10ur** [comment]
Looks like it is the same for vsan too, the bundle cannot grab the datastore version of the file.

**Pull request merged**
