### PR TITLE
[skip ci] Documented vic-machine inspect, delete, version and added latest changes to create

### PR DESCRIPTION
**Pull request by stuclem**
[skip ci] Fixes https://github.com/vmware/vic/issues/1400, https://github.com/vmware/vic/issues/953, https://github.com/vmware/vic/issues/828, https://github.com/vmware/vic/issues/841.

### CODE REVIEW

**Comment by stuclem** [comment]
:recycle:

**Comment by stuclem** [comment]
:recycle:

**Comment by mdubya66** [comment]
lgtm

**Comment by stuclem** [comment]
lgtm

**Comment by stuclem** [comment]
:recycle:

**Pull request merged**
