### PR TITLE
Create docker-compose.yml for LEMP example [skip ci]

### PR DESCRIPTION
**Pull request by chengwang86**
Fixes #

Create a LEMP demo for docker-compose.

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by matthewavery** [comment]
LGTM

**Comment by hickeng** [comment]
@chengwang86 @frapposelli Do you know how we can get images pushed to dockerhub as vmware/vice/xxx or a public facing vmware repo?

**Comment by chengwang86** [comment]
Loc has created a public repo called "victest" on the docker hub for our demos. All the images are tagged as "victest/..." but I can also easily create a new public repo with the name "vmware/vice..." if you do not want to use Loc's docker hub repo.






cheng.wang1986

From: George Hicken
Date: 2016-10-11 20:39
To: vmware/vic
CC: chengwang86; Mention
Subject: Re: [vmware/vic] Create docker-compose.yml for LEMP example [skip ci] (#2635)
@chengwang86 @frapposelli Do you know how we can get images pushed to dockerhub as vmware/vice/xxx or a public facing vmware repo?

**Comment by chengwang86** [comment]
@hickeng @stuclem 
https://github.com/chengwang86/temp/blob/master/webserving.md
Here is an updated version of the LEMP example for docker-compose. I have uploaded pre-built images to Loc's docker hub repo "victest". 

I will create a PR for this updated example after Loc reviews it.

**Comment by mdubya66** [comment]
why are we wanting to manage another repo? please don't make this public until we discuss how best to proceed.

**Pull request merged**
