### PR TITLE
Ensure Entrypoint or Cmd is set

### LINKED ISSUE #1378: crash: personality during pull
Saw the following during a pull of alpine. The VCH had been created and used a little, then left alone for an hour:

client:
```
vagrant@devbox:~/vic$ docker -H 192.168.78.245:2376 --tls create alpine
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
e110a4a17941: Pull complete
Digest: sha256:023c4a98e02ff523c38e830299bbe64f3a0c1cdde7dbd4ecacaf46986e264c94
Status: Downloaded newer image for library/alpine:latest
An error occurred trying to connect: Post https://192.168.78.245:2376/v1.21/containers/create: EOF
```

personality:
```
time="2016-04-17T01:02:21Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] ContainerCreate" 
time="2016-04-17T01:02:21Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] [117.977µs] ContainerCreate" 
time="2016-04-17T01:02:21Z" level=error msg="Handler for POST /v1.21/containers/create returned error: No such image: alpine" 
time="2016-04-17T01:02:21Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Image).PullImage] PullImage" 
time="2016-04-17T01:02:31Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Image).PullImage] [9.590280298s] PullImage" 
time="2016-04-17T01:02:31Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] ContainerCreate" 
time="2016-04-17T01:02:31Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] [145.368µs] ContainerCreate" 
2016/04/17 01:02:31 http: panic serving 192.168.78.202:34667: runtime error: slice bounds out of range
goroutine 196 [running]:
net/http.(*conn).serve.func1(0xc820612000)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1560f80, 0xc82000e040)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).dockerContainerCreateParamsToPortlayer(0x26bac50, 0xc820422130, 0xd, 0xc82060a120, 0xc820343c00, 0x0, 0x0, 0xc82038ee40, 0x40, 0xc8203e0930, ...)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/lib/apiservers/engine/backends/container.go:712 +0xb09
github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate(0x26bac50, 0xc820422130, 0xd, 0xc82060a120, 0xc820343c00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/lib/apiservers/engine/backends/container.go:196 +0xbb6
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersCreate(0xc820074210, 0x7effb789e320, 0xc8203fddd0, 0x7effb789e2a8, 0xc8201b1520, 0xc820307960, 0xc8203fdd10, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container/container_routes.go:366 +0x30f
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.postContainersCreate)-fm(0x7effb789e320, 0xc8203fddd0, 0x7effb789e2a8, 0xc8201b1520, 0xc820307960, 0xc8203fdd10, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container/container.go:42 +0x74
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7effb789e320, 0xc8203fddd0, 0x7effb789e2a8, 0xc8201b1520, 0xc820307960, 0xc8203fdd10, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7effb789e320, 0xc8203fdd70, 0x7effb789e2a8, 0xc8201b1520, 0xc820307960, 0xc8203fdd10, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6a9
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7effb789e2a8, 0xc8201b1520, 0xc820307960)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/server.go:132 +0x138
net/http.HandlerFunc.ServeHTTP(0xc820302320, 0x7effb789e2a8, 0xc8201b1520, 0xc820307960)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8201e7900, 0x7effb789e2a8, 0xc8201b1520, 0xc820307960)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/gorilla/mux/mux.go:103 +0x270
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8204233d0, 0x7effb789e2a8, 0xc8201b1520, 0xc820307960)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8202cdc80, 0x7effb789e2a8, 0xc8201b1520, 0xc820307960)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820612000)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

### PR DESCRIPTION
**Pull request by caglar10ur**
Before creating the container like Docker

https://github.com/docker/docker/blob/master/daemon/create.go#L237

Fixes #1378

### CODE REVIEW

**Comment by caglar10ur** [comment]
We are now getting the correct response

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(1378)] docker run -it alpine
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine

e110a4a17941: Pull complete
Digest: sha256:023c4a98e02ff523c38e830299bbe64f3a0c1cdde7dbd4ecacaf46986e264c94
Status: Downloaded newer image for library/alpine:latest
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

**Comment by dougm** [comment]
lgtm

**Comment by hickeng** [comment]
LGTM

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
