### PR TITLE
Container inspect in the personality server

### LINKED ISSUE #370: Docker API: Docker Inspect Container
Implement the docker inspect operation (docker inspect from CLI) in the engine-api server and integrate with the interaction port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#inspect-a-container
https://docs.docker.com/engine/reference/commandline/inspect/

Please note, the engine-api's rest server already packaging these json struct into golang structs.  The url above is just for reference on what the operation should do.

### PR DESCRIPTION
**Pull request by caglar10ur**
This is simply Loc's original work #1307 + adjustments required for the
ContainerInfo API.

Also removes the containers from the cache after a docker rm

Fixes #370

Requires #1427 and #1428

### CODE REVIEW

**Comment by hickeng** [comment]
@caglar10ur we'd like to get this into TP3 - can you check the failed start and let me know if it's a problem with this or another issue in the CI infra.

**Comment by caglar10ur** [comment]
Checking, will let you know...

**Comment by caglar10ur** [comment]
Start seems to be working fine here, waiting CI to finish

**Comment by sflxn** [comment]
Cool, you patched up the code to reflect Clint's changes to the swagger spec.

**Comment by sflxn** [comment]
lgtm

**Comment by hickeng** [comment]
LGTM

**Comment by jzt** [comment]
👍 lgtm, thanks for doing this.

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
