### PR TITLE
bump attach timeout to 50s

### PR DESCRIPTION
**Pull request by emlin**
So far the attach timeout (30s) is too short for slow environment. But we don't want to increase the timeout to super long time, because before attach connection is established, docker cli hung there without any response to user input, including ctrl+C/D
If docker attach timeout, docker cli will accept ctrl+C to stop the command.

Now to avoid the awkward time period mentioned above, we set a short timeout for docker attach, but this timeout does not match with other timeout in portlayer, e.g. the property collector, which is 3m. So even after docker attach timeout, docker run will not return until 3m later. The only way to stop that is to ctrl+C.

This PR is just one workaround for usually in a slightly slower environment, the attach connection takes 40 seconds. Bump to 50 seconds, could accommodate slow environment a little bit better, and not that long time to wait.

The long term solution for this issue is to remove the attach timeout, and parsing the stdin stream data. If there is ctrl+C/D, stop all the work, and return an error to say that user cancelled the operation. But this is not likely should be done right before release, so filed another issue for this enhancement: #6062

fixes: #5940

### CODE REVIEW

**Comment by emlin** [comment]
> NAK, we need the property collector to make sure the process really starts.
> 
> As a workaround we should either make the timeout more than 3 min or remove them altogether.

@caglar10ur Did I misunderstand anything? I didn't change the property collector timeout. Just I didn't change the attach timeout to 3m as well, for attach will hold the docker cli, without any response.

**Comment by caglar10ur** [comment]
You removed the check from lib/portlayer/exec/base.go https://github.com/vmware/vic/pull/6063/files#diff-67f57bbb6bec9888ba685e947a8a00cfL219

**Comment by emlin** [comment]
> You removed the check from lib/portlayer/exec/base.go https://github.com/vmware/vic/pull/6063/files#diff-67f57bbb6bec9888ba685e947a8a00cfL219

this is the second change, to avoid setting container back to stopped, if only session is not initialized.
the wait for session method is called in https://github.com/emlin/vic/blob/a3420f7c0a10465695ced9cc14308429a297d446/lib/portlayer/exec/container.go#L385.
If I don't remove this line, the container will be set back to stopped, if session hung there to wait for clear to launch channel, because of this line: https://github.com/emlin/vic/blob/a3420f7c0a10465695ced9cc14308429a297d446/lib/portlayer/exec/container.go#L366

**Comment by caglar10ur** [comment]
Sooooo looked at the code a bit more and I think the behavior that you are describing is what we want and correct. When you start a container with -i, we set runblock flag of a session (this is exec session not ssh) to true and won't start the process unless the attach operation succeeds. We do that in order to not lost any output from the command that will run inside the container. 

I understand the timeout in attach path ends up timing out waitForSession. The issue is we can't tell whether it is really an attach timeout due to slowness of the system, a real ssh problem or something happened on the container side (tether crashed, vm got stuck etc.)

Also the same start function is used for detached operations so that -d can wait the process to start and then return to the caller, removing that will cause -d to return immediately without waiting command to start.

I believe - unless we do overall change in design - the only thing we can do here is making both ssh and property collector timeouts the same value and increasing them a bit to accommodate slow systems (2 min or something). This way fast systems will keep running as of today and slow systems will waiting more.

**Comment by caglar10ur** [comment]
@emlin pointed out that we are waiting the session twice in the start path (once in base.Start and then container.Start) so I'm OK for this workaround until we fix it for real :)

**Comment by emlin** [comment]
To fix it for real, issue #6072 is filed

**Pull request merged**
