### PR TITLE
Fix docker daemon volumes unit test and persist docker volumes metadata

### PR DESCRIPTION
**Pull request by fdawg4l**
This test wasn't running because the directory was being skipped due to the Makefile.  Also the unit test itself didn't compile.  Fixed.

We weren't persisting the volumes metadata when creating the volume.  Fixed.

### CODE REVIEW

**Comment by fdawg4l** [comment]
@matthewavery, can you take a look at this change when you get the chance?  Thanks!

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by matthewavery** [comment]
lgtm, thanks for cleaning that up for me. I never liked that function name. Also yeah somehow that test made it into master in a weird state... I am thinking I forgot to push a final commit at some point since I use `go test` to check all my unit tests before a merge.

**Comment by fdawg4l** [comment]
.

**Comment by jzt** [comment]
Hey!  This fixes #1612!

**Pull request merged**
