### PR TITLE
Replace some Info level calls with Debug

### PR DESCRIPTION
**Pull request by caglar10ur**

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

Why the 'Debug' -> 'Debugf' changes though?

**Comment by fdawg4l** [comment]
If only we had component logging.  :-)

LGTM

**Comment by caglar10ur** [comment]
@dougm that could be my search/replace operation, could change them back if you think it matters?

**Comment by dougm** [comment]
@caglar10ur ok doesn't matter much, just avoids scanning for the format.. but likely little difference here

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
Removed the debug -> debugf conversion

**Pull request merged**
