### PR TITLE
Encrypt pivate key for host certificate [full ci]

### LINKED ISSUE #2630: Hide secrets from read-only API
We need to hide appliance secrets from the read-only API, while still having them be persistent through vic-machine reconfigure operations.

The problem here is that if the API cannot see them then it cannot re-hydrate those fields in the config before doing a VM reconfigure operation. We're looking at using guestinfo.ovfEnf for hiding from the API, however we must confirm what happens if you update the Extraconfig of a VM that has a guestinfo.ovfEnv specified via API reconfigure, but without again specifying that data - if it's overwritten hen we need a more involved approach.

The alternative to embedding all secrets in one key is that we use the same model drone does and embed a private key in guestinfo.ovfEnv and use that to encrypt any secrets that are stored in a normal fashion.

### PR DESCRIPTION
**Pull request by hickeng**
This encrypts the private key for the endpoint VM server certificate.
Also corrects missing --tlscacert value when loading certificates in
docker client example output during create.

Fixes #2630

### CODE REVIEW

**Comment by fdawg4l** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by dougm** [comment]
lgtm

**Comment by mdubya66** [comment]
This is approved as it is a security requirement from our review and will be stop ship.

**Comment by hickeng** [comment]
poke

**Comment by hickeng** [comment]
poke

**Pull request merged**
