### PR TITLE
[skip ci] Introduce Gandalf the Bot

### LINKED ISSUE #5545: Create a new status check in github that prevents merges to master when builds are failing
User statement:  As an engineer on VIC, I don't always know when we have a build break and shouldn't be merging to master so it would be nice to have an automated mechanism to prevent merges when in this state

Details:  Need to implement a new github status check and make it mandatory.  Needs to have a mechanism to override in case of emergency/need to merge the actual fix into master.

Acceptance criteria:
1. When a failure occurs, the status check will flag all further PRs as not-mergeable until it is fixed/someone manually overrides.

### PR DESCRIPTION
**Pull request by caglar10ur**
SLACK_TOKEN=< omitted > GITHUB_TOKEN=< omitted > ./gandalf

Fixes #5545

### CODE REVIEW

**Comment by mdubya66** [comment]
Since the CI is a production system should we find a way to have this service running on the OVH infrastructure?

**Comment by mdubya66** [comment]
Also, other folks may want to use gandalf. Any interest in  having it in a separate repo?

**Comment by frapposelli** [comment]
+1 on having a separate repo for the bot

**Comment by caglar10ur** [comment]
To be honest I don't think anyone other than us will use this. IMHO this is no different than other scripts in the infra folder (which I can move gandalf into). I could create a Upstream Contrib request and wait legal to approve this new repo etc. but I don't personally think it will worth the effort. 

Your call, let me know what you want and I'll do it :)

**Comment by caglar10ur** [comment]
@mdubya66 @frapposelli do you feel strongly for a separate repo?

**Comment by frapposelli** [comment]
I don't have a super strong opinion, but if it's a separate repo I could see more people contributing/using the bot, especially within vmware.

**Comment by caglar10ur** [comment]
OK then I'm merging this as it for now. We can split the bot into a new repo if we see an interest.

**Comment by mdubya66** [comment]
approved for merge into vic. we can pull it later if it's desired by other repos.

**Pull request merged**
