### PR TITLE
Add script to automate ci log downloads [full ci]

### PR DESCRIPTION
**Pull request by dougm**
Example, for the build of your current branch, no build number required optionally use `-s` flag to stream the log output:

```
$ ./ci-logs.sh -s
Number: 4870
Status: running
Event: pull_request
Commit: d1e2a9ce27bb1b45510b80d569a5785bbdd2aa9c
Branch: ci
Ref: refs/pull/2348/merge
Message: Add script to automate ci log downloads
Author: dougm
Streaming CI log...
[info] Pulling image plugins/drone-git:latest
Drone Git Plugin built from 43dcd64
...
```

Example, for a specific build:
```
$ ./ci-logs.sh 4829
Number: 4829
Status: failure
Event: push
Commit: 25ae6cbdc4a0e4586af8ace73966be0847482114
Branch: master
Ref: refs/heads/master
Message: Add DeleteImage to storage image cache

Author: fdawg4l
Downloading CI log...
Downloading integration logs (integration_logs_4829_25ae6cbdc4a0e4586af8ace73966be0847482114_1473970920.zip)...
Container logs for failed tests:
/.../4829/Test-Cases.Group1-Docker-Commands.1-24-Docker-Link-VCH-4829-7302-container-logs.zip
/.../4829/Test-Cases.Group1-Docker-Commands.1-6-Docker-Run-VCH-4829-9308-container-logs.zip
/.../4829/Test-Cases.Group6-VIC-Machine.6-4-Create-Basic-VCH-4829-1673-container-logs.zip
```

### CODE REVIEW

**Comment by dougm** [comment]
Example:

```
$ drone build list --format {{.Number}}-{{.Branch}}-{{.Status}} vmware/vic | grep master-failure | cut -d- -f1 | xargs -n1 ./ci-logs.sh
Number: 4845
Status: failure
Event: push
Commit: 68929b28bc77259ee13d5c93b24b47875d24f268
Branch: master
Ref: refs/heads/master
Message: Add docker-compose to integration image (#2345)
Author: mhagen-vmware
Downloading CI log...
Downloading integration logs (integration_logs_4845_68929b28bc77259ee13d5c93b24b47875d24f268_1473983208.zip)...
Container logs for failed tests:
/home/dougm/vmw/vic/src/github.com/vmware/vic/ci-logs/4845/Test-Cases.Group6-VIC-Machine.6-4-Create-Basic-VCH-4845-4188-container-logs.zip
```

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by gigawhitlocks** [comment]
LGTM

**Comment by dougm** [comment]
.

**Comment by dougm** [comment]
.

**Pull request merged**
