### PR TITLE
Stop container stats listener in a separate goroutine

### PR DESCRIPTION
**Pull request by dougm**
Seeing TestContainerStatsListener fail locally and in CI.
The 2 Listen goroutines are blocked:
1: for dec.More()
2: doc.Encode

So neither hit the select case for cs.config.Ctx.Done(), so Stop() is never closed.

### CODE REVIEW

**Comment by dougm** [comment]
Stacktrace for the 2 Listen goroutines that are stuck:
```
goroutine 14 [semacquire]:
sync.runtime_notifyListWait(0xc4200c4400, 0xc400000001)
        /usr/local/golang-go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4200c43f0)
        /usr/local/golang-go/src/sync/cond.go:57 +0x97
io.(*pipe).read(0xc4200c43c0, 0xc4201f2001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
        /usr/local/golang-go/src/io/pipe.go:47 +0x163
io.(*PipeReader).Read(0xc42000e0a0, 0xc4201f2001, 0x5ff, 0x5ff, 0x1, 0x523, 0x1)
        /usr/local/golang-go/src/io/pipe.go:130 +0x6f
encoding/json.(*Decoder).refill(0xc4201008c0, 0xc42007eef8, 0xc4201008e8)
        /usr/local/golang-go/src/encoding/json/stream.go:152 +0x1d3
encoding/json.(*Decoder).peek(0xc4201008c0, 0xc42043ff60, 0xc420100901, 0xccdc69)
        /usr/local/golang-go/src/encoding/json/stream.go:500 +0x18b
encoding/json.(*Decoder).More(0xc4201008c0, 0xc42007eea0)
        /usr/local/golang-go/src/encoding/json/stream.go:481 +0x39
github.com/vmware/vic/lib/apiservers/engine/backends/convert.(*ContainerStats).Listen.func1(0xc42007ee40, 0xc42007eea0, 0xc4201008c0)
        /home/dougm/src/github.com/vmware/vic/lib/apiservers/engine/backends/convert/stats.go:145 +0xc5
created by github.com/vmware/vic/lib/apiservers/engine/backends/convert.(*ContainerStats).Listen
        /home/dougm/src/github.com/vmware/vic/lib/apiservers/engine/backends/convert/stats.go:158 +0x28a

goroutine 15 [semacquire]:
sync.runtime_notifyListWait(0xc4200c4378, 0xc400000002)
        /usr/local/golang-go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4200c4368)
        /usr/local/golang-go/src/sync/cond.go:57 +0x97
io.(*pipe).write(0xc4200c4300, 0xc4201f2600, 0x354, 0x595, 0x0, 0x0, 0x0)
        /usr/local/golang-go/src/io/pipe.go:90 +0x206
io.(*PipeWriter).Write(0xc42000e098, 0xc4201f2600, 0x354, 0x595, 0x0, 0x0, 0x46258a)
        /usr/local/golang-go/src/io/pipe.go:157 +0x6f
encoding/json.(*Encoder).Encode(0xc42021f310, 0xd6c060, 0xc4200e66c0, 0x0, 0x0)
        /usr/local/golang-go/src/encoding/json/stream.go:218 +0x3e2
github.com/vmware/vic/lib/apiservers/engine/backends/convert.(*ContainerStats).Listen.func2(0xc42007ee40, 0xc42007eea0, 0xc42021f310)
        /home/dougm/src/github.com/vmware/vic/lib/apiservers/engine/backends/convert/stats.go:182 +0x5a4
created by github.com/vmware/vic/lib/apiservers/engine/backends/convert.(*ContainerStats).Listen
        /home/dougm/src/github.com/vmware/vic/lib/apiservers/engine/backends/convert/stats.go:194 +0x2c3
```

**Comment by dougm** [comment]
Another fix, that does not require the test to call Stop():
```diff
modified   lib/apiservers/engine/backends/convert/stats.go
@@ -132,14 +132,18 @@ func (cs *ContainerStats) Listen() *io.PipeWriter {
 		cs.preDockerStat = &types.StatsJSON{}
 	}
 
+	go func() {
+		<-cs.config.Ctx.Done()
+		close(metric)
+		cs.Stop()
+	}()
+
 	// go routine will decode metrics received from the portLayer and
 	// send them to the encoding routine
 	go func() {
 		for {
 			select {
 			case <-cs.config.Ctx.Done():
-				close(metric)
-				cs.Stop()
 				return
 			default:
 				for dec.More() {
@@ -164,7 +168,6 @@ func (cs *ContainerStats) Listen() *io.PipeWriter {
 		for range ticker.C {
 			select {
 			case <-cs.config.Ctx.Done():
-				cs.Stop()
 				ticker.Stop()
 				return
 			case nm := <-metric:
```

**Comment by dougm** [comment]
Another option would be to have the caller always call `Stop`, and never call it in `Listen()`.

**Comment by cgtexmex** [comment]
@dougm and I talked about this and there's an issue w/the test, but I think the approach of the additional go routine that is solely used for stopping the listener is the appropriate change.  

Currently the code can depend on the `outstream` used by the encoder to be closed...what we were seeing in some iterations of the test was that not happening and then we'd have a deadlock.  Having the "cleanup" routine should help.

**Pull request merged**
