### PR TITLE
Revert "Revert "Add tests and lostcancel check to go vet""

### PR DESCRIPTION
**Pull request by fdawg4l**
Reverts vmware/vic#2044

### CODE REVIEW

**Comment by mdubya66** [comment]
lgtm -after @caglar10ur and @mhagen-vmware figures out the latest failure

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mdubya66** [comment]
lgtm again

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by fdawg4l** [comment]
.

**Pull request merged**
