### PR TITLE
[full ci] Allow default volstore location w/o specified path

### LINKED ISSUE #2302: Could not create volume store due to error: root directory is empty
creating a VCH 

```
      /opt/go/src/github.com/vmware/vic/bin/vic-machine-linux create \
            -t ${host} \
            -u ${user} \
            -p ${pass} \
            -n ZzZ \
            -r $(govc-linux ls host/* | grep Resources) \
            --image-store datastore1 \
            --volume-store datastore1:default \
            --container-network VM\ Network:external \
            --timeout 10m \
            --no-tls \
            -f
```

ends up with 

```
INFO[2016-09-12T20:06:14Z] Creating Resource Pool "ZzZ"
INFO[2016-09-12T20:06:14Z] Creating VirtualSwitch
INFO[2016-09-12T20:06:14Z] Creating Portgroup
INFO[2016-09-12T20:06:14Z] error creating root directory : root directory is empty
ERRO[2016-09-12T20:06:14Z] --------------------
ERRO[2016-09-12T20:06:14Z] vic-machine-linux failed: Exiting because we could not create volume stores due to error: Could not create volume store due to error: root directory is empty
```

error. git blame points to d9143170619e59951e20b3580463e8d7fb996b98

```
commit d9143170619e59951e20b3580463e8d7fb996b98
Author: Hasan Mahmood <hmahmood@users.noreply.github.com>
Date:   Fri Sep 2 16:59:12 2016 -0500

    Restructure datastore root directory creation code (#2224)
```

changing   --volume-store datastore1:default to   --volume-store datastore1/store:default workarounds the issue.

The error could be little bit clear as well.

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Fixes #2302

### CODE REVIEW

**Comment by gigawhitlocks** [comment]
Opened a new issue regarding when directories are created re: conversion IRL with @hmahmood

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by gigawhitlocks** [comment]
♻️

**Comment by gigawhitlocks** [comment]
LGTM

**Pull request merged**
