### PR TITLE
Bump to golang 1.6.3

### PR DESCRIPTION
**Pull request by caglar10ur**
https://groups.google.com/forum/#!topic/golang-nuts/kfzBGiAcxME

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by mdubya66** [comment]
Needs to be reviewed for our onsite push. @hickeng @corrieb @mhagen-vmware

**Comment by hmahmood** [comment]
LGTM

**Comment by fdawg4l** [comment]
LGTM

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
