### PR TITLE
Start naming VCH appliances after the drone build number

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Going to take this in phases. This one will start naming all builds after the drone build number so that later, when I push the cleanup it will clear out all the previous builds based on the new naming scheme.

### CODE REVIEW

**Comment by matthewavery** [comment]
lgtm

**Comment by mdubya66** [comment]
lgtm

**Comment by andrewtchin** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
