### PR TITLE
Fix vic-machine panic

### LINKED ISSUE #1938: vic-machine panics
```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(1578)] /opt/go/src/github.com/vmware/vic/infra/machines/vcsa/install.sh -a -i
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a3b08]

goroutine 1 [running]:
panic(0xb94260, 0xc4200100d0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/vic/pkg/flags.(*optionalString).String(0xc4200260e0, 0xc21f40, 0xc4200260e0)
        /opt/go/src/github.com/vmware/vic/pkg/flags/optional_string.go:38 +0x8
flag.isZeroValue(0xc420019340, 0xd3fc7b, 0x5, 0xd53045)
        /usr/local/go/src/flag/flag.go:393 +0x12d
flag.(*FlagSet).PrintDefaults.func1(0xc420019340)
        /usr/local/go/src/flag/flag.go:467 +0x1d5
flag.(*FlagSet).VisitAll(0xc420014ae0, 0xc420153160)
        /usr/local/go/src/flag/flag.go:323 +0x67
flag.(*FlagSet).PrintDefaults(0xc420014ae0)
        /usr/local/go/src/flag/flag.go:476 +0x46
flag.defaultUsage(0xc420014ae0)
        /usr/local/go/src/flag/flag.go:509 +0x96
flag.(*FlagSet).usage(0xc420014ae0)
        /usr/local/go/src/flag/flag.go:825 +0x55
flag.(*FlagSet).failf(0xc420014ae0, 0xd69cab, 0x22, 0xc420153368, 0x1, 0x1, 0x18, 0x0)
        /usr/local/go/src/flag/flag.go:814 +0x116
flag.(*FlagSet).parseOne(0xc420014ae0, 0x1, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:873 +0xad8
flag.(*FlagSet).Parse(0xc420014ae0, 0xc4200016e0, 0x18, 0x18, 0x1576d38, 0x0)
        /usr/local/go/src/flag/flag.go:915 +0x60
github.com/vmware/vic/vendor/github.com/urfave/cli.Command.Run(0xd4052a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd42125, 0xa, 0x0, ...)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/command.go:120 +0x69c
github.com/vmware/vic/vendor/github.com/urfave/cli.(*App).Run(0xc420192000, 0xc4200016c0, 0x1a, 0x1a, 0x0, 0x0)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/app.go:236 +0x60c
main.main()
        /opt/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:98 +0x1756
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(1578)]
```

following is how that script uses vic-machine
```
        /opt/go/src/github.com/vmware/vic/bin/vic-machine-linux create \
            -t ${host} \
            -u ${user} \
            -p ${pass} \
            -n ZzZ \
            -r /dc1/host/cluster1/Resources \
            --image-datastore vsanDatastore \
            --volume-store vsanDatastore:default \
            --external-network /dc1/network/ExternalNetwork \
            --bridge-network /dc1/network/InternalNetwork \
            --container-network /dc1/network/ExternalNetwork:external \
            --timeout 10m \
            --no-tls \
            -f
```

### PR DESCRIPTION
**Pull request by emlin**
Fixes #1938 

  somehow these flags will be invoked with nil variables. This just happens recently.

### CODE REVIEW

**Comment by hmahmood** [comment]
lgtm

**Comment by andrewtchin** [comment]
lgtm
@kjplatz was also seeing this and may have opened up a duplicate issue

**Comment by emlin** [comment]
Also fix #2027

**Comment by emlin** [comment]
♻️

**Pull request merged**
