### PR TITLE
Fix PL REST API unit test

### PR DESCRIPTION
**Pull request by fdawg4l**
The test wasn't running and had some compilation issues.  Refactored to
PASS.

Also, pass by ref vs pass by val issues needed some sorting.  This could
probably use a second pass, but it's functional as is.

### CODE REVIEW

**Comment by mdubya66** [comment]
Approved for merge as this is a test

**Comment by hmahmood** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by fdawg4l** [comment]
Im going to hold off on this.  I found an issue which isn't trivial.  WIll push this fix with some more stuff next week (post beta).

**Pull request closed without merging**
