### PR TITLE
Enable robot tests using log based assertions [full ci]

### LINKED ISSUE #366: Docker API: Docker Container Logs
Add docker log operation to our engine-api server and integrate that with the interaction portlayer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#get-container-logs
https://docs.docker.com/engine/reference/commandline/logs/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

### PR DESCRIPTION
**Pull request by dougm**
A few tests were using 'docker logs' to assert container command output
but were disabled.

Note that the tests needed additional changes other just enabling the
use of logs.

Closes #366

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
Looks like the build ran just the regression tests. I've noticed that editing the PR title to include `[full ci]` sometimes doesn't trigger a full build. Restarting the build should resolve this, I think.

**Comment by dougm** [comment]
Yeah, it should run full ci on the next rebase+push.

**Comment by fdawg4l** [comment]
lgtm

**Comment by mdubya66** [comment]
Lgtm

**Comment by dougm** [comment]
rebased

**Pull request merged**
