### PR TITLE
Adding new landing page and HTML/PDF docs for VIC on github.io.

### PR DESCRIPTION
**Pull request by stuclem**
[ci skip] New landing page for vmware.github.io, with VIC icons and PDF and HTML versions of the draft docs.

### CODE REVIEW

**Comment by caglar10ur** [comment]
github can't show the diffs so I'm blindly trusting you @stuclem here and giving LGTM :)

**Comment by stuclem** [comment]
Thanks @caglar10ur - these are mostly generated files for publication on github.io. The sources are in the master branch.

**Comment by dougm** [comment]
You can see it here @caglar10ur : https://stuclem.github.io/vic/

very nice, lgtm

**Comment by stuclem** [comment]
Thanks!

**Comment by caglar10ur** [comment]
hmm we have dead links, http://vmware.github.io/vic/ -> click "See vSphere Integrated Containers Architecture for a high level overview." -> 404

**Comment by mdubya66** [comment]
<https://github.com/vmware/vic/blob/master/doc/design/arch/arch.md><https://github.com/vmware/vic/blob/master/doc/design/arch/arch.md>Should it be this? https://github.com/vmware/vic/blob/master/doc/design/arch/arch.md
--
Matt Williamson
mwilliamson@vmware.com<mailto:mwilliamson@vmware.com>
(W) 512 813 3455
(C) 512 496 1788

From: "S.Çağlar Onur"
Reply-To: vmware/vic
Date: Thursday, June 9, 2016 at 12:56 PM
To: vmware/vic
Subject: Re: [vmware/vic] Adding new landing page and HTML/PDF docs for VIC on github.io. (#1030)


hmm we have dead links, http://vmware.github.io/vic/<https://urldefense.proofpoint.com/v2/url?u=http-3A__vmware.github.io_vic_&d=CwMCaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=_HNG7MsT3qaLn7_f1XRJR0MicqkG6oi-42eFTYWaU4E&m=rSwOD2Mt6ZIlggXJkc18nq_hyMrpqJCZdTgltiVNAPY&s=AtSKsT5t-7iIrErrtpfITORCCe3pgVEZZgJ-aAv1Tuw&e=> -> click "See vSphere Integrated Containers Architecture for a high level overview." -> 404

**Comment by stuclem** [comment]
Updated the link. See https://stuclem.github.io/vic/ to verify.

**Pull request merged**
