### PR TITLE
[specific ci=Group6-VIC-Machine]These two tests were innacurately set to true when they were doing --…

### PR DESCRIPTION
**Pull request by mhagen-vmware**

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by hickeng** [comment]
@mhagen-vmware This PR description is useless to me - I can see what it was meant to say from the code, but that's not really helpful.
There's also a high likelyhood that this PR would be merged with the PR title as the git commit message which is a crime against source control.

**Comment by mhagen-vmware** [comment]
@hickeng this was a temporary branch PR. I kept it so that Loc could use it for the basis of his real PR to fix the actual problem.

**Comment by hickeng** [comment]
@mhagen-vmware Ok - can those be created in the http://github.com/mhagen-vmware/vic repo if needed - in general all PRs should be coming from personal repos, then there's no need for a PR at all.

**Pull request closed without merging**
