### PR TITLE
Remove transitive govmomi inclusion from guest.UUID

### PR DESCRIPTION
**Pull request by hickeng**
DHCP id.go pulled in guest.UUID which inflated the size of the tether to 44MB from 12MB

Towards: #1724

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by hickeng** [comment]
@caglar10ur can I get a review? This one actually managed to pass integration ;)

**Comment by hmahmood** [comment]
If its going to be just one function, maybe we can name it something other than guest?

**Comment by fdawg4l** [comment]
lgtm

**Comment by caglar10ur** [comment]
Lgtm

**Comment by hickeng** [comment]
poke

**Pull request merged**
