### PR TITLE
vic-machine create option enhancement

### LINKED ISSUE #1165: vic-machine options enhancement
- Add single letter option for common arguments
- Add "Optional" explicitly into the flag description if it is optional all the time

### PR DESCRIPTION
**Pull request by emlin**
Fixes #1165 

  Add REQUIRED ahead of flag usage message, to mark mandatory options
  Add acronym as option short name
  Add advanced help option -x to show hidden/advanced options.

### CODE REVIEW

**Comment by emlin** [comment]
Currently, just move few experimental options to hidden. Following is the output of -h
```
./bin/vic-machine-linux create -h
NAME:
   vic-machine-linux create - Deploy VCH

USAGE:
   vic-machine-linux create [command options] [arguments...]

OPTIONS:
   --target value, -t value                         REQUIRED. ESXi or vCenter connection URL, specifying a datacenter if multiple exist e.g. root:password@VC-FQDN/datacenter (default: <nil>)
   --user value, -u value                           ESX or vCenter user
   --password value, -p value                       ESX or vCenter password (default: <nil>)
   --compute-resource value, -r value               Compute resource path, e.g. myCluster/Resources/myRP. Default to <default cluster>/Resources
   --name value, -n value                           The name of the Virtual Container Host (default: "virtual-container-host")
   --image-datastore value, -i value                REQUIRED. Image datastore name
   --container-datastore value, --cs value          Container datastore name - not supported yet, default to image datastore
   --volume-store value, --vs value                 Specify location and label for volume store; path optional: "datastore/path:label" or "datastore:label"
   --bridge-network value, -b value                 The bridge network (private port group for containers)
   --external-network value, --en value             The external network (can see hub.docker.com)
   --management-network value, --mn value           The management network (provides route to target hosting vSphere)
   --client-network value, --cln value              The client network (restricts DOCKER_API access to this network)
   --container-network value, --cn value            Networks that containers can use
   --container-network-gateway value, --cng value   Gateway for the container network's subnet in CONTAINER-NETWORK:SUBNET format, e.g. a_network:172.16.0.0/16
   --container-network-ip-range value, --cnr value  IP range for the container network in CONTAINER-NETWORK:IP-RANGE format, e.g. a_network:172.16.0.0/24, a_network:172.16.0.10-20
   --container-network-dns value, --cnd value       DNS servers for the container network in CONTAINER-NETWORK:DNS format, e.g. a_network:8.8.8.8
   --pool-memory-reservation value, --pmr value     VCH Memory reservation in MB (default: 0)
   --pool-memory-limit value, --pml value           VCH Memory limit in MB (default: 0)
   --pool-memory-shares value, --pms value          VCH Memory shares in level or share number, e.g. high, normal, low, or 163840 (default: <nil>)
   --pool-cpu-reservation value, --pcr value        VCH vCPUs reservation in MHz (default: 0)
   --pool-cpu-limit value, --pcl value              VCH vCPUs limit in MHz (default: 0)
   --pool-cpu-shares value, --pcs value             VCH vCPUs shares, in level or share number, e.g. high, normal, low, or 4000 (default: <nil>)
   --bridge-network-range value, --bnr value        The ip range from which bridge networks are allocated (default: "172.16.0.0/12")
   --appliance-iso value, --ai value                The appliance iso
   --bootstrap-iso value, --bi value                The bootstrap iso
   --key value                                      Virtual Container Host private key file
   --cert value                                     Virtual Container Host x509 certificate file
   --no-tls, -k                                     Disable TLS support
   --force, -f                                      Force the install, removing existing if present
   --timeout value                                  Time to wait for appliance initialization (default: 3m0s)
   --advanced-options, -x                           Show all options
   --debug value, -v value                          [0(default),1...n], 0 is disabled, 1 is enabled, >= 1 may alter behaviour (default: 0)
```

And this is the -x output:
```
./bin/vic-machine-linux create -x
NAME:
   vic-machine-linux create - Deploy VCH

USAGE:
   vic-machine-linux create [command options] [arguments...]

OPTIONS:
   --target value, -t value                         REQUIRED. ESXi or vCenter connection URL, specifying a datacenter if multiple exist e.g. root:password@VC-FQDN/datacenter (default: <nil>)
   --user value, -u value                           ESX or vCenter user
   --password value, -p value                       ESX or vCenter password (default: <nil>)
   --compute-resource value, -r value               Compute resource path, e.g. myCluster/Resources/myRP. Default to <default cluster>/Resources
   --name value, -n value                           The name of the Virtual Container Host (default: "virtual-container-host")
   --image-datastore value, -i value                REQUIRED. Image datastore name
   --container-datastore value, --cs value          Container datastore name - not supported yet, default to image datastore
   --volume-store value, --vs value                 Specify location and label for volume store; path optional: "datastore/path:label" or "datastore:label"
   --bridge-network value, -b value                 The bridge network (private port group for containers)
   --external-network value, --en value             The external network (can see hub.docker.com)
   --management-network value, --mn value           The management network (provides route to target hosting vSphere)
   --client-network value, --cln value              The client network (restricts DOCKER_API access to this network)
   --container-network value, --cn value            Networks that containers can use
   --container-network-gateway value, --cng value   Gateway for the container network's subnet in CONTAINER-NETWORK:SUBNET format, e.g. a_network:172.16.0.0/16
   --container-network-ip-range value, --cnr value  IP range for the container network in CONTAINER-NETWORK:IP-RANGE format, e.g. a_network:172.16.0.0/24, a_network:172.16.0.10-20
   --container-network-dns value, --cnd value       DNS servers for the container network in CONTAINER-NETWORK:DNS format, e.g. a_network:8.8.8.8
   --pool-memory-reservation value, --pmr value     VCH Memory reservation in MB (default: 0)
   --pool-memory-limit value, --pml value           VCH Memory limit in MB (default: 0)
   --pool-memory-shares value, --pms value          VCH Memory shares in level or share number, e.g. high, normal, low, or 163840 (default: <nil>)
   --pool-cpu-reservation value, --pcr value        VCH vCPUs reservation in MHz (default: 0)
   --pool-cpu-limit value, --pcl value              VCH vCPUs limit in MHz (default: 0)
   --pool-cpu-shares value, --pcs value             VCH vCPUs shares, in level or share number, e.g. high, normal, low, or 4000 (default: <nil>)
   --bridge-network-range value, --bnr value        The ip range from which bridge networks are allocated (default: "172.16.0.0/12")
   --appliance-iso value, --ai value                The appliance iso
   --bootstrap-iso value, --bi value                The bootstrap iso
   --key value                                      Virtual Container Host private key file
   --cert value                                     Virtual Container Host x509 certificate file
   --no-tls, -k                                     Disable TLS support
   --force, -f                                      Force the install, removing existing if present
   --timeout value                                  Time to wait for appliance initialization (default: 3m0s)
   --advanced-options, -x                           Show all options
   --appliance-memory value                         Memory for the appliance VM, in MB (default: 2048)
   --appliance-cpu value                            vCPUs for the appliance VM (default: 1)
   --use-rp                                         Use resource pool for vch parent in VC
   --debug value, -v value                          [0(default),1...n], 0 is disabled, 1 is enabled, >= 1 may alter behaviour (default: 0)
   --help, -h                                       show help
   --generate-bash-completion
```

**Comment by emlin** [comment]
@cormachogan @hickeng Please have a look for this PR

**Comment by andrewtchin** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by emlin** [comment]
♻️

**Pull request merged**
