### PR TITLE
[skip ci] Minor doc edits resulting from self-review

### PR DESCRIPTION
**Pull request by stuclem**
Lots of small fixes of typos, or minor rewording for clarity. Cleaned up some unused files. Small amount of reorg.

### CODE REVIEW

**Comment by stuclem** [comment]
LGTM

**Comment by npakrasi** [comment]
LGTM

**Comment by stuclem** [comment]
Thanks @npakrasi !

**Comment by stuclem** [comment]
:recycle:

**Comment by stuclem** [comment]
:recycle:

**Pull request merged**
