### PR TITLE
Manually install govmomi to avoid gocov breakage in unit tests

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Add a line to install govmomi before we call go coverage so that the govmomi types package doesn't break gocov as seen in #2329 

 Hopefully this will resolve this issue. Locally I have been able to run `docker run -v $(pwd):/go/src/github.com/vmware/vic -w /go/src/github.com/vmware/vic golang:1.7 make -j3 all test` successfully several times, and was able to run the tests successfully in Drone a number of times as well (with the old WIP name of the PR displayed on these jobs):

https://ci.vmware.run/vmware/vic/5482
https://ci.vmware.run/vmware/vic/5484
https://ci.vmware.run/vmware/vic/5486
https://ci.vmware.run/vmware/vic/5487

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
:shipit:

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by andrewtchin** [comment]
lgtm

**Comment by dougm** [comment]
lgtm - though we should look at doing this within the Makefile, it'll speed up tests, gocode, etc.  Same could be said for other deps too of course.

**Comment by gigawhitlocks** [comment]
Yeah I just wasn't entirely sure the best place to put it in the Makefile and sticking it where I did ensured that it'd get run right before cover regardless

**Comment by hickeng** [comment]
@dougm it's possible my understanding of Go package resolution is flawed, but...

if we run `go install x` we're going to end up with %GOPATH/pkg/x
when we reference x in code, it first checks in `vendor` - isn't that going to negate the value of installing it for compilation and testing?

**Comment by dougm** [comment]
'vendor' is included path under $GOPATH/pkg too:

```
% rm -rf $GOPATH/pkg

% go install ./vendor/github.com/vmware/govmomi/govc

% go install -v ./cmd/vcsim
github.com/vmware/vic/vendor/github.com/google/uuid
github.com/vmware/vic/pkg/vsphere/simulator/esx
github.com/vmware/vic/pkg/vsphere/simulator/vc
github.com/vmware/vic/pkg/vsphere/simulator
github.com/vmware/vic/cmd/vcsim

% find $GOPATH -name types.a
$GOPATH/pkg/darwin_amd64/github.com/vmware/vic/vendor/github.com/vmware/govmomi/vim25/types.a
```

**Pull request merged**
