### PR TITLE
Swagger spec for container info and list

### LINKED ISSUE #1122: Port Layer: Create swagger definitions for getting container metadata and list of containers
We need some portlayer definitions that allows us to get container metadata (for docker inspect container) and get a list of containers (for docker ps).

related to #798 and #388

### PR DESCRIPTION
**Pull request by sflxn**
**WIP PR to allow collaboration between docker ps and docker inspect container**

Add in swagger spec to retrieve information about containers and get
a list of all containers in the system.  This supports #857 & #369.

Resolves #1122.

### CODE REVIEW

**Comment by sflxn** [comment]
@cgtexmex @corrieb

**Comment by caglar10ur** [comment]
LGTM

**Comment by corrieb** [comment]
Seems like a good place to start. With the caveat that the REST interface doesn't have to reflect the golang interface exactly, it would be good (eventually) to consider having the separation between container status and container config reflected in different API calls. Apart from reflecting different kinds of state (static config data vs dynamic runtime state data), the two calls will have different costs on the implementation side. The config call will only ever hit port layer caches, whereas the status call will have to hit tether(s) and potentially even the vmomi gateway. I hope to avoid the latter though with the event mechanism

**Comment by sflxn** [comment]
lgtm.  Haven't changed anything other then rebase.  Shouldn't require all new status.

**Pull request merged**
