### PR TITLE
[skip ci] Removed references to SFTP installation from UI install docs.

### PR DESCRIPTION
**Pull request by stuclem**
Following the removal of WinSCP from the build, removing all references to the SFTP install of the VIC UI.

Fixes https://github.com/vmware/vic/issues/2261.

### CODE REVIEW

**Comment by stuclem** [comment]
@jooskim can you please review? Thanks!

**Comment by stuclem** [comment]
Also fixes https://github.com/vmware/vic/issues/2136. Removed the question about VC 5.5 or 6.0 from the topic on deploying the UI to VCSA with a Web Server. I left the question in the topic about deploying to VCSA without a Web Server.

**Comment by jooskim** [comment]
LGTM

**Comment by stuclem** [comment]
LGTM to me too.

**Comment by stuclem** [comment]
:recycle:

**Pull request merged**
