### PR TITLE
Propagate debug/pprof config into containers

### PR DESCRIPTION
**Pull request by hickeng**
We've previously had pprof servers running in all of the components on port 6060 however we cannot have those running and exposed by default when we ship.

This PR propagates the debug flag into the containerVMs and uses that to configure logging and pprof.

Towards #2455

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by fdawg4l** [comment]
LGTM

**Comment by emlin** [comment]
lgtm 👍 
This make the debug process complete.

**Comment by hickeng** [comment]
poke

**Pull request merged**
