### PR TITLE
unmount /run

### LINKED ISSUE #1643: unable to run postgres:9.4
For some reason we're missing `/run/postgresql`

A quick hunt suggests that 60a4daae58264b9e52dbadafdc809e2d27a899fc2a5840f67a610cdbcf234289 is the ID in which this directory can be found, however it doesn't exist in our containers.

My hypothesis on the basis of a quick inspection is that the systemctl switch-root that we're using to move into the container filesystem is purging /run (or /var/run - which is a symlink to /run).

### PR DESCRIPTION
**Pull request by caglar10ur**
systemd is not purging but just propagating the mount points into the new
environment so we end up with a tmpfs /run instead of Dockerfile created
(static) one.

IMHO that's docker bug. Their images should not assume /run/XYZ
directories existence as systemd clearly says "Applications must ensure
to recreate their own files/dirs on startup, and cannot rely that doing
this at package installation will suffice. It" but since fixing all
those images are not possible we simply unmount /run in tether.

Fixes #1643

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

Assuming the syscall just returns an errno, EBUSY for example, might be good to add some context there: return fmt.Errorf("unmount /run: %s", err)

**Comment by caglar10ur** [comment]
in theory it shouldn't return EBUSY as we are telling it to perform a lazy unmount. According to man page MNT_DETACH does following

```
Perform a lazy unmount: make the mount point unavailable for
              new accesses, immediately disconnect the filesystem and all
              filesystems mounted below it from each other and from the
              mount table, and actually perform the unmount when the mount
              point ceases to be busy.
```

will add fmt.Errorf in every case :)

**Comment by hickeng** [comment]
What happens here if /run isn't mounted? That's an acceptable condition for us and is likely to be the case once we ditch systemd.

**Comment by caglar10ur** [comment]
I guess we error out if /run is not mounted, I'll add a check to confirm we have /run before trying to unmount

**Comment by caglar10ur** [comment]
@hickeng take a look again

**Comment by caglar10ur** [comment]
@hickeng ping

**Comment by hickeng** [comment]
LGTM

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
