### PR TITLE
List the path that keeps failing

### PR DESCRIPTION
**Pull request by mhagen-vmware**
For #2329 again

### CODE REVIEW

**Comment by vburenin** [comment]
LGTM

**Comment by rajanashok** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
.

**Comment by hickeng** [comment]
@mhagen-vmware can we have slightly more context in the commit - this is confusing in the commit log. A prefix or similar that denotes it as an infra element rather than product code would more than suffice.

**Pull request merged**
