### PR TITLE
Fixed datastore path leakage in docker info

### LINKED ISSUE #1540: Remove the vsphere datastore information from docker info plugin
The Plugins section of info is leaking vSphere topology data.
```
vagrant@devbox:~/vic$ docker -H 192.168.78.216:2376 --tls info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Storage Driver: vSphere Integrated Containers Backend Engine
vSphere Integrated Containers Backend Engine: RUNNING
Execution Driver: vSphere Integrated Containers Backend Engine
Plugins:
 Volume: ds://@datastore1/%5Bdatastore1%5D%20volumes-extra
 Network: bridge external
Kernel Version: 4.4.8-esx
```

When fixed this should show:
Plugins:
  Volume: default extra
  Network: bridge external

This **must not** show vsphere datastore paths

### PR DESCRIPTION
**Pull request by sflxn**
Fixes #1540

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by jzt** [comment]
lgtm

**Comment by sflxn** [comment]
poke

**Comment by sflxn** [comment]
poke

**Pull request merged**
