### PR TITLE
Remove resource pool limitation

### PR DESCRIPTION
**Pull request by emlin**

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by cgtexmex** [comment]
Would be nice to provide a description -- maybe a brief "why" of this change...otherwise LGTM

**Comment by emlin** [comment]
We still didn't expose parameters to set VCH limitation at this time, so we should not have a default reservation, although that is not a big number, empty resource pool will still consume resources.

In the future, we'll expose those parameters, and user could change this limitation manually, to limit VCH resources, and all container VMs created by this VCH.

**Comment by emlin** [comment]
> Would be nice to provide a description -- maybe a brief "why" of this change
@hickeng think this might be related to our current CI issue, so I had this quick PR.

**Comment by mhagen-vmware** [comment]
@cgtexmex When we kill jobs in the CI part of the problem is this reservation.  It hangs around and consumes 42MB of memory and never gets cleaned up.  So that builds up rather quickly and crashes all of our CI testing.  According to George, it isn't needed at all and is just an excessive reservation that doesn't help anything in later on.

**Comment by emlin** [comment]
Fixes #1189

**Pull request merged**
