### PR TITLE
[skip ci] Update and expand vicadmin access docs

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Added instructions for adding a client side certificate to Firefox, accessing vicadmin using `curl`, and corrected some smaller things.

### CODE REVIEW

**Comment by mdubya66** [comment]
I'm not sure @stuclem wants us editing the docs directly. This will require an looks from him.

**Comment by gigawhitlocks** [comment]
Yeah, whoops, won't merge unless you tell me to @stuclem -- in any case this is a nicely-formatted version that you can reference while writing the final version xD

Sorry about being out sick yesterday and being out of the loop

**Comment by stuclem** [comment]
No problem @gigawhitlocks, I'm grateful for the effort! Please do merge this PR.

LGTM

**Comment by mdubya66** [comment]
LGTM

**Comment by mdubya66** [comment]
Please make sure the SKIP CI is kept. Thanks

**Comment by gigawhitlocks** [comment]
♻️

**Pull request merged**
