### PR TITLE
move retry to pkg

### PR DESCRIPTION
**Pull request by emlin**
per @caglar10ur request, separate change for retry in pr #3172, in case anyone want to use retry logic in other modules.

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM, thanks Emma!

**Comment by hmahmood** [comment]
Hm.. I would name the package `retry`. In the future we can make the backoff scheme pluggable.

**Comment by hickeng** [comment]
LGTM - @hmahmood is on point

**Comment by emlin** [comment]
@hmahmood Understand the point for pluggable retry mechanism, but then the method call would be like retry.Retry(), is that a good name?

**Comment by hmahmood** [comment]
You could do `retry.Do()`, as `retry.Retry()` does stutter.

**Comment by emlin** [comment]
this one works. thanks

**Comment by hmahmood** [comment]
lgtm

**Comment by mdubya66** [comment]
Is this PR still relevant?

**Comment by emlin** [comment]
> Is this PR still relevant?

yes, it is. Start to rebase this one

**Comment by emlin** [comment]
.

**Pull request merged**
