### PR TITLE
Disable timesync service in appliance

### LINKED ISSUE #2340: "Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc4201fe0d8 Message:timeout waiting for layer to present as /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0}"
Seen on build:
https://ci.vmware.run/vmware/vic/4804

[integration_logs_4804_9374cde28de68dffc53baf87abe87c2174f5ad05_1473959100.zip](https://github.com/vmware/vic/files/475199/integration_logs_4804_9374cde28de68dffc53baf87abe87c2174f5ad05_1473959100.zip)

### PR DESCRIPTION
**Pull request by fdawg4l**
timesync doesn't follow NTP semantics and drift the clock to sync with
the ntp server eventually.  Instead, it slams the clock to the time it gets
from NTP, leading to weirdness in log timestamps and timeouts in
routines that use wallclock time to set deadlines before their time has
elapsed.

Fixes #2340

### CODE REVIEW

**Comment by vburenin** [comment]
LGTM

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by fdawg4l** [comment]
.

**Comment by fdawg4l** [comment]
wtf...   lgtm

**Pull request merged**
