### PR TITLE
[specific ci=9-01-VICAdmin-ShowHTML] Update tests to new status message responses from vch-admin

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Forgot to update the integration tests in my last PR

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by jzt** [comment]
LGTM 🍳 🤕

**Comment by gigawhitlocks** [comment]
:recycle:

**Comment by matthewavery** [comment]
LGTM

**Pull request merged**
