### PR TITLE
Update vendor/govmomi to 0.11.4 release

### PR DESCRIPTION
**Pull request by dougm**
Does not impact any existing vic runtime code paths.

Issue #1689 will make use of the new object.AuthorizationManager methods
and test/dev will make use of the new govc commands.

### CODE REVIEW

**Comment by dougm** [comment]
Diff from the last vendor govmomi update: https://github.com/vmware/govmomi/compare/v0.11.2...v0.11.4

**Comment by mdubya66** [comment]
lgtm

**Comment by mlh78750** [comment]
LGTM

**Comment by mlh78750** [comment]
LGTM

**Comment by mlh78750** [comment]
.

**Pull request merged**
