### PR TITLE
[full ci] Revert govc changes and update event page value

### PR DESCRIPTION
**Pull request by mdharamadas1**
~~Revert "Increase event page size to 1000 (#6937)~~
Change event page size to 300
Revert "Integration image govc v0.16.0 (#6788)"
Add GitHub check to two failing vic machine tests

### CODE REVIEW

**Comment by cgtexmex** [comment]
Why the revert?

**Comment by mdharamadas1** [comment]
@cgtexmex Sorry, didn't mention earlier but this is just for testing purpose as requested by @mhagen-vmware

**Comment by cgtexmex** [comment]
so why revert from master and pollute the git history?  Can't we use a different branch?  Or is this a CI / Testing limitation?

**Comment by mhagen-vmware** [comment]
Not going to merge it, just testing

**Comment by andrewtchin** [comment]
Merging this will break some of the tests in https://github.com/vmware/vic/pull/6816 so those will need to be disabled or something

**Comment by mdharamadas1** [comment]
All, I have updated the description for this PR.

**Comment by hickeng** [comment]
#6998 addressed this

**Pull request closed without merging**
