### PR TITLE
Fix vicadmin UI alignment[skip ci]

### LINKED ISSUE #3045: Minor UI text alignment bug in Vic Admin
The text `VIEW ON GITHUB` is not centered vertically because the github icon is slightly taller than the text:

screen shot 2016-11-07 at 3 08 06 pm

CSS should be tweaked to align this text properly.

The bug is especially visible next to the properly-aligned `LOG OUT` button: 
screen shot 2016-11-07 at 3 10 42 pm

### PR DESCRIPTION
**Pull request by sgairo**
Fixes #3045

### CODE REVIEW

**Comment by sgairo** [comment]
@gigawhitlocks @anchal-agrawal

**Comment by caglar10ur** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
Looks good! Please change `auth.html` as well.

**Comment by andrewtchin** [comment]
lgtm

**Comment by sgairo** [comment]
ping

**Pull request merged**
