### PR TITLE
Fix for tests

### PR DESCRIPTION
**Pull request by gigawhitlocks**
@fdawg4l 's fix for the failing integration tests pending resolution of the underlying issue

### CODE REVIEW

**Comment by emlin** [comment]
LGTM

**Comment by hickeng** [comment]
LGTM. Underlying issue is #725

**Comment by mdubya66** [comment]
LGTM

**Comment by gigawhitlocks** [comment]
Tests still fail, same place but different issue, with this change. See http://smithers.eng.vmware.com:8080/job/ian_tests_his_fork/7/console . @fdawg4l is investigating.

**Comment by hickeng** [comment]
@gigawhitlocks recommend you try running /bin/date instead of a shell - if stdin closing isn't propagating the the shell may sit there indefinitely awaiting input.

**Comment by fdawg4l** [comment]
@gigawhitlocks on a clean esx with a clean build with this diff, it passes for me locally.

**Comment by mdubya66** [comment]
i vote we push this change and we let @fdawg4l figure out the new failure under a new issue.

**Comment by gigawhitlocks** [comment]
Switched to running `/bin/date` & will merge once Drone lets me

**Pull request merged**
