### PR TITLE
Reduce boilerplate in vic-machine API handlers

### LINKED ISSUE #7944: Reduce duplication between and within VCH Management API handlers
Significant duplication exists between and within VCH Management API handlers. Addressing this will require extracting common code into packages which are cohesive and loosely coupled. Operation-specific code should be more tightly bound to the associated handler(s).

### PR DESCRIPTION
**Pull request by zjs**
Extract code for validation and dispatch into a new package, client,
and refactor common code for building a data.Data struct containing
target information (vSphere endpoint, thumbprint, datacenter, compute
resource, and VCH ID) into a new package, target.
    
Add unit tests for the client package, introducing public and private
interfaces as necessary.
    
Reduce duplication of code between related handlers and use embedding
to better share code.
    
Update handler documentation.

Fixes #7944 

`[specific ci=Group23-VIC-Machine-Service]`

### CODE REVIEW

**Comment by vburenin** [comment]
Do you plan to do a lot of such type of refactoring? Asking since I am also working on something in parallel in a hidden mode, so changes like this may affect things I am working on. Not asking to stop, I am asking to plan on what to expect.

**Comment by zjs** [comment]
> Do you plan to do a lot of such type of refactoring? Asking since I am also working on something in parallel in a hidden mode, so changes like this may affect things I am working on. Not asking to stop, I am asking to plan on what to expect.

#6032 is going to involve substantial refactoring of the `vic-machine-server` API handlers, the `vic-machine` CLI commands, and the shared code under `lib/install` (but shouldn't creep far outside those areas). That ticket has a few specific items we need to address, but I think the overall goals are to (1) reduce duplication within and between the API handlers and CLI commands, (2) allow such code to be unit tested, and (3) decrease fragility.

**Comment by zjs** [comment]
CI pre-rebase: https://ci-vic.vmware.com/vmware/vic/19023/7

**Comment by zjs** [comment]
Clean CI: https://ci-vic.vmware.com/vmware/vic/19038

**Pull request merged**
