### PR TITLE
Implement attach tests and move TTY tests to manual

### LINKED ISSUE #1582: cannot enable tty mode on non tty input
Our integration tests are now failing on the link test.  It works locally when running robot directly, but I am able to reproduce when I run using drone locally, so it appears to be some sort of nested container/drone related issue.

### LINKED ISSUE #2896: docker attach tests are flaky
Attach sometimes takes a long time or fails to return which causes problems for the tests. The fifo method we were using to input to an attached container seems to no longer work. Checking the status of a previously attached container using `ps -a` sometimes shows status as `Stopped` instead of `Exited`

Current tests in 
`tests/test-cases/Group1-Docker-Commands/1-25-Docker-Port-Map.robot`
`test-cases/Group1-Docker-Commands/1-06-Docker-Run.robot`

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Fixes #1582 
Fixes #2896

### CODE REVIEW

**Comment by rajanashok** [comment]
LGTM

**Comment by sgairo** [comment]
LGTM

**Comment by sgairo** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
