### PR TITLE
Fix go vet errors

### PR DESCRIPTION
**Pull request by dougm**
Don't know why this isn't happening in CI, via 'make check':

```
./cmd/imagec/docker.go:193: declaration of err shadows declaration at ./cmd/imagec/docker.go:154: 
./cmd/imagec/fetcher.go:154: declaration of err shadows declaration at ./cmd/imagec/fetcher.go:117: 
```

### CODE REVIEW

**Comment by fdawg4l** [comment]
:eyes: :+1: :v: :meat_on_bone:

**Comment by dougm** [comment]
@caglar10ur pointed out the govet target was broken.. included his fix and got rid of all the vet warnings.

**Comment by emlin** [comment]
Looks like we cannot write like following
a, err := XXX, if a is not defined, but err is already there. Is that a best practice?

**Comment by caglar10ur** [comment]
LGTM :sheep: :it: 👍 👯

**Comment by dougm** [comment]
@emlin yes, shadow checker is a fairly new feature of go vet: https://golang.org/cmd/vet/#hdr-Shadowed_variables

**Pull request merged**
