### PR TITLE
update integration tests to reflect newly merged PRs

### PR DESCRIPTION
**Pull request by corrieb**
[skip-ci]

should solve:
```
------------------------------------------------------------------------------
Create and start named container                                      | FAIL |
Test 1-4-Docker-Create.robot needs to be updated now that Issue #1234 has been resolved
------------------------------------------------------------------------------
Create linked containers that can ping                                | FAIL |
Test 1-4-Docker-Create.robot needs to be updated now that Issue #430 has been resolved
------------------------------------------------------------------------------
Test-Cases.Group1-Docker-Commands.1-4-Docker-Create :: Test 1-4 - ... | FAIL |
7 critical tests, 5 passed, 2 failed
7 tests total, 5 passed, 2 failed
```

### CODE REVIEW

**Comment by jzt** [comment]
LGTM

**Comment by mdubya66** [comment]
lgtm

**Comment by andrewtchin** [comment]
I don't think they're needed anymore so could you delete the lines that check the issue instead of commenting them out?
lgtm either way

**Comment by corrieb** [comment]
@andrewtchin I think it's actually a useful audit trail to see what issue these tests were tied back to. At least in the short term. If they fail, we have a place to refer to

**Comment by corrieb** [comment]
ping

**Pull request merged**
