### PR TITLE
Initial functional test plan [skip ci]

### PR DESCRIPTION
**Pull request by mhagen-vmware**

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by matthewavery** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
.

**Comment by mhagen-vmware** [comment]
:recycle:

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by andrewtchin** [comment]
lgtm

**Pull request merged**
