### PR TITLE
Don't provide redundant 'images' default for image store path

### LINKED ISSUE #2081: Remove redundant "images" directory from path when vic-machine -i only includes a datastore
`./vic-machine-linux create ... -i datastore1`

**Expected behavior:**
`./VIC/564d9a86-068d-dfad-823e-0d0a2b4c76df/images/scratch/scratch.vmdk`

**Actual behavior:**
**./images**`/VIC/564d9a86-068d-dfad-823e-0d0a2b4c76df/images/scratch/scratch.vmdk`

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Fixes #2081 

Was appending an additional `images` into the image store path. This fixes that.

### CODE REVIEW

**Comment by fdawg4l** [comment]
LGTM

**Comment by matthewavery** [comment]
LGTM

**Comment by gigawhitlocks** [comment]
.

**Comment by fdawg4l** [comment]
Any updates on this? Are we waiting to merge this?

**Comment by gigawhitlocks** [comment]
I'm about to merge it, just merged in master to let tests run

**Comment by gigawhitlocks** [comment]
.

**Comment by gigawhitlocks** [comment]
.

**Pull request merged**
