### PR TITLE
Add the full round robin for network interfaces

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Not clear exactly what is going on here, but filing an issue to clarify.  For now, just allow that we appear to be randomly round robin'ing on which interfaces we report as sharing the same NIC.

### CODE REVIEW

**Comment by mhagen-vmware** [comment]
#3104

**Comment by matthewavery** [comment]
What happens if none of them share a NIC?

**Comment by matthewavery** [comment]
lgtm

**Comment by andrewtchin** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
