### PR TITLE
Restore collection of vmware.log

### PR DESCRIPTION
**Pull request by hickeng**
Restores the collection of vmware.log for the VMs and drops
collecting the containerVM output, which is purely customer application
data. Also renames misnamed variables.
Original changes were in #2604 

Fixes #2604

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by matthewavery** [comment]
Would this change also affect the target of the `docker logs` that was changed in #2604

**Comment by matthewavery** [comment]
@hickeng  yes, looks like I misunderstood one of the logs. the `docker logs` target looks to now be collecting(or trying to) the `output.log` file that I renamed... instead of the <containerID>.log . Would it be worth it to rename the actual output log to `output.log`?

**Comment by hickeng** [comment]
@matthewavery the actual output log _is still_ output.log which is what `docker logs` uses.
It's just not the log we wanted, which was vmware.log, which contains the vSphere level diagnostics.

**Comment by matthewavery** [comment]
In that case LGTM

**Comment by hickeng** [comment]
poke

**Comment by matthewavery** [comment]
LGTM

**Pull request merged**
