### PR TITLE
Continuing deleting other dangling VCHs even if one fails

### PR DESCRIPTION
**Pull request by mhagen-vmware**

### CODE REVIEW

**Comment by rajanashok** [comment]
lgtm

**Comment by sgairo** [comment]
Even if only one fails, list would still fail correct? Is this just for keeping the buildup smaller?

**Comment by chengwang86** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
correct @sgairo It will still cause other problems for other tests, but this at least prevents the list from piling up.

**Pull request merged**
