### PR TITLE
reduce the verbosity of vspc

### PR DESCRIPTION
**Pull request by kreamyx**
vspc becomes verbose only if the vch config debug level is greater than 2

### CODE REVIEW

**Comment by caglar10ur** [comment]
ping @kreamyx, I need this in my life :)

**Comment by kreamyx** [comment]
@caglar10ur haha it is ready! just waiting for 'Verify'

**Comment by mdubya66** [comment]
@mhagen-vmware I'd like to consider this for RC3.

**Comment by mhagen-vmware** [comment]
@mdubya66   This is just a nice to have reduction in logging verbosity right?  I wouldn't think that would be a candidate for an RC build...

**Comment by mdubya66** [comment]
how verbose is the question? is it causing the log to rotate where we lose the ability to debug?

**Comment by kreamyx** [comment]
@mdubya66 it really depends on the serial data moving back and forth. It can get pretty ugly if there is a lot of data flowing. Moreover, the verbose logging will only be needed if debugging a problem caused by the vspc. Otherwise, it is not really relevant for normal debugging purposes.

**Pull request merged**
