### PR TITLE
Expanded functional testing [skip ci]

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Adding functional tests for VSAN, clustering, and heterogenous topologies. Still working on NSX, but wanted to finish this up for now.

### CODE REVIEW

**Comment by gigawhitlocks** [comment]
This is awesome. LGTM

**Comment by andrewtchin** [comment]
how does the drone server get to nimbus/nimbus gateway?

**Comment by andrewtchin** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
Drone server does not get to the nimbus server, that is why I have these test cases in the "manual" test cases folder.

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
