### PR TITLE
Disable tests

### PR DESCRIPTION
**Pull request by corrieb**
[skip-ci]

Tests that were re-enabled in PR #1399 fail with a crash.

Will urgently investigate the crash, but will temporarily disable these tests in order to facilitate further merges.

### CODE REVIEW

**Comment by jzt** [comment]
LGTM  FYI, for some reason the [skip-ci] tag didn't cause this to skip CI. Tagging @andrewtchin.

**Comment by corrieb** [comment]
I messed this up somehow - it pulled in my previous commit

**Comment by jzt** [comment]
Looks like it needs to go in the title, not the description.

**Comment by andrewtchin** [comment]
lgtm

**Pull request merged**
