### PR TITLE
Handle unspecified cluster in vic-machine create

### LINKED ISSUE #1285: vic-machine-linux failed:  Creating resource pool failed: ServerFaultCode: A specified parameter was not correct:
**VIC Version:**

0.1 / master / 2416

// A self-contained demonstration of the problem follows...

Trying to create a new VCH using vic-machine-linux from #2416

```ts
root@photon-NaTv5i8IA [ /workspace/vic ]# ./vic-machine-linux create  --bridge-network Bridge-DPG --image-datastore isilion-nfs-01 -t "administrator@vsphere.local@10.27.51.103" --compute-resource Mgmt
INFO[2016-06-30T10:37:12Z] Please enter ESX or vCenter password:
INFO[2016-06-30T10:37:16Z] ### Installing VCH ####
INFO[2016-06-30T10:37:16Z] Generating certificate/key pair - private key in ./docker-appliance-key.pem
INFO[2016-06-30T10:37:16Z] Validating supplied configuration
INFO[2016-06-30T10:37:16Z] Firewall status: DISABLED on /CNA-DC/host/Mgmt/10.27.51.8
INFO[2016-06-30T10:37:16Z] Firewall configuration OK on hosts:
INFO[2016-06-30T10:37:16Z]   /CNA-DC/host/Mgmt/10.27.51.8
INFO[2016-06-30T10:37:17Z] License check OK on hosts:
INFO[2016-06-30T10:37:17Z]   /CNA-DC/host/Mgmt/10.27.51.8
INFO[2016-06-30T10:37:17Z] DRS check OK on:
INFO[2016-06-30T10:37:17Z]   /CNA-DC/host/Mgmt/Resources
INFO[2016-06-30T10:37:18Z] Creating Resource Pool docker-appliance
INFO[2016-06-30T10:37:18Z] Collecting a0522635-224e-4171-92b1-7edaf726b39f vpxd.log
vic-machine-linux failed:  Creating resource pool failed: ServerFaultCode: A specified parameter was not correct:
```

Here is the vpxd.log:

```ts
root@photon-NaTv5i8IA [ /workspace/vic ]# cat vpxd.log
2016-06-30T10:37:18.891Z info vpxd[7EFC0CD8F700] [Originator@6876 sub=vpxLro opID=6b73a95a] [VpxLRO] -- BEGIN task-internal-4084009 -- LicenseAssignmentManager -- vim.LicenseAssignmentManager.queryAssignedLicenses -- 528efe71-7422-0b70-d398-f9ab5951a9ab(52bebf8a-ec28-29d0-1b66-8aaa4ed2a0f2)
2016-06-30T10:37:19.003Z info vpxd[7EFC0CD8F700] [Originator@6876 sub=vpxLro opID=6b73a95a] [VpxLRO] -- FINISH task-internal-4084009
2016-06-30T10:37:20.561Z info vpxd[7EFC0D8A5700] [Originator@6876 sub=vpxLro opID=998fc96] [VpxLRO] -- BEGIN task-3815 -- resgroup-419 -- vim.ResourcePool.createResourcePool -- 528efe71-7422-0b70-d398-f9ab5951a9ab(52bebf8a-ec28-29d0-1b66-8aaa4ed2a0f2)
2016-06-30T10:37:20.567Z info vpxd[7EFC0D8A5700] [Originator@6876 sub=vpxLro opID=998fc96] [VpxLRO] -- FINISH task-3815
2016-06-30T10:37:20.567Z info vpxd[7EFC0D8A5700] [Originator@6876 sub=Default opID=998fc96] [VpxLRO] -- ERROR task-3815 -- resgroup-419 -- vim.ResourcePool.createResourcePool: vmodl.fault.InvalidArgument:
--> Result:
--> (vmodl.fault.InvalidArgument) {
-->    faultCause = (vmodl.MethodFault) null,
-->    invalidProperty = <unset>,
-->    msg = ""
--> }
--> Args:
-->
--> Arg name:
--> "docker-appliance"
--> Arg spec:
--> (vim.ResourceConfigSpec) {
-->    entity = <unset>,
-->    changeVersion = <unset>,
-->    lastModified = <unset>,
-->    cpuAllocation = (vim.ResourceAllocationInfo) {
-->       reservation = <unset>,
-->       expandableReservation = true,
-->       limit = -1,
-->       shares = (vim.SharesInfo) {
-->          shares = 0,
-->          level = "normal"
-->       },
-->       overheadLimit = <unset>
-->    },
-->    memoryAllocation = (vim.ResourceAllocationInfo) {
-->       reservation = <unset>,
-->       expandableReservation = true,
-->       limit = -1,
-->       shares = (vim.SharesInfo) {
-->          shares = 0,
-->          level = "normal"
-->       },
-->       overheadLimit = <unset>
-->    },
--> }
```

**Expected behavior:**

This is the same syntax for _vic-machine-linux_ that I have been using for a few days time. I'm not sure if something has changed and I need to include another argument, but at the very least the error should report something more meaningful.

**Actual behavior:**

As above.

### PR DESCRIPTION
**Pull request by andrewtchin**
We were seeing a nil pointer dereference when trying to perform checks based on an unset cluster. Now we handle that gracefully.

```
INFO[2016-06-30T13:53:52-07:00] ### Installing VCH ####                      
INFO[2016-06-30T13:53:52-07:00] Generating certificate/key pair - private key in ./chin-vic-101-key.pem 
INFO[2016-06-30T13:53:53-07:00] Validating supplied configuration            
INFO[2016-06-30T13:53:53-07:00] Suggesting valid values for --compute-resource based on * 
INFO[2016-06-30T13:53:53-07:00]   Austin                                     
INFO[2016-06-30T13:53:53-07:00]   JoshCluster                                
ERRO[2016-06-30T13:53:54-07:00] Firewall check SKIPPED                       
ERRO[2016-06-30T13:53:54-07:00]   cluster not set                            
ERRO[2016-06-30T13:53:54-07:00] License check SKIPPED                        
ERRO[2016-06-30T13:53:54-07:00]   cluster not set                            
ERRO[2016-06-30T13:53:54-07:00] DRS check SKIPPED                            
ERRO[2016-06-30T13:53:54-07:00]   cluster not set                            
ERRO[2016-06-30T13:53:54-07:00] Compatibility check SKIPPED                  
ERRO[2016-06-30T13:53:54-07:00]   cluster not set                            
ERRO[2016-06-30T13:53:54-07:00] --------------------                         
ERRO[2016-06-30T13:53:54-07:00] No unambiguous default compute resource available: --compute-resource must be specified 
ERRO[2016-06-30T13:53:54-07:00] Firewall check SKIPPED                       
ERRO[2016-06-30T13:53:54-07:00] License check SKIPPED                        
ERRO[2016-06-30T13:53:54-07:00] DRS check SKIPPED                            
ERRO[2016-06-30T13:53:54-07:00] Compatibility check SKIPPED                  
ERRO[2016-06-30T13:53:54-07:00] Creation cannot continue: configuration validation failed 
vic-machine-linux failed:  validation of configuration failed
```

Fixes #1285

### CODE REVIEW

**Comment by gigawhitlocks** [comment]
LGTM

**Comment by gigawhitlocks** [comment]
:sheep: :it:

**Comment by emlin** [comment]
lgtm

**Comment by andrewtchin** [comment]
♻️

**Pull request merged**
