### PR TITLE
Implement ContainerRestart

### LINKED ISSUE #805: Support restart of containers via docker restart
`docker restart` should restart the container vm.

(I don't know if this should be an "epic".  Please modify as you see fit.)

### PR DESCRIPTION
**Pull request by caglar10ur**
Restart is a stop followed by start without touching the network state.

Fixes #805

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by fdawg4l** [comment]
lgtm

**Comment by hmahmood** [comment]
I would prefer you make bind idempotent ... look at https://github.com/vmware/vic/blob/master/lib/portlayer/network/context.go#L418 and

**Comment by caglar10ur** [comment]
@hmahmood do you suggest adding restart as new state and returning early from bind/unbound when Handle.State is Restart? I thought about doing that but adding restart as a state sounded strange to me.

**Comment by hmahmood** [comment]
No I was suggesting make bind and unbind be idempotent always. So the line I referenced above, instead of returning an error we would just log a warning maybe, and return nil.

**Comment by hmahmood** [comment]
Idempotent bind and unbind will be tackled in a separate PR. LGTM

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
