### PR TITLE
[skip ci] Review feedback for docker commands and use/limitations of VIC

### PR DESCRIPTION
**Pull request by npakrasi**
Incorporated review feedback for supported docker commands table
Added workflow guidelines to Use and Limitations topic
Fixed # 3381, 3353

### CODE REVIEW

**Comment by npakrasi** [comment]
LGTM

**Comment by stuclem** [comment]
LGTM

**Comment by stuclem** [comment]
:recycle:

**Comment by stuclem** [comment]
:recycle:

**Pull request merged**
