### PR TITLE
 [full ci]  Use docker1.13 by default

### PR DESCRIPTION
**Pull request by jakedsouza**
Changes -
- Change docker file for integration image to use 1.13 as the
  default docker binary
- Updated all references to the integration image to use a new tag 1.24
- Updated secrets file with the same change

Fixes: #4368

### CODE REVIEW

**Comment by jakedsouza** [comment]
@maplain I pushed tag 1.24. For the DIND work could you push a new tag which includes this change as 1.25

**Comment by mdubya66** [comment]
For the #4504 issue should we release note #4504 and comment out that test until it's fixed? @mhagen-vmware?

**Comment by mdubya66** [comment]
FYI, We support Docker API version 1.25, not 1.24. I am not sure that is what is being referenced. 

Docker client version 1.13.0
Docker API version 1.25
Docker Compose version 1.9.0 and v2 and v2.1 compose files only

**Comment by mhagen-vmware** [comment]
Yep, known issue with our current testing requirements so we should comment out #4504 test.

**Comment by mhagen-vmware** [comment]
For the disposition of the failures in 1-24, ~we need to comment out the end of the test and tag it with a github check for #4561 ~ actually we can just change the last rc check to an output check:
```
    ${rc}  ${output}=  Run And Return Rc And Output  docker %{VCH-PARAMS} run --net jedi debian ping -c1 first
    Should Be Equal As Integers  ${rc}  0
    Should Not Contain  ${output}  Error

    # cannot reach first from another network
    ${rc}  ${output}=  Run And Return Rc And Output  docker %{VCH-PARAMS} run debian ping -c1 first
    ~Should Not Be Equal As Integers  ${rc}  0~
    Should contain  ${output}  unknown host
```

**Comment by jakedsouza** [comment]
> For the disposition of the failures in 1-24, we need to comment out the end of the test and tag it with a github check for 4561 actually we can just change the last rc check to an output check:
> 
> ${rc} ${output}= Run And Return Rc And Output docker %{VCH-PARAMS} run --net jedi debian ping -c1 first
> Should Be Equal As Integers ${rc} 0
> Should Not Contain ${output} Error
> 
> # cannot reach first from another network
> ${rc} ${output}= Run And Return Rc And Output docker %{VCH-PARAMS} run debian ping -c1 first
> Should Not Be Equal As Integers rc 0
> Should contain ${output} unknown host

@mhagen-vmware This would have to be done for some other tests that check for a non zero return code. I think the same "fix" would work for test failures in 1-17

**Comment by mhagen-vmware** [comment]
Yep, based on the current bug, any test that checks for non-0 rc will need to be changed.

**Comment by mhagen-vmware** [comment]
we need to have at least one of them that does a github check instead of modifying the test though:
```${status}=  Get State Of Github Issue  780
    Run Keyword If  '${status}' == 'closed'  Fail  Test 1-1-Docker-Info.robot needs to be updated now that Issue #780 has been resolved
```

**Comment by jakedsouza** [comment]
> Blocked by #4504

@caglar10ur #4504 does not seem to break any existing tests.

**Pull request merged**
