### PR TITLE
fix invalid argument issue in vc 6.0u3

### PR DESCRIPTION
**Pull request by emlin**
This PR is to fix vic-machine create --use-rp failure

### CODE REVIEW

**Comment by chengwang86** [comment]
Could you please elaborate a bit about the DBS failure and the fix to help us understand the rationale? It will also be useful for debugging if we observe failures related to this feature in the future.

**Comment by mdubya66** [comment]
see bug 1952991 @chengwang86

**Comment by cgtexmex** [comment]
@emlin is this suppose to create the Resource Pool if it doesn't exist?  Or just use a previously created RP?

**Comment by cgtexmex** [comment]
@emlin figured it out...I was incorrectly passing the RP that I wanted to create via the `-r` argument, but it just names the RP the same as the specified appliance `-n`...anyhoo...

LGTM

**Comment by mdubya66** [comment]
does this work on 6.5

**Comment by emlin** [comment]
It's for new resource pool creation.
Didn't add anything more is because the vsphere error message is not straight forward, you'll need to get vpxd log to get details.
Here is one sample error in vpxd
```
2017-09-07T19:41:15.015Z info vpxd[7F439B1DC700] [Originator@6876 sub=Default opID=7cf2b98b] [VpxLRO] -- ERROR task-258 -- resgroup-8 -- vim.ResourcePool.createResourcePool: vmodl.fault.InvalidArgument:
--> Result:
--> (vmodl.fault.InvalidArgument) {
-->    faultCause = (vmodl.MethodFault) null,
-->    invalidProperty = <unset>,
-->    msg = ""
--> }
--> Args:
-->
--> Arg name:
--> "test-rp"
--> Arg spec:
--> (vim.ResourceConfigSpec) {
-->    entity = <unset>,
-->    changeVersion = <unset>,
-->    lastModified = <unset>,
-->    cpuAllocation = (vim.ResourceAllocationInfo) {
-->       reservation = 1,
-->       expandableReservation = true,
-->       limit = -1,
-->       shares = (vim.SharesInfo) {
-->          shares = 0,
-->          level = "normal"
-->       },
-->       overheadLimit = -1
-->    },
-->    memoryAllocation = (vim.ResourceAllocationInfo) {
-->       reservation = 1,
-->       expandableReservation = true,
-->       limit = -1,
-->       shares = (vim.SharesInfo) {
-->          shares = 0,
-->          level = "normal"
-->       },
-->       overheadLimit = -1
-->    },
--> }

```

**Comment by emlin** [comment]
Actually even with this message, it didn't tell you what's wrong.

**Comment by emlin** [comment]
Yes, I tested it in my 6.5 env

**Comment by cgtexmex** [comment]
@mdubya66 yes -- I deployed to 6.5 and created a new RP...

**Comment by emlin** [comment]
this is for a wrong branch, already had one for master branch, so close it.

**Pull request closed without merging**
