### PR TITLE
[specific ci=6-07-Create-Network] Validate bridge network range

### LINKED ISSUE #3212: network validation does not block wrong bridge ip range
This is one beta customer reported issue. They set bridge ip range, but portlayer network initialization failed with following error message
```
could not initialize port layer: bridge mask is not compatible with bridge pool mask
```

For this issue, at least vic-machine create should fail the deployment with reasonable error message. 
And right now bridge ip range is exposed, but bridge ip width is not, which can be exposed as well, to leave user more flexibility to configure bridge network.

### PR DESCRIPTION
**Pull request by andrewtchin**
Fixes #3212 

Port layer uses a default mask of 16 bits so if vic-machine sets the bridge IP range to a network smaller than /16, port layer gives the error `bridge mask is not compatible with bridge pool mask`. 
This change prevents the user from creating a VCH with a bridge pool that's too small. We will later expose a configuration option for the bridge mask so the user can specify any size bridge pool. 
Added integration test to check for this error.

Attempting to create VCH with too small bridge network pool
```
⇒  bin/vic-machine-linux create --target root:password@10.17.109.132 --name chin-vic-25 --thumbprint DC:5F:3C:3B:57:37:25:A0:84:C8:4E:31:48:00:C0:14:62:D9:95:E2 --bridge-network-range 172.16.0.0/17 --no-tlsverify             
Error opening logfile vic-machine.log: open vic-machine.log: permission denied
Jan 27 2017 09:05:43.753-08:00 INFO  ### Installing VCH ####
Jan 27 2017 09:05:43.753-08:00 WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Jan 27 2017 09:05:43.754-08:00 INFO  Loaded server certificate chin-vic-25/server-cert.pem
Jan 27 2017 09:05:43.754-08:00 WARN  Configuring without TLS verify - certificate-based authentication disabled
Jan 27 2017 09:05:45.517-08:00 INFO  Validating supplied configuration
Jan 27 2017 09:05:46.937-08:00 INFO  Using default datastore: datastore1
Jan 27 2017 09:05:48.949-08:00 INFO  Firewall status: DISABLED on "/ha-datacenter/host/ib-aus-office-132.eng.vmware.com/ib-aus-office-132.eng.vmware.com"
Jan 27 2017 09:05:49.170-08:00 WARN  Firewall configuration will be incorrect if firewall is reenabled on hosts:
Jan 27 2017 09:05:49.170-08:00 WARN  	"/ha-datacenter/host/ib-aus-office-132.eng.vmware.com/ib-aus-office-132.eng.vmware.com"
Jan 27 2017 09:05:49.170-08:00 INFO  Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled
Jan 27 2017 09:05:49.292-08:00 WARN  Evaluation license detected. VIC may not function if evaluation expires or insufficient license is later assigned.
Jan 27 2017 09:05:49.292-08:00 INFO  License check OK
Jan 27 2017 09:05:49.292-08:00 INFO  DRS check SKIPPED - target is standalone host
Jan 27 2017 09:05:50.500-08:00 ERROR --------------------
Jan 27 2017 09:05:50.500-08:00 ERROR Specified bridge network range is not large enough for the default bridge network size. --bridge-network-range must be /16 or larger network.
Jan 27 2017 09:05:50.500-08:00 ERROR Create cannot continue: configuration validation failed
Jan 27 2017 09:05:50.500-08:00 ERROR --------------------
Jan 27 2017 09:05:50.500-08:00 ERROR vic-machine-linux create failed: validation of configuration failed
```

VCH with large enough bridge network pool:
```
⇒  bin/vic-machine-linux create --target root:password@10.17.109.132 --name chin-vic-25 --thumbprint DC:5F:3C:3B:57:37:25:A0:84:C8:4E:31:48:00:C0:14:62:D9:95:E2 --bridge-network-range 172.16.0.0/16 --no-tlsverify
Error opening logfile vic-machine.log: open vic-machine.log: permission denied
Jan 27 2017 09:07:03.487-08:00 INFO  ### Installing VCH ####
Jan 27 2017 09:07:03.487-08:00 WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Jan 27 2017 09:07:03.488-08:00 INFO  Loaded server certificate chin-vic-25/server-cert.pem
Jan 27 2017 09:07:03.488-08:00 WARN  Configuring without TLS verify - certificate-based authentication disabled
Jan 27 2017 09:07:05.233-08:00 INFO  Validating supplied configuration
Jan 27 2017 09:07:06.603-08:00 INFO  Using default datastore: datastore1
Jan 27 2017 09:07:08.602-08:00 INFO  Firewall status: DISABLED on "/ha-datacenter/host/ib-aus-office-132.eng.vmware.com/ib-aus-office-132.eng.vmware.com"
Jan 27 2017 09:07:08.834-08:00 WARN  Firewall configuration will be incorrect if firewall is reenabled on hosts:
Jan 27 2017 09:07:08.834-08:00 WARN  	"/ha-datacenter/host/ib-aus-office-132.eng.vmware.com/ib-aus-office-132.eng.vmware.com"
Jan 27 2017 09:07:08.834-08:00 INFO  Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled
Jan 27 2017 09:07:08.954-08:00 WARN  Evaluation license detected. VIC may not function if evaluation expires or insufficient license is later assigned.
Jan 27 2017 09:07:08.954-08:00 INFO  License check OK
Jan 27 2017 09:07:08.954-08:00 INFO  DRS check SKIPPED - target is standalone host
Jan 27 2017 09:07:10.241-08:00 INFO  
Jan 27 2017 09:07:11.989-08:00 INFO  Creating Resource Pool "chin-vic-25"
Jan 27 2017 09:07:12.112-08:00 INFO  Creating VirtualSwitch
Jan 27 2017 09:07:12.361-08:00 INFO  Creating Portgroup
Jan 27 2017 09:07:12.738-08:00 INFO  Creating appliance on target
Jan 27 2017 09:07:12.859-08:00 INFO  Network role "client" is sharing NIC with "public"
Jan 27 2017 09:07:12.859-08:00 INFO  Network role "management" is sharing NIC with "public"
Jan 27 2017 09:07:15.299-08:00 INFO  Uploading images for container
Jan 27 2017 09:07:15.299-08:00 INFO  	"/home/chin/go/src/github.com/vmware/vic/bin/bootstrap.iso"
Jan 27 2017 09:07:15.301-08:00 INFO  	"/home/chin/go/src/github.com/vmware/vic/bin/appliance.iso"
Jan 27 2017 09:07:24.685-08:00 INFO  Waiting for IP information
Jan 27 2017 09:07:36.871-08:00 INFO  Waiting for major appliance components to launch
Jan 27 2017 09:07:38.441-08:00 INFO  Checking VCH connectivity with vSphere target
Jan 27 2017 09:07:39.832-08:00 INFO  vSphere API Test: https://10.17.109.132 vSphere API target responds as expected
Jan 27 2017 09:07:46.893-08:00 INFO  Initialization of appliance successful
...
Jan 27 2017 09:07:46.893-08:00 INFO  
Jan 27 2017 09:07:46.893-08:00 INFO  Connect to docker:
Jan 27 2017 09:07:46.893-08:00 INFO  docker -H 10.17.109.176:2376 --tls info
Jan 27 2017 09:07:46.893-08:00 INFO  Installer completed successfully

⇒  docker -H 10.17.109.176:2376 --tls run -it busybox
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
4b0bc1c4050b: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:348432dd709c2cd6ca42e56c2a0d157f611c50c908e14c9bfc1e9cb0ed234871
Status: Downloaded newer image for library/busybox:latest
/ # 

```

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by madmaxT800** [comment]
how to fix this? i get the same error if i want to add my photone machine via vic to vcenter

**Comment by mhagen-vmware** [comment]
@madmaxT800 This is a pull request to merge code, not a bug report. Are you seeing this error?:

Jan 27 2017 09:05:50.500-08:00 ERROR Specified bridge network range is not large enough for the default bridge network size. --bridge-network-range must be /16 or larger network.

If you are seeing that error and it is persistent, please open a new bug and we can address your issues in that.  Thanks!

**Comment by andrewtchin** [comment]
@madmaxT800 If you're seeing either `bridge mask is not compatible with bridge pool mask` or `Specified bridge network range is not large enough for the default bridge network size` the workaround is to run `vic-machine create` with `--bridge-network-range` as a /16 or larger network

**Pull request merged**
