### PR TITLE
Remove debug logger in VicUIServiceImpl.java

### PR DESCRIPTION
**Pull request by jooskim**
The debug logger is logging information that is unnecessary (yet sensitive) for operation of the plugin. This PR removes that.

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
Not sure why Github's diff shows the whole file, even though the only changes seem to be on lines 145-148.

LGTM

**Comment by jooskim** [comment]
@anchal-agrawal I replaced CRLFs with LFs and that's why :) Don't know why it started off with CRLFs.

**Comment by jooskim** [comment]
Taking @asudhak 's approval as LGTM.

**Comment by jooskim** [comment]
♻️

**Pull request merged**
