### PR TITLE
[imagec] set --insecure-skip-verify flag

### PR DESCRIPTION
**Pull request by caglar10ur**

### CODE REVIEW

**Comment by mdubya66** [comment]
if i followed this correctly this was a regression. is there a test for this to prevent that from happening?

**Comment by caglar10ur** [comment]
nope, we don't have one now. We can bring a registry on vic but the issue is lack of push like we discussed last week. Will work with @mhagen-vmware to figure out a way

**Comment by fdawg4l** [comment]
LGTM

**Comment by jzt** [comment]
lgtm

**Comment by cgtexmex** [comment]
LGTM

**Pull request merged**
