### PR TITLE
Fix 'Equivalent path already exists: /containers/{handle}'

### PR DESCRIPTION
**Pull request by caglar10ur**
```
       "/containers/{id}": {
and
        "/containers/{handle}": {
```

are the same endpoint and validators not happy about it.

Reindent the file while at it...

### CODE REVIEW

**Comment by hickeng** [comment]
LGTM - worth noting that I've not really reviewed this as the indentation makes it excruciating and I don't have diff -w to hand. Rather, if the integration passed for this, then it's not regressed.

**Comment by caglar10ur** [comment]
@hickeng there 2 commits here to ease the pain. The first one has the real change (https://github.com/vmware/vic/pull/2523/commits/ac5f421ab52aaf256beb4a020fc4044a83e64ae5) the other is purely indentation change :)

**Comment by hickeng** [comment]
@caglar10ur I took a long time over it, being exceptionally diligent. My LGTM stands ;)

**Comment by anchal-agrawal** [comment]
:shipit:

**Comment by caglar10ur** [comment]
@hmahmood if I remember correctly you objected that. What do you want? Should I drop this?

**Comment by hmahmood** [comment]
I think drop it for now, and open an issue.

**Pull request closed without merging**
