### PR TITLE
VIC does not support host IP in port bindings, but allow 0.0.0.0

### LINKED ISSUE #2104: Create container fails when using VIC as a Docker endpoint with Jenkins
Using VIC 0.5.0. Trying out Jenkins with Docker Plug-in (https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin).

When Jenkins tries to create the container for my build, I am seeing failures with the following error in the logs:

Provisioned agent Image of evarga/jenkins-slave failed to launch
com.github.dockerjava.api.BadRequestException: Container.validateCreateConfig: invalid config

This error message is from here: https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/container.go#L1373

I will update with Docker API HTTP request/response logs once I capture them for triage.

### PR DESCRIPTION
**Pull request by travisfinch**
Fixes #2104

Although VIC does not support specifying the host IP to be using when doing port bindings, allow 0.0.0.0 to be specified since this is the default behavior anyway.

When using Jenkins with Docker Plug-in (https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin), Jenkins will send a container create API call with the following JSON for HostConfig:

```
   "HostConfig":{
      "Binds":null,
      "Links":null,
      "LxcConf":null,
      "LogConfig":null,
      "PortBindings":{
         "22/tcp":[
            {
               "HostIp":"0.0.0.0",
               "HostPort":""
            }
         ]
      },
```

Without this patch, provisioning the build slave fails with the following error message even though it is a valid configuration that should work with VIC:

`host IP is not supported for port bindings`

With this patch, everything works as expected. Here is an example build output from a dynamically provisioned Jenkins slave container running on VIC:

```
Building remotely on VIC-33a7e3b8f890 (docker-slave) in workspace /home/jenkins/workspace/vic-test
[vic-test] $ /bin/sh -xe /tmp/hudson4730172276331220303.sh
+ printenv
<output truncated>
JENKINS_HOME=/Users/Shared/Jenkins/Home
SSH_CLIENT=172.16.0.1 65089 22
JENKINS_CLOUD_ID=VIC
USER=jenkins
<output truncated>
DOCKER_HOST=tcp://10.115.68.105:2375
<output truncated>
SSH_CONNECTION=172.16.0.1 65089 172.16.0.2 22
DOCKER_CONTAINER_ID=33a7e3b8f8900e31d9541f54ef94953f39d22263f25e11037df7f1003dee6c28
Finished: SUCCESS
```

### CODE REVIEW

**Comment by jzt** [comment]
LGTM

**Comment by dougm** [comment]
lgtm

**Comment by mdubya66** [comment]
ping

**Comment by mdubya66** [comment]
lgtm

**Comment by gigawhitlocks** [comment]
lgtm

**Comment by emlin** [comment]
♻️

**Pull request closed without merging**
