### PR TITLE
Quick fix for harcoded network

### LINKED ISSUE #2377: Create VCH - custom image store directory
network is hardcoded, switch it to using the env variable so it will work cleaner with VC testing

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Fixes #2377

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by andrewtchin** [comment]
lgtm

**Comment by andrewtchin** [comment]
oops!

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
