### PR TITLE
[skip ci] Add markdown files for docker rename tests

### PR DESCRIPTION
**Pull request by anchal-agrawal**
Follow-up of #4377

### CODE REVIEW

**Comment by chengwang86** [comment]
I'm still not quite clear why we need to list all the docker cmds we use in the markdown file, e.g., `issue docker run -dit ...`. Although I totally understand that these are `steps`, it does not help explain why we are taking these steps. 

Actually I prefer the styles used in 11-01 where we only list the high level goals and methods for the test while leaving the details to the robot file.

These are just my comments. I don't require any changes.

**Comment by chengwang86** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
@chengwang86 I concur with your point. We've been using this pattern extensively so far - see `1-04-Docker-Create.md` for example. I'll let @mhagen-vmware and @rajanashok make the call on whether we should move to your suggested approach.

**Comment by rajanashok** [comment]
lgtm

**Pull request merged**
