### PR TITLE
Re-enable stop with specific grace period test [full ci]

### LINKED ISSUE #1924: Failure in CI test Stop a container with specific grace period
This test has now failed 3 times in a row with 3 different errors:
3846: 125 != 0
[integration_logs_3846_936a10a4e99665dd7521fe7fbd8d6482296e0621_1470925723.zip](https://github.com/vmware/vic/files/413758/integration_logs_3846_936a10a4e99665dd7521fe7fbd8d6482296e0621_1470925723.zip)

3856: 1 != 0
[integration_logs_3856_cb88305b25486548b7829c822926f4c61b63f808_1470934272.zip](https://github.com/vmware/vic/files/413760/integration_logs_3856_cb88305b25486548b7829c822926f4c61b63f808_1470934272.zip)

3860: '' does not contain 'StopSignalHUP'
[integration_logs_3860_ef590de88f0aaa0a03e439e214e3b8476e87c63a_1470935256.zip](https://github.com/vmware/vic/files/413784/integration_logs_3860_ef590de88f0aaa0a03e439e214e3b8476e87c63a_1470935256.zip)

I am going to quarantine this test now, until this issue is resolved.

### PR DESCRIPTION
**Pull request by dougm**
Fixes #1924

### CODE REVIEW

**Comment by jzt** [comment]
👍 LGTM 👍

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
@dougm Just switching from docker run to docker create/start? Can we have a test that uses run still? Is there something about run that prevents stop from working correctly?

**Comment by dougm** [comment]
There's no issue with using 'run' in this test, but I switched to 'start' so its clearer in the test logs if we continue to have the start issues (cde/vmxnet3).  We have 1-6-Docker-Run.robot to cover the 'run' command.

**Pull request merged**
