### PR TITLE
Don't overwrite TERM if supplied by user

### LINKED ISSUE #1618: Don't overwrite TERM if user supplies it from the cli
We are currently overwriting `TERM` to be `xterm` when a container is created with the `-t` flag, even if `-e "TERM=<some other value>"` is used.

The user-supplied TERM value should take precedence over any other.

**Expected behavior:**
```
$ docker run -it -e "TERM=screen" busybox /bin/sh
/ # echo $TERM
screen
```

**Actual behavior:**
```
$ docker -H 192.168.218.235:2376 --tls run -it -e "TERM=screen" busybox /bin/sh
/ # echo $TERM
xterm
```

### PR DESCRIPTION
**Pull request by jzt**
Fixes #1618

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by fdawg4l** [comment]
LGTM

**Comment by hmahmood** [comment]
lgtm

**Comment by jzt** [comment]
♻️

**Pull request merged**
