### PR TITLE
Redundant multi-writer and test

### PR DESCRIPTION
**Pull request by hickeng**
TestAbsPath failed to return output in the Go1.6.2 PR test. Looking at the
output it was apparent that there was a redundant chaining of
multi-writers. It's not clear whether this caused the problem or not, but
this removes the unnecessary chain and adds a scale repetition of the unit
test.

### CODE REVIEW

**Comment by hickeng** [comment]
*facepalm* seems I've rolled up @caglar10ur's 1.6.2 change as well.

**Comment by caglar10ur** [comment]
LGTM, by the way this commit includes my old commit [which will cause test to fail] :)

**Comment by caglar10ur** [comment]
@hickeng can you rebase this on master and push again?

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by caglar10ur** [comment]
Hmm looks like we still have some issues with the test as it panics after 10 min

**Comment by hickeng** [comment]
@caglar10ur yup - it's the repetition test. It cycles 1000 times but seems to hang with a channel full issue. Why it's not doing so locally is my current puzzle.

**Comment by hickeng** [comment]
@fdawg4l I think we still have an issue around flushing but it's not something I can spend time on at the moment. This fix at least addresses the incorrect aspects of the test that sometimes finds the problem.
I've skipped the test that occasionally hits the flushing issue and opened #577

**Pull request merged**
