### PR TITLE
Change URL of default registry in whitelist test

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Addressing #5902 . Not sure why this changed, but this is the requested fix.

### CODE REVIEW

**Comment by sgairo** [comment]
does this need CI?

**Comment by mdharamadas1** [comment]
@sgairo I would run specific ci for this.

**Comment by gigawhitlocks** [comment]
@mdharamadas1 it's a nightly, so this test doesn't run in CI. I'll copy and paste a successful run into the PR once I have one for the sake of posterity and paper trail :)

**Comment by mdharamadas1** [comment]
@gigawhitlocks ah yes!! I didn't realize that its nightly.

**Comment by gigawhitlocks** [comment]
Going to just go ahead and take care of #5904 while I'm at it

**Comment by gigawhitlocks** [comment]
This is the first test passing, though, the fix for #5902 anyway:
```
==============================================================================
21-1-Whitelist :: Test 21-01 - Whitelist                                      
==============================================================================

Deploying Nimbus ESXi server: ESX-53530.469192

Disable TLS on the host
Successfully deployed new ESXi server - iwhitlock-ESX-53530.469192

Fetching harbor ova...

Deploying ova...
Waiting for Harbor to Come Up...

Fetching harbor ova...

Deploying ova...
Waiting for Harbor to Come Up...
Basic Whitelisting                                                    
TEST_URL=10.161.85.4

Worker_Date=Wed Aug  9 21:47:33 UTC 2017

Test_Server_Date=
Current date and time:  Wed Aug  9 21:47:34 UTC 2017
NTP client status:      Enabled
NTP service status:     Running
NTP servers:            time.vmware.com


Installing VCH to test server...
Installer completed successfully: VCH-0-7452...
Gathering logs from the test server VCH-0-7452
Deleting the VCH appliance VCH-0-7452
| PASS |
------------------------------------------------------------------------------
```

**Comment by sgairo** [comment]
Good thinking !

**Comment by gigawhitlocks** [comment]
```
==============================================================================
21-1-Whitelist :: Test 21-01 - Whitelist                                      
==============================================================================

Deploying Nimbus ESXi server: ESX-77050.466092

Disable TLS on the host
Successfully deployed new ESXi server - iwhitlock-ESX-77050.466092

Fetching harbor ova...

Deploying ova...
Waiting for Harbor to Come Up...

Fetching harbor ova...

Deploying ova...
Waiting for Harbor to Come Up...
Basic Whitelisting                                                    
TEST_URL=10.192.41.194

Worker_Date=Thu Aug 10 20:26:35 UTC 2017

Test_Server_Date=
Current date and time:  Thu Aug 10 20:26:36 UTC 2017
NTP client status:      Enabled
NTP service status:     Running
NTP servers:            time.vmware.com


Installing VCH to test server...
Installer completed successfully: VCH-0-9429...
Gathering logs from the test server VCH-0-9429
Deleting the VCH appliance VCH-0-9429
| PASS |
------------------------------------------------------------------------------
Check Login to Insecure Registry (http)                               
TEST_URL=10.192.41.194

Worker_Date=Thu Aug 10 20:29:09 UTC 2017

Test_Server_Date=
Current date and time:  Thu Aug 10 20:29:10 UTC 2017
NTP client status:      Enabled
NTP service status:     Running
NTP servers:            time.vmware.com


Installing VCH to test server...
Installer completed successfully: VCH-0-7165...
Gathering logs from the test server VCH-0-7165
Deleting the VCH appliance VCH-0-7165

TEST_URL=10.192.41.194

Worker_Date=Thu Aug 10 20:31:12 UTC 2017

Test_Server_Date=
Current date and time:  Thu Aug 10 20:31:12 UTC 2017
NTP client status:      Enabled
NTP service status:     Running
NTP servers:            time.vmware.com


Installing VCH to test server...
Installer completed successfully: VCH-0-2944...
Gathering logs from the test server VCH-0-2944
Deleting the VCH appliance VCH-0-2944
| PASS |
------------------------------------------------------------------------------
Configure Registry CA                                                 
TEST_URL=10.192.41.194

Worker_Date=Thu Aug 10 20:33:37 UTC 2017

Test_Server_Date=
Current date and time:  Thu Aug 10 20:33:38 UTC 2017
NTP client status:      Enabled
NTP service status:     Running
NTP servers:            time.vmware.com


Installing VCH to test server...
Installer completed successfully: VCH-0-5653...
Gathering logs from the test server VCH-0-5653
Deleting the VCH appliance VCH-0-5653
| PASS |
------------------------------------------------------------------------------
21-1-Whitelist :: Test 21-01 - Whitelist                              | PASS |
3 critical tests, 3 passed, 0 failed
3 tests total, 3 passed, 0 failed
==============================================================================
Output:  /tmp/output.xml
Log:     /tmp/log.html
Report:  /tmp/report.html
~/go/src/github.com/vmware/vic
Test reports are in /tmp/vic-test-output-2017-08-10T1452-0500
```

**Pull request merged**
