### PR TITLE
[skip ci] Remove only the specific test vms on nightly teardown

### PR DESCRIPTION
**Pull request by rajanashok**
The teardown only deletes the VMs specific to the test. This is needed to support running multiple nightly runs on the same test account so we can run both 6.0 and 6.5 ESX versions.

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
nice job!

**Comment by rajanashok** [comment]
.

**Pull request merged**
