### PR TITLE
Avoid waiting on guestinfo if vm powered off

### PR DESCRIPTION
**Pull request by dougm**
If the tether fails to initialize, for example when no ethernet card is
found, the container VM will power off.  With this change we stop
waiting on guestinfo keys in such an event.

Issue #2327

### CODE REVIEW

**Comment by jzt** [comment]
LGTM

**Comment by jzt** [comment]
This PR also fixes #2372. 👍

**Comment by hmahmood** [comment]
LGTM

**Comment by dougm** [comment]
:recycle:

**Pull request merged**
