### PR TITLE
Echo out directories & files during coverage step

### LINKED ISSUE #2329: Unit test CI build failure in pkg test
see https://ci.vmware.run/vmware/vic/4784
# github.com/vmware/vic/vendor/github.com/vmware/govmomi/object

vendor/github.com/vmware/govmomi/object/host_service_system.go:25: can't find import: "github.com/vmware/vic/vendor/github.com/vmware/govmomi/vim25/types"
Makefile:227: recipe for target 'test-job-github.com/vmware/vic/pkg' failed
make: **\* [test-job-github.com/vmware/vic/pkg] Error 2
make: **\* Waiting for unfinished jobs....

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Adding more logging so that we can close #2329 

This is an incredibly intermittent bug that appears during coverage checks. I have been unable to reproduce it despite trying many approaches.

It's my hypothesis that this is a bug that exists in the `go` compiler's coverage tool and surfaces from time to time.

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by gigawhitlocks** [comment]
♻️

**Comment by gigawhitlocks** [comment]
LGTM

**Comment by gigawhitlocks** [comment]
LGTM

**Pull request merged**
