### PR TITLE
Fix: stop container started out of band

### LINKED ISSUE #1398: Unable to stop container powered on by UI
```
vagrant@devbox:~/vic$ docker -H 192.168.78.245:2376 --tls start 646e745164a74834ab269a86fb6a6d3e28c95f99383940121863a5380445a064
646e745164a74834ab269a86fb6a6d3e28c95f99383940121863a5380445a064
vagrant@devbox:~/vic$ docker -H 192.168.78.245:2376 --tls ps
CONTAINER ID        IMAGE               COMMAND             CREATED                  STATUS              PORTS               NAMES
646e745164a7        busybox             "top"               Less than a second ago   Running                                 runk_easley
vagrant@devbox:~/vic$ docker -H 192.168.78.245:2376 --tls stop 646e745164a74834ab269a86fb6a6d3e28c95f99383940121863a5380445a064
646e745164a74834ab269a86fb6a6d3e28c95f99383940121863a5380445a064
vagrant@devbox:~/vic$ docker -H 192.168.78.245:2376 --tls ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
vagrant@devbox:~/vic$ docker -H 192.168.78.245:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED                  STATUS              PORTS               NAMES
646e745164a7        busybox             "top"               Less than a second ago   Stopped                                 runk_easley
vagrant@devbox:~/vic$ # POWER ON THE CONTAINER VIA VSPHERE UI
vagrant@devbox:~/vic$ docker -H 192.168.78.245:2376 --tls ps
CONTAINER ID        IMAGE               COMMAND             CREATED                  STATUS              PORTS               NAMES
646e745164a7        busybox             "top"               Less than a second ago   Running                                 runk_easley
vagrant@devbox:~/vic$ docker -H 192.168.78.245:2376 --tls stop 646e745164a74834ab269a86fb6a6d3e28c95f99383940121863a5380445a064
Error response from daemon: container 646e745164a74834ab269a86fb6a6d3e28c95f99383940121863a5380445a064 not found
Error: failed to stop containers: [646e745164a74834ab269a86fb6a6d3e28c95f99383940121863a5380445a064]
vagrant@devbox:~/vic$
```

### PR DESCRIPTION
**Pull request by hmahmood**
Fixes #1398

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by andrewtchin** [comment]
lgtm

**Comment by hmahmood** [comment]
♻️

**Comment by hmahmood** [comment]
♻️

**Pull request merged**
