### PR TITLE
Remove vmware.log from applianceVM (Vic Admin)

### LINKED ISSUE #2164: vic-admin: strip vmware.log
vmware.log for the appliance contains the extraconfig entries for the VM - this needs to be sanitized by vic-admin prior to bundling.

https://bugzilla.eng.vmware.com/show_bug.cgi?id=1727636

### PR DESCRIPTION
**Pull request by sgairo**
Fixes #2164

### CODE REVIEW

**Comment by sgairo** [comment]
@jzt @hickeng

**Comment by dougm** [comment]
Why not just remove vmware.log from the list? https://github.com/vmware/vic/blob/e08c84dbe6ecb7a925f7bb41be6ee37822d6a216/cmd/vicadmin/vicadm.go#L67

Maybe we can still include it if debug is enabled?  @hickeng ?  If not, can we change the robot helper to grab the log via govc datastore.download and add it to the log bundle.zip ?

**Comment by jzt** [comment]
@dougm That will also remove vmware.log from the containerVM bundles.

**Comment by dougm** [comment]
@jzt gotcha, disregard.

**Comment by hickeng** [comment]
I was stripping it in this WIP: https://github.com/vmware/vic/pull/2784 and there's a big TODO about not using name comparison because it sucks. The WIP includes the changes necessary for GetSelf so we could use that for much more reliable comparison.
@dougm +1 for logging it with higher debug levels enabled (debug > 2 IMO as it's a pretty serious behavioural change)

**Comment by jzt** [comment]
@hickeng It looks like your changes take care of this (minus the debug level check to allow for inclusion of the log). Should @sgairo close this PR and move on, or were you thinking something else?

**Pull request closed without merging**
