### PR TITLE
[skip ci] fixed tether error msg typo

### PR DESCRIPTION
**Pull request by kreamyx**
typo fix in tether error msg

### CODE REVIEW

**Comment by sgairo** [comment]
👍

**Comment by sgairo** [comment]
Also, just a quick change needed in the copyright range.

**Comment by caglar10ur** [comment]
@sgairo we should write a bot for that copyright check :)

**Comment by sgairo** [comment]
@caglar10ur good idea, that way PRs like this one dont get merged without the correct copyright in the future haha

**Pull request merged**
