### PR TITLE
Make volume store command line consistent w/ container-network

### LINKED ISSUE #1490: vic-machine: make the volume-store ordering consistent with container-network
The volume-store argument to vic-machine is currently inconsistent with container-network - it takes the internal name first, with the vsphere path second. This may have been done deliberately to simplify splitting around the first : however it should be consistent and we should be splitting on the last : in the value.
The logic for having vsphere name first is [here](https://github.com/vmware/vic/blob/master/doc/design/vic-machine.md#usage-examples)

When fixed:
```
--volume-store=datastore1/path/to/volumes:mydata
--volume-store=ds://datastore (1)/path/to/data:otherdata
```

Requires the follow before closing:
- [ ] implementation
- [ ] doc update

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Fixes #1490 in both implementation & help text & usage doc.

### CODE REVIEW

**Comment by matthewavery** [comment]
lgtm , barring comments from Stuart Clements

**Comment by gigawhitlocks** [comment]
@stuclem you probably need to :+1: this before I can merge it

**Comment by gigawhitlocks** [comment]
Whoops I LGTM'd myself, but I'll be a good citizen and wait for another one.

**Comment by gigawhitlocks** [comment]
Oh good and then I closed the PR by accident

**Comment by andrewtchin** [comment]
lgtm

**Comment by stuclem** [comment]
LGTM

**Pull request merged**
