### PR TITLE
Fix version.ShortVersion formatting

### PR DESCRIPTION
**Pull request by caglar10ur**
now shows
```
Server Version: v0.5.5-c775037
```
instead of
```
Server Version: v0.5.5--c775037
```
when the BuildNumber is omitted

### CODE REVIEW

**Comment by cgtexmex** [comment]
LGTM

**Comment by dougm** [comment]
Can we make build number '0' in that case?
```
v0.5.5-0-c775037
```

Just to have the same format in either case, should a script want to parse the version.  But if we don't care about that, then LGTM

**Comment by emlin** [comment]
> Can we make build number '0' in that case?
> 
> v0.5.5-0-c775037
> 
> Just to have the same format in either case, should a script want to parse the version. 

 +1 with it.
vic-machine upgrade will check version, and assume the same format.

**Comment by caglar10ur** [comment]
Sure thing, will update the PR with 0 as the placeholder

**Comment by emlin** [comment]
lgtm

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
