### PR TITLE
add vic-machine inspect

### LINKED ISSUE #1252: vic-machine inspect command
This command will accept same parameter with vic-machine delete, to query out existing VCH.
And then output the same information like vic-machine create successfully.

### PR DESCRIPTION
**Pull request by emlin**
Fixes #1252 #1287

This is the first step for this command, which will show the VCH information similar to user got after installation. So user could get the changed VCH ip address easily.

No more diagnostic information provided yet.

### CODE REVIEW

**Comment by emlin** [comment]
For VM is powered off:
```
INFO[2016-06-29T16:19:27-05:00] ### Inspecting VCH ####                      
INFO[2016-06-29T16:19:30-05:00]                                              
INFO[2016-06-29T16:19:30-05:00] VCH: *********
ERRO[2016-06-29T16:19:31-05:00] VCH is not powered on, state poweredOff      
INFO[2016-06-29T16:19:31-05:00] Collecting ha-host hostd.log                 
ERRO[2016-06-29T16:19:31-05:00] vic-machine-linux failed, VCH is not powered on, state poweredOff 
```

**Comment by emlin** [comment]
For VM is powered on, but ip is not set yet:
```
INFO[2016-06-29T16:21:31-05:00] ### Inspecting VCH ####                      
INFO[2016-06-29T16:21:35-05:00]                                              
INFO[2016-06-29T16:21:35-05:00] VCH: ********* 
ERRO[2016-06-29T16:21:35-05:00] Didn't have client IP address assigned       
INFO[2016-06-29T16:21:35-05:00] Collecting ha-host hostd.log                 
ERRO[2016-06-29T16:21:35-05:00] vic-machine-linux failed, Didn't have client IP address assigned 
```

**Comment by emlin** [comment]
For running VCH:
```
INFO[2016-06-29T16:03:17-05:00] ### Inspecting VCH ####
INFO[2016-06-29T16:03:20-05:00]
INFO[2016-06-29T16:03:20-05:00] VCH: <resource pool path>/<vch-name>
INFO[2016-06-29T16:03:21-05:00]
INFO[2016-06-29T16:03:21-05:00] SSH to appliance (default=root:password)
INFO[2016-06-29T16:03:21-05:00] ssh root@x.x.x.x
INFO[2016-06-29T16:03:21-05:00]
INFO[2016-06-29T16:03:21-05:00] Log server:
INFO[2016-06-29T16:03:21-05:00] https://x.x.x.x:2378
INFO[2016-06-29T16:03:21-05:00]
INFO[2016-06-29T16:03:21-05:00] DOCKER_HOST=x.x.x.x:2376
INFO[2016-06-29T16:03:21-05:00] DOCKER_OPTS="-H x.x.x.x:2376"
INFO[2016-06-29T16:03:21-05:00]
INFO[2016-06-29T16:03:21-05:00] Connect to docker:
INFO[2016-06-29T16:03:21-05:00] docker -H x.x.x.x:2376 info
INFO[2016-06-29T16:03:21-05:00] Completed successfully
```

**Comment by mdubya66** [comment]
Didn't have a client IP address assigned to Does not have a client IP address assigned.

Didn't we determine that DOCKER_OPTS is ignored? @hickeng?

Did we drop the --tls requirement?

**Comment by caglar10ur** [comment]
@mdubya66 what do you mean? (referring dropping --tls requirement part) Are we dropping tls support or making it default and adding --no-tls to disable it?

**Comment by mdubya66** [comment]
The example above doesn't have --tls.

INFO[2016-06-29T16:03:21-05:00] docker -H x.x.x.x:2376 info
INFO[2016-06-29T16:03:21-05:00] Completed successfully

**Comment by emlin** [comment]
> The example above doesn't have --tls.

@mdubya66 Just understand what do you mean. This should be a bug, not dropping tls support.

**Comment by emlin** [comment]
Updated sample output after code change.

**Comment by mdubya66** [comment]
what about DOCKER_OPTS? @hickeng mentioned it's ignored. see #1207.

**Comment by emlin** [comment]
Currently, vic-machine inspect is showing everything same to vic-machine create. So the DOCKER_OPTS is same to before.
After this PR is merged, can start to work on #1207.

**Comment by andrewtchin** [comment]
lgtm

**Comment by gigawhitlocks** [comment]
LGTM
Looks like you need a rebase though, might want to wait until my change goes in, I think there'll be rebase conflicts if I rebase against this change but I don't think you'll have conflicts if you rebase my change in (because `Dispatch` was moved and renamed)

**Comment by gigawhitlocks** [comment]
LGTM

**Comment by emlin** [comment]
refresh

**Comment by emlin** [comment]
Killed code refresh build. Here is the green one: https://ci.vmware.run/vmware/vic/2441

**Pull request merged**
