### PR TITLE
Strip network mask from IP if it is used as cname.

### LINKED ISSUE #3410: Strip network mask from IP address for cert check.
At the moment if --tls-cname is not specified vic-machine automatically takes clientNetworkIP/publicNetworkIP/managementNetworkIP as a value for cname. Unfortunately, it also means that it will automatically include a network mask that is not a part of a host name.
If user run this command second time with pre-generated certificates, it is going to fail since ip/mask is not equal IP.

### PR DESCRIPTION
**Pull request by vburenin**
Fixes #3410

### CODE REVIEW

**Comment by hickeng** [comment]
There's no point in adding this code - at the moment the mask portion is ignored on the `--xxx-network-ip` options so simply not providing the /xx component of the value is an equivalent fix.

This should be delivered with an update that stops requiring the mask on the gateway argument and instead pulls it from the address argument.

**Comment by vburenin** [comment]
@hickeng If mask is not supplied with IP address, how do we determine a subnet?

**Comment by mdubya66** [comment]
Given the comments is this PR still relevant?

**Comment by mlh78750** [comment]
agree with https://github.com/vmware/vic/pull/3411#issuecomment-263973505 We should not use /XX on the gateway and instead have it on the ip option.

**Comment by vburenin** [comment]
Fixed in #3519

**Pull request closed without merging**
