### PR TITLE
[it] Test --link/--net-alias subcommands

### PR DESCRIPTION
**Pull request by caglar10ur**

### CODE REVIEW

**Comment by caglar10ur** [comment]
Reopening this as I mistakenly removed the branch in github...

**Comment by caglar10ur** [comment]
```
[DRONE] starting job #1
[info] Pulling image vmware-docker-ci-repo.bintray.io/integration/vic-test:1.1
$ pybot tests/test-cases/Group1-Docker-Commands/1-24-Docker-Link.robot
==============================================================================
1-24-Docker-Link :: Test 1-24 - Docker Link
==============================================================================

Installing VCH to test server...
:q
gInstaller completed successfully: VCH-0-5353...
Link and alias                                                        | PASS |
------------------------------------------------------------------------------
1-24-Docker-Link :: Test 1-24 - Docker Link                           | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /drone/src/github.com/vmware/vic/output.xml
Log:     /drone/src/github.com/vmware/vic/log.html
Report:  /drone/src/github.com/vmware/vic/report.html
[DRONE] finished job #1
[DRONE] exit code 0
[DRONE] job #1 passed
[DRONE] build passed
```

**Comment by mdubya66** [comment]
lgtm

**Comment by fdawg4l** [comment]
lgtm

**Pull request merged**
