### PR TITLE
Update to pull from Photon 1.0 GA

### PR DESCRIPTION
**Pull request by kjplatz**
This addresses issue #1041

### CODE REVIEW

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by hmahmood** [comment]
lgtm

**Comment by kjplatz** [comment]
Note that this introduces issue #1005 into an ESX environment.  The same fix for issue #1005 will address that issue here as well.

**Comment by andrewtchin** [comment]
Note the above comment means that we will not be able to start containers until #1005 is merged.

**Comment by caglar10ur** [comment]
@kjplatz @andrewtchin I'm not sure I understood what #1005 is about. Are you sure you have the correct network settings with a DHCP server on those ESX and/or VC setups?

**Comment by sflxn** [comment]
LGTM

**Comment by mdubya66** [comment]
@hickeng : Can you follow up on this and let's get it resolved. We should get onto Photon OS 1.0 ASAP for some soak time.

**Comment by hickeng** [comment]
@frapposelli @casualjim How do we prompt a CI build to occur having vetted the change from someone not in maintainers?

**Comment by hickeng** [comment]
@kjplatz @mhagen-vmware This failure looks like an issue with aufs and possibly --trusted mode:
https://github.com/docker/docker/issues/6980
https://major.io/2014/03/26/docker-trusted-builds-and-fedora-20/

**Comment by matthewavery** [comment]
Yes I spent some time sitting down with @kjplatz and it appeared that aufs was causing problems with unpacking archives with cpio. Atleast at first glance it looks like there is a failure unpacking the iputils photon rpm archive. However @kjplatz was getting this when attempting to build in a golang-1.6.2 docker container.

**Comment by mdubya66** [comment]
lgtm to enable merge, maybe

**Comment by kjplatz** [comment]
It appears that containers still spin interminably while waiting for an IP (see #1005) after applying this PR.

**Comment by hickeng** [comment]
@kjplatz what was the solution to the iputils issue? has the drone config been changed?

**Pull request closed without merging**
