### PR TITLE
[skip ci] Added new supported docker commands to the table.

### PR DESCRIPTION
**Pull request by npakrasi**
[skip ci] Updated table with more commands that are implemented.

### CODE REVIEW

**Comment by npakrasi** [comment]
LGTM. Will reorder in alphabetical order next.

**Comment by stuclem** [comment]
LGTM!

**Comment by npakrasi** [comment]
.

**Comment by npakrasi** [comment]
:recycle:

**Comment by npakrasi** [comment]
♻️

**Pull request merged**
