### PR TITLE
Handle container vm stop/power off race

### PR DESCRIPTION
**Pull request by dougm**
In container stop() it is possible for the container vm to have reached
powered off state in between graceful shutdown and hard power off.
Ignore the PowerOff_Task error in this case.

### CODE REVIEW

**Comment by dougm** [comment]
Looks like the cause of this test failure: https://ci.vmware.run/vmware/vic/3842

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
Are we elsewhere checking first before we attempt the power off in the first place? If not, it would be nice to do that to avoid forcing vsphere constantly down error paths.

**Comment by dougm** [comment]
@mhagen-vmware this is the only place we stop/power off a container vm.  We do the following here:

* send stop signal to the container process (SIGTERM by default)

* wait for vm power state == off or timeout (10 second timeout by default)

* if power state is not off, send SIGKILL to the container process

* wait for vm power state == off or timeout (10 second timeout by default)

* if power state is still not off, PowerOff the container vm

Normally we'd be done after the first SIGTERM + a short wait for power state off and not hit the remaining steps.  The test that failed intentionally forces us to the SIGKILL step.  Combined with a shorter timeout (2sec) and a busy system, it is possible the vm power state won't be set to "off" until after we've entered the call to PowerOff().

**Comment by cgtexmex** [comment]
LGTM

**Pull request merged**
