### PR TITLE
[skip ci] Fixing the log url for the nightly email

### PR DESCRIPTION
**Pull request by rajanashok**
The log link needs an additional query string for it to resolve the file in google cloud.
Also, updating the test status to PASS/FAIL instead of Passed/Failed.

### CODE REVIEW

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by sgairo** [comment]
lgtm

**Comment by mdubya66** [comment]
Approved for merge

**Comment by rajanashok** [comment]
.

**Pull request merged**
