### PR TITLE
Use ComputeResource as search root in vic-machine ls

### LINKED ISSUE #4482: vCenter: vic-machine ls not working as expected
Related to #4203 /cc @dougm 

**VIC version:**

1.1.0-rc2 / ee1c09a

**Deployment details:**

Single-cluster vCenter 6.5.0 b4602587 with 3 ESX 6.5.0 b4564106 hosts deployed with https://github.com/vmware/vic/blob/master/tests/resources/Nimbus-Util.robot#L140

**Steps to reproduce:**

```
$ bin/vic-machine-linux create --name=vch-1 --target=<VC> --thumbprint=<> --user=<> --password=<> --image-store=datastore1 --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --compute-resource=cls1 --bridge-network=bridge --public-network=vm-network  --volume-store=datastore1/test:default --no-tlsverify  --force=true

# No compute-resource specified - works
$ bin/vic-machine-linux ls --target=10.160.103.156 --user=<> --password=<> --thumbprint=<>
Mar 30 2017 16:46:47.974-05:00 INFO  ### Listing VCHs ####
Mar 30 2017 16:46:49.119-05:00 INFO  Validating target

ID            PATH                                    NAME              VERSION                     UPGRADE STATUS
vm-305        /datacenter1/host/cls1/Resources        VCH-0-8634        v1.1.0-rc2-9284-ee1c09a     Up to date

# Cluster specified in compute-resource - doesn't work
$ bin/vic-machine-linux ls --target=<> --user=<> --password=<> --thumbprint=<> --compute-resource=cls1
Mar 30 2017 16:45:54.135-05:00 INFO  ### Listing VCHs ####
Mar 30 2017 16:45:55.294-05:00 INFO  Validating target
Mar 30 2017 16:45:55.294-05:00 INFO  Validating compute resource

ID        PATH        NAME        VERSION        UPGRADE STATUS

# Absolute path specified in compute-resource - doesn't work
anchala@ubuntu:~/go/src/github.com/vmware/vic$ bin/vic-machine-linux ls --target=<> --user=<> --password=<> --thumbprint=<> --compute-resource=/datacenter1/host/cls1/Resources
Mar 30 2017 16:46:59.842-05:00 INFO  ### Listing VCHs ####
Mar 30 2017 16:47:00.982-05:00 INFO  Validating target
Mar 30 2017 16:47:00.982-05:00 INFO  Validating compute resource

ID        PATH        NAME        VERSION        UPGRADE STATUS
```

**Additional details:**
Test https://github.com/vmware/vic/blob/master/tests/test-cases/Group6-VIC-Machine/6-10-List.robot also fails on this setup

### PR DESCRIPTION
**Pull request by dougm**
Using the ResourcePool as search root here does not work on VC,
due to VirtualApp being the immediate child.

Fixes #4482

### CODE REVIEW

**Comment by mdubya66** [comment]
@mhagen please review for inclusion in the next RC.

**Comment by MHagen** [comment]
Not sure why, but I'm getting these emails when I'm not part of this project.

________________________________

**Comment by mdubya66** [comment]
fixed, apologies to the original mhagen

**Comment by mhagen-vmware** [comment]
lgtm

**Pull request merged**
