### PR TITLE
Move problematic tests to a folder

### PR DESCRIPTION
**Pull request by DanielXiao**
Move below scenario tests to need-to-fix folder to
skip them. Tests in this folder are problematic
and should be fixed.
5-7-NSX: Testbed '10.160.21.102' is not accessible.
5-27-Selenium-Grid: The network configuration is
incorrect.

### CODE REVIEW

**Comment by renmaosheng** [comment]
please file two issue to track those two tests.

**Comment by DanielXiao** [comment]
https://github.com/vmware/vic/issues/8235
https://github.com/vmware/vic/issues/8236

**Comment by zjs** [comment]
Can we update the "Possible Problems" of each of the markdown files to add a note referencing the relevant issue? This will help someone looking at the code or running the tests manually quickly understand the known issues with the tests.

---

Can we add a placeholder test to the top-level directory that checks the status of the issues that were filed? Something like `vic/tests/manual-test-cases/5-27-Selenium-Grid-disabled.robot` that has something like:

```robot
    ${status}=  Get State Of Github Issue  8235
    Run Keyword If  '${status}' == 'closed'  Fail  Test 5-7-NSX.robot needs to be moved out of "need-to-fix" folder now that Issue #8235 has been resolved
    Log  Test skipped; see issue \#8235  WARN
```

This will help tie the tests to the GitHub issue, and would be more consistent with the way we disable other tests.

**Comment by DanielXiao** [comment]
OK. I will disable these 2 tests like other tests

**Comment by zjs** [comment]
Is this needed for the 1.4.3 release branch as well?

**Pull request merged**
