### PR TITLE
Gather the ESX logs from the environment

### LINKED ISSUE #1861: Need to gather host ESX logs in the CI environment
Life cycle team is debugging some of the errors we are seeing in the CI environment, but they need additional logs in order to be more successful.

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Fixes #1861

### CODE REVIEW

**Comment by mdubya66** [comment]
@mhagen-vmware  says this adds 2min 23sec per gathering to the build <sigh>
Maybe do it only on failure, eventually. 

LGTM

**Comment by dougm** [comment]
The support bundle includes more than just logs and does indeed take a long time to generate.  Do we need more than just hostd.log?

lgtm

**Comment by mhagen-vmware** [comment]
Derek said they really need the additional logs as well unfortunately.

**Comment by mhagen-vmware** [comment]
.

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
