### PR TITLE
Added vic-machine create, double dash options and updated option names.

### PR DESCRIPTION
**Pull request by stuclem**
[ci skip] 
This PR looks a bit better than https://github.com/vmware/vic/pull/1019.

Fixes https://github.com/vmware/vic/issues/948.

Updated docs to reflect changes to vic-machine made by @emlin in PR https://github.com/vmware/vic/issues/995 and issue https://github.com/vmware/vic/issues/945.

- Added `create `to `vic-machine` commands to deploy a VCH
- Changed single dash to double dash for all options
- Renamed `image-store`, `container-store`, and `passwd` to `image-datastore`, `container-datastore`, and `password`.

Links to affected files:
- [Deploy a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/install_vic_cli.md) 
- [Virtual Container Host Deployment Options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md) 
- [Examples of Deploying a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md) 
- [Verify the Deployment of a Virtual Container Host to an ESXi Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/verify_vch_deployment_esx.md) 
- [Verify the Deployment of a Virtual Container Host to vCenter Server](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/verify_vch_deployment.md) 

Also removed product version number from all publications, since 0.3 isn't out yet.

Added a topic on manually [removing a VCH](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/remove_vch.md).

### CODE REVIEW

**Comment by andrewtchin** [comment]
@stuclem to skip ci the commit message should have [skip ci] in it like:
```git commit -m "[skip ci] Added vic-machine create, double dash options and updated option names."```

**Comment by stuclem** [comment]
Thanks @andrewtchin, that's what I thought too, but in my PR https://github.com/vmware/vic/pull/955  @dougm said "Please don't put 'skip ci' in the git commit messages. Just put it in the github PR comment form."

**Comment by dougm** [comment]
Right, please don't put that in the git commit messages.  CI isn't started until you submit the PR, so using the comment box at the point is the time to add it.

Stu, you had it backwards this time "ci skip", instead of "skip ci", so ci still ran.

**Comment by dougm** [comment]
Also regarding the commit message: https://github.com/vmware/vic/blob/master/CONTRIBUTING.md#format-of-the-commit-message

**Comment by stuclem** [comment]
Hi @dougm, according to https://github.com/vmware/vic/blob/master/CONTRIBUTING.md#automated-testing both ci skip and skip ci should work. 

Regarding the commit message, is this something that I can change retroactively?

**Comment by dougm** [comment]
Sorry missed that, and never actually used skip myself.  That is surprising and crummy.  If skip only works in the commit message, let's put it in the body, rather than the subject at least.

You can use 'git commit -a' to amend a commit and/or change the commit message.

**Comment by andrewtchin** [comment]
lgtm

**Comment by dougm** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks!

**Pull request merged**
