### PR TITLE
Initial testing notes/walkthrough for setting up kubernetes

### LINKED ISSUE #3785: Research spike: Investigate testing kubernetes support in VIC
As a quality engineer on VIC, I would like to have a simple getting started kubernetes document as it pertains to VIC, so that I can get up to speed quickly and begin writing tests and executing tests.

Acceptance criteria:
1. How to kubernetes document

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Fixes #3785

### CODE REVIEW

**Comment by matthewavery** [comment]
lgtm

**Comment by rajanashok** [comment]
Looks good!

**Comment by hickeng** [comment]
@mhagen-vmware not sure this goes under doc/design - is this the basis for something else? if it's just deployment steps for a k8 reference deployment then putting it in the repo may not be the right place.

**Comment by mhagen-vmware** [comment]
@hickeng It is the basis for our future k8s testing plans.  I would like to have this as a public document, so that we can easily reference it as well as other people, as I had to draw this for several different sources and experimentation.

**Pull request merged**
