### PR TITLE
These tests won't apparently work until we implement containerwait

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Just have to comment out for now.

### CODE REVIEW

**Comment by mdubya66** [comment]
We have to get our testing going the opposite direction, enabling tests. @hickeng @corrieb : container wait is not planned for 1.0. See #384. We need to find a way to get this working.

giving a, begrudging, LGTM

**Comment by mdubya66** [comment]
LGTM

**Comment by andrewtchin** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
.

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
