### PR TITLE
Revert "Remove resource pool limitation"

### PR DESCRIPTION
**Pull request by andrewtchin**
This was a breaking change - reverting while we fix
This reverts commit 81aae035218a7e56e945c6cc2df7c0cd13a9dbda.

### CODE REVIEW

**Comment by matthewavery** [comment]
lgtm

**Comment by hickeng** [comment]
LGTM
@emlin @mhagen-vmware if this passed testing, how did that occur?

**Comment by emlin** [comment]
> @emlin @mhagen-vmware if this passed testing, how did that occur?

This is because the problem only happens in VC, and we don't test VC in any integration test yet.

**Comment by andrewtchin** [comment]
♻️

**Comment by emlin** [comment]
Fixes #1285

**Pull request merged**
