### PR TITLE
Feature/stress tests

### LINKED ISSUE #1847: Execute Stress Test Plan
As a customer of VIC, I want to be assured that VIC has been put through an exhaustive set of stress tests so that I can be assured that it works under extreme conditions and fails gracefully.

Depends on #1846

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Initial implementation of the stress tests, and some cleanup on some keywords that didn't work on VC quite right.

Fixes #1847

### CODE REVIEW

**Comment by rajanashok** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
.

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by matthewavery** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
.

**Comment by rajanashok** [comment]
lgtm

**Pull request merged**
