### PR TITLE
[skip ci] Moving the hardcoded ESX & VC version to the yaml file

### PR DESCRIPTION
**Pull request by rajanashok**
This will let us pass the version to the Nimbus-Util to support running both 6.0, 6.5 ESXs.

### CODE REVIEW

**Comment by mhagen-vmware** [comment]
We can do it this way, but I thought you would just do in the shell script:
pybot --variable ESX_VERSION:132143 --variable VC_VERSION:32413454 tests/manual....
etc.

**Comment by mhagen-vmware** [comment]
either way is fine by me, the nightly kickoff would just then be using this PR method:
ESX_VERSION=12312 VC_VERSION=22345432  pybot tests/manual
anyways

**Comment by mhagen-vmware** [comment]
LGTM

**Comment by rajanashok** [comment]
Yes, I did not know about the "pybot --variable ESX_VERSION:132143". Will go with this option, this should save us from creating a another secrets file for 6.0.

**Comment by rajanashok** [comment]
Closing this PR. We could just do "pybot --variable ESX_VERSION:132143"

**Pull request closed without merging**
