### PR TITLE
Add unzip package to the image for Ian

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Add the unzip package for something @gigawhitlocks needs.

### CODE REVIEW

**Comment by mhagen-vmware** [comment]
He will update the references to the new 1.5 image in a separate PR.

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by matthewavery** [comment]
LGTM

**Comment by gigawhitlocks** [comment]
NOBODY ELSE IS ALLOWED TO USE **MY** UNZIP PACKAGE

**Comment by gigawhitlocks** [comment]
Also LGTM

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
