### PR TITLE
Allow for logs to not show up for a little bit

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Fix for longevity issue, we have tech debt that needs to be addressed at some point but the logs won't necessarily be available instantly after working on a container.

### CODE REVIEW

**Comment by fdawg4l** [comment]
LGTM

**Comment by mdubya66** [comment]
lgtm

**Comment by hmahmood** [comment]
I think we should leave this test alone for now. I want to see if @caglar10ur recent fixes also fix this. See my comment in https://github.com/vmware/vic/issues/2872

**Comment by hickeng** [comment]
@hmahmood the log files are created by vsphere as soon as the VM powers on - nothing @caglar10ur does will influence their presence, only their content.

@mhagen-vmware don't close #2872 as we don't know what's actually happening- can we add in the usual github issue open check - in this case for the repeated check of the logs. That means we won't close #2872 forgetting why we're not seeing it occur any more.

**Comment by mdubya66** [comment]
Do it

**Comment by mhagen-vmware** [comment]
.

**Comment by hmahmood** [comment]
@hickeng are you sure they are created on power on, and not on first write to the serial port?

**Pull request merged**
