### PR TITLE
Switch back to the original URLs

### PR DESCRIPTION
**Pull request by mhagen-vmware**
We went back to the original URLs so need to re-encode the .sec files again.

### CODE REVIEW

**Comment by emlin** [comment]
Just to confirm, where did you switch back the URLs? Cause in this PR, you only changed the sec file.

**Comment by mhagen-vmware** [comment]
When you encode the .sec files, you need to specify the URLs.  It doesn't show up in any file change, just in the procedure to encode the file.

**Comment by emlin** [comment]
LGTM

**Comment by andrewtchin** [comment]
lgtm

**Pull request merged**
