### PR TITLE
Correct the vicadmin and personality nonTLS path

### LINKED ISSUE #1161: vic-machine doesn't work in the non-certificates mode anymore
bin/vic-machine-linux create --name=VCH-4 --target=192.168.254.128 --user=root --image-datastore=datastore1 --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --generate-cert=false --password=vmware1 --force=true --bridge-network=network --compute-resource=/ha-datacenter/host/localhost.localdomain/Resources
INFO[2016-06-21T11:16:50-05:00] ### Installing VCH ####                      
WARN[2016-06-21T11:16:50-05:00] Configuring without TLS - to enable use -generate-cert or -key/-cert parameters 
INFO[2016-06-21T11:16:50-05:00] Validating supplied configuration            
ERRO[2016-06-21T11:16:50-05:00] crypto/tls: failed to find any PEM data in certificate input 
ERRO[2016-06-21T11:16:50-05:00] Creation cannot continue: configuration validaton failed 
vic-machine-linux failed:  validation of configuration failed

### PR DESCRIPTION
**Pull request by hickeng**
This fixes the non-TLS path for docker personality and vicadmin. It makes it explicit that if a certificate was specified but cannot be loaded that the fall back to non-TLS isn't acceptable.

This also neatens some of the vic-machine output around TLS arguments and displays DOCKER_OPTS as an alternative to the full command line

Fixes #1161

### CODE REVIEW

**Comment by emlin** [comment]
LGTM

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by dougm** [comment]
lgtm

**Comment by hickeng** [comment]
Forcing check update

**Pull request merged**
