### PR TITLE
Grab the logs before deleting the appliance

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Just in case these tests fail before getting to the delete section, lets grab the logs.

### CODE REVIEW

**Comment by matthewavery** [comment]
lgtm

**Comment by fdawg4l** [comment]
lgtm

**Comment by stuclem** [comment]
@mhagen-vmware is this just for your tests or is this a feature of vic-machine delete? Thanks!

**Comment by mhagen-vmware** [comment]
@stuclem This is just for our tests.

**Comment by stuclem** [comment]
OK, thanks @mhagen-vmware

**Pull request merged**
