### PR TITLE
Use unsigned 16-bit int to enable full TCP port range

### PR DESCRIPTION
**Pull request by travisfinch**
This change allows containers to map ports from 0 to 65535, instead of to just 32767.

Previously, the command below would return "bad port spec 50000/tcp"

```
$ docker -H 10.115.68.105:2375 run -d -p 8080:8080 -p 50000:50000 aus-dc-test.eng.vmware.com/jenkins-interop/jenkins
bef7c5015dc00e386384b9b091230d0248faf7e715548870dc3e6eba8f3c2b57
```

### CODE REVIEW

**Comment by hmahmood** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
:shipit:

**Comment by caglar10ur** [comment]
@travisfinch can you update your branch?

**Comment by caglar10ur** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
Merging on behalf of @travisfinch.

**Pull request merged**
