### PR TITLE
Allow extraconfig updates for running VM

### PR DESCRIPTION
**Pull request by hickeng**
This allows extraconfig updates for a running VM, filtering the keys to
those that are explicitly noted as non-persistent or are not guestinfo.

Also adds some make targets to the set of those that don't have dependency
memoization run so as to improve build time in CI.

Towards #4110

### CODE REVIEW

**Comment by sgairo** [comment]
Do these copyright headers need to have the 2016-2017 range?

**Comment by cgtexmex** [comment]
agree with @sgairo that copyright should be updated, but other than that LGTM

**Comment by fdawg4l** [comment]
I don't understand the makefile change. Are the clean targets no longer cleaning up everything?

**Comment by fdawg4l** [comment]
Is the change to extra config simply an optimization or did something functional change?

**Comment by hickeng** [comment]
@fdawg4l The Makefile change is purely an optimization. In CI we call `make mark` and `make sincemark` at every build step. Each of those invocations would build the dynamic dependency graphs for the Go targets - this causes the dependency generation to be skipped for those targets.

**Pull request merged**
