### PR TITLE
Correct formatting issue

### PR DESCRIPTION
**Pull request by hickeng**
Correct formatting in vic-machine output.

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by caglar10ur** [comment]
I think we are also having another 

```
INFO[2016-06-23T00:03:04Z] Connect to docker:
INFO[2016-06-23T00:03:04Z] docker -H 10.143.2.172:2376  --tlsinfo
INFO[2016-06-23T00:03:04Z] Installer completed successfully
```

**Comment by caglar10ur** [comment]
♻️

**Comment by hickeng** [comment]
force check update

**Pull request merged**
