### PR TITLE
Add short name for common vic-machine arguments

### PR DESCRIPTION
**Pull request by emlin**
Also add trace to vic-machine functions, and update usage document for vic-machine delete command.
Reference #828

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM (it's minor but I think we should pass meaningful strings to trace package when possible instead of just saying "")

**Comment by emlin** [comment]
ah, make sense. Didn't know that.
It will be useful to have parameter printed out.

**Comment by emlin** [comment]
refresh

**Pull request merged**
