### PR TITLE
Remove metabase upload

### PR DESCRIPTION
**Pull request by mhagen-vmware**
This hasn't worked in months, and just continues to fail. When we move our CI to a new environment we will be using loginsight anyways, so no need to continue to carry this code.

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
Does this change disable uploading `log.html` to vic-logs.vcna.io or uploading to metabase (the failure visualization tool)? vic-logs.vcna.io been working fine recently afaik.

**Comment by mhagen-vmware** [comment]
I don't know what vic-logs.vcna.io is doing, but this has not worked in months:
```
Saving integration test results to /drone-test-results/testruns-db/vic-master.db
19812s
5881
Traceback (most recent call last):
19840s
5882
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
19840s
5883
    "__main__", fname, loader, pkg_name)
19840s
5884
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
19840s
5885
    exec code in run_globals
19840s
5886
  File "/usr/local/lib/python2.7/dist-packages/dbbot/run.py", line 51, in <module>
19840s
5887
    DbBot().run()
19840s
5888
  File "/usr/local/lib/python2.7/dist-packages/dbbot/run.py", line 41, in run
19840s
5889
    self._parser.xml_to_db(xml_file)
19840s
5890
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 51, in xml_to_db
19840s
5891
    self._parse_suite(test_run.suite, test_run_id)
19840s
5892
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 117, in _parse_suite
19840s
5893
    self._parse_suites(suite, test_run_id, suite_id)
19840s
5894
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 132, in _parse_suites
19840s
5895
    [self._parse_suite(subsuite, test_run_id, parent_suite_id) for subsuite in suite.suites]
19840s
5896
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 117, in _parse_suite
19840s
5897
    self._parse_suites(suite, test_run_id, suite_id)
19840s
5898
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 132, in _parse_suites
19840s
5899
    [self._parse_suite(subsuite, test_run_id, parent_suite_id) for subsuite in suite.suites]
19840s
5900
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 118, in _parse_suite
19840s
5901
    self._parse_tests(suite.tests, test_run_id, suite_id)
19840s
5902
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 135, in _parse_tests
19840s
5903
    [self._parse_test(test, test_run_id, suite_id) for test in tests]
19840s
5904
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 154, in _parse_test
19840s
5905
    self._parse_keywords(test.keywords, test_run_id, None, test_id)
19840s
5906
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 172, in _parse_keywords
19840s
5907
    for keyword in keywords]
19840s
5908
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 190, in _parse_keyword
19840s
5909
    self._parse_keyword_status(test_run_id, keyword_id, keyword)
19840s
5910
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/robot_results_parser.py", line 200, in _parse_keyword_status
19840s
5911
    'elapsed': keyword.elapsedtime
19840s
5912
  File "/usr/local/lib/python2.7/dist-packages/dbbot/reader/database_writer.py", line 196, in insert_or_ignore
19840s
5913
    self._connection.execute(sql_statement, criteria.values())
19840s
5914
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by anchal-agrawal** [comment]
Yep, I've seen that error but I don't think it affects uploading `log.html` to vic-logs.vcna.io. It probably affects some other file/feature. We can currently go to vic-logs.vcna.io/$buildNumber and view `log.html` directly instead of downloading the log bundle first. With this change, we don't upload `log.html` to vic-logs.vcna.io - https://vic-logs.vcna.io/15725 gives a 404.

Do we still want to do this? Being able to look at `log.html` directly is convenient.

**Comment by mhagen-vmware** [comment]
no problem, wasn't aware people used that. update, now it only removes the metabase business

**Pull request merged**
