### PR TITLE
Fixes segfault instead of go panic

### LINKED ISSUE #1197: go panics, coredumps and systemd. Chose one.
Currently we do not get go panic listings on things such as nil pointer (seen in port-layer storage parent map change #1191). Instead a core is being produced, captured by systemd and added into the journal.
`coredumpctl` can be used to access some information about the core but we're not getting a backtrace, possibly because gdb is unavailable. We should find a way to switch this back to go thread dump, but we should also add this information to vicadmin log collection data, along with the entire journal:
```
root@docker-appliance [ /var/lib/systemd/coredump ]# coredumpctl
TIME                            PID   UID   GID SIG PRESENT EXE
Fri 2016-06-24 14:05:41 UTC     168     0     0  11 * /usr/sbin/port-layer-server
Fri 2016-06-24 14:19:15 UTC     195     0     0  11 * /usr/sbin/port-layer-server
root@docker-appliance [ /var/lib/systemd/coredump ]# coredumpctl info
           PID: 168 (port-layer-serv)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Fri 2016-06-24 14:05:38 UTC (17min ago)
  Command Line: /sbin/port-layer-server --host=localhost --port=8080 --insecure --sdk=https://root:ca$hc0w@192.168.78.128/sdk --datacenter=ha-datacenter --cluster=/ha-datacenter/host/localhost.localdomain --pool=/ha-datacenter/host/local
host.localdomain/Resources --datastore=datastore1 --network=/ha-datacenter/network/VM Network --vch=docker-appliance
    Executable: /usr/sbin/port-layer-server
 Control Group: /system.slice/launcher.service
          Unit: launcher.service
         Slice: system.slice
       Boot ID: d8fd3f32d75d427a8bc329b948003a02
    Machine ID: 7451e7523aff433d8b62f8f48bc472c8
      Hostname: docker-appliance
      Coredump: /var/lib/systemd/coredump/core.port-layer-serv.0.d8fd3f32d75d427a8bc329b948003a02.168.1466777138000000.xz
       Message: Process 168 (port-layer-serv) of user 0 dumped core.

           PID: 195 (port-layer-serv)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Fri 2016-06-24 14:19:12 UTC (4min 4s ago)
  Command Line: /sbin/port-layer-server --host=localhost --port=8080 --insecure --sdk=https://root:ca$hc0w@192.168.78.128/sdk --datacenter=ha-datacenter --cluster=/ha-datacenter/host/localhost.localdomain --pool=/ha-datacenter/host/local
host.localdomain/Resources --datastore=datastore1 --network=/ha-datacenter/network/VM Network --vch=docker-appliance
    Executable: /usr/sbin/port-layer-server
 Control Group: /system.slice/system-sshd.slice/sshd@0-192.168.78.181:22-192.168.78.1:50380.service
          Unit: sshd@0-192.168.78.181:22-192.168.78.1:50380.service
         Slice: system-sshd.slice
       Boot ID: d8fd3f32d75d427a8bc329b948003a02
    Machine ID: 7451e7523aff433d8b62f8f48bc472c8
      Hostname: docker-appliance
      Coredump: /var/lib/systemd/coredump/core.port-layer-serv.0.d8fd3f32d75d427a8bc329b948003a02.195.1466777952000000.xz
       Message: Process 195 (port-layer-serv) of user 0 dumped core.
root@docker-appliance [ /var/lib/systemd/coredump ]#
```

### PR DESCRIPTION
**Pull request by kjplatz**
Invoking bdoor.HypervisorPortCheck() squashes the default golang SIGSEGV handler; after invoking this function, any SEGV will abort with a core dump instead of invoking a go panic.  This PR changes the behaviour to save and restore the signal handler. 

Fixes #1197

### CODE REVIEW

**Comment by dougm** [comment]
Fix looks good Ken.  But rather than modify vendor/ directly, you need to submit the change upstream to the repo at: https://github.com/sigma/bdoor

**Comment by kjplatz** [comment]
@dougm I have also submitted a PR upstream here: https://github.com/sigma/bdoor/pull/1

**Comment by mdubya66** [comment]
Hi Ken, we should cancel this PR then. We don't change vendor code.

**Comment by dougm** [comment]
@kjplatz great, once upstream has the fixed merged, you can update vic's vendor version using:
```
gvt fetch github.com/sigma/bdoor
```

And re-open this PR with that change.

**Comment by hickeng** [comment]
@dougm @mdubya66 I was the one who asked @kjplatz to do it this way - I'd rather have stack traces in the TP3 code. Do we know the person behind sigma/bdoor to get this pushed through quickly, because we'll also need vmware/vmw-guestinfo to update their vendor before we see benefit as it's a transitive dependency.

**Comment by caglar10ur** [comment]
They are both in (pinged Yann over slack) you can update vendor now

**Comment by hickeng** [comment]
@caglar10ur Thanks! @kjplatz ok - just the vendor update to the updated vmw-guestinfo for this PR.

**Pull request closed without merging**
