### PR TITLE
Populate image cache correctly. Starting from parents to children.

### LINKED ISSUE #2546: image cache is not correctly populated after VCH restart
before restart
```
docker -H 10.17.109.87:2376 --tls images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nginx               latest              f7df00cd0f62        9 days ago          181.3 MB
```
after restart
```
docker -H 10.17.109.87:2376 --tls images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
```

### PR DESCRIPTION
**Pull request by vburenin**
Populate image cache according to images hierarchy. 
Fixes #2546

### CODE REVIEW

**Comment by emlin** [comment]
Well this is good. Please also change the VCH restart integration test, so we can catch any regression in the future.
Here is the test folder: https://github.com/vmware/vic/tree/master/tests/test-cases/Group10-VCH-Restart

**Comment by vburenin** [comment]
I am writing unit test for this right now.

**Comment by jzt** [comment]
LGTM, pending tests. 👍

**Comment by emlin** [comment]
lgtm. 
Would be nice to squash unnecessary commits during your push.

**Comment by fdawg4l** [comment]
Guys, checking things into the storage layer without me looking at it isn't ok.  Please check with me before merging changes like this in the future.

**Pull request merged**
