### PR TITLE
[skip ci] Document the design for the vic-machine API

### LINKED ISSUE #6014: Write a public design document for the VCH management API
Document a design for the VCH management API, including the rationale for any design decisions.

### PR DESCRIPTION
**Pull request by zjs**
This document proposes a design for a comprehensive `vic-machine` API, the implementation of which will be tracked by #6116.

Subsets of this API (tracked by #5721, #6123, and eventually others) will be implemented incrementally, and the design will be revised as those efforts progress to reflect changes to the long-term vision.

Implementation status will be captured in GitHub, not this document.

Resolves #6014

### CODE REVIEW

**Comment by mdubya66** [comment]
can we get this one wrapped up? @zjs

**Comment by zjs** [comment]
> can we get this one wrapped up?

I'd love to; I just need reviews.

**Comment by mdubya66** [comment]
@ali5ter @jak-atx @hickeng please review ASAP. @zjs remove @jooskim from the review list

**Comment by zjs** [comment]
This isn't actually merged... I'm not sure why GitHub thinks it is.

**Pull request merged**
