### PR TITLE
Avoid attempt to create image config if image already exists

### LINKED ISSUE #970: Pulling an existing image causes imagec to panic
imagec:

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xf1de40, 0xc82000c080)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.CreateImageConfig(0xc82022e0a0, 0x0, 0x2, 0xc8204839a0, 0x0, 0x0)
    /opt/go/src/github.com/vmware/vic/cmd/imagec/imagec.go:387 +0xeda
main.main()
    /opt/go/src/github.com/vmware/vic/cmd/imagec/imagec.go:597 +0x1483
```

**VIC Version:**

master

**Expected behavior:**
```
Using default tag: latest
latest: Pulling from library/busybox
385e281300cc: Already exists
a3ed95caeb02: Already exists
Status: Image is up to date for library/busybox:latest
```
**Actual behavior:**
```
Using default tag: latest
latest: Pulling from library/busybox
385e281300cc: Already exists
a3ed95caeb02: Already exists
invalid character 'p' looking for beginning of value
```

### PR DESCRIPTION
**Pull request by jzt**
Fixes #970

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by andrewtchin** [comment]
A+ would lgtm again

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by caglar10ur** [comment]
needs rebase

**Comment by jzt** [comment]
Testing if I can lgtm myself to refresh after rebase.

**Pull request merged**
