### PR TITLE
Just big sleep to allow VM to shut off and hopefully avoid intermitte…

### PR DESCRIPTION
**Pull request by mhagen-vmware**
We believe that there is a race between docker stop and docker rm. Because we have not implemented containerWait yet, our docker rm implementation immediately tries to rm a vm that might still be powered on.

### CODE REVIEW

**Comment by mdubya66** [comment]
@hickeng : this requires your review before merge.

**Comment by mdubya66** [comment]
potential workaround for #1822 and #1823

**Comment by hickeng** [comment]
Firstly that's a VERY long timeout. I'm not sure how many minutes that'll add to the integration tests but it'll be a lot.
Secondly I don't think it'll actually work - I believe there are two problems: #1870 and another one in the containerVM itself, possibly #1837). The latter is hard to confirm as we need the container logs which is currently blocked by #1836)

**Comment by mhagen-vmware** [comment]
1. It will add 30 sec to each PR run
2. It will add 2 minutes to a merge to master run

I don't like the big sleep either, but it doesn't add that much to our development process and unless all those issues are getting fixed today, I really don't want to sit through another day of CI failures. I think this is a relatively easy and limited potential fix that has little cost and either improves things or costs us a small amount of time.  And it is really easy to remove once we have the other fixes in place.  @hickeng

**Comment by mhagen-vmware** [comment]
@hickeng How about this: https://github.com/vmware/vic/pull/1869/commits/77d68ae036bef6775d95d5a807f41aae36a3c543

Poll govc?

**Comment by mdubya66** [comment]
@hickeng @mhagen-vmware where are we with this?

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Pull request closed without merging**
