### PR TITLE
Fixing handling of arbitrary sized slice

### PR DESCRIPTION
**Pull request by hmahmood**
This is a bug I ran into while working on VCH restart. Its part of my larger; I am splitting it out here to make that PR smaller.

### CODE REVIEW

**Comment by hmahmood** [comment]
@caglar10ur

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by hmahmood** [comment]
♻️

**Pull request merged**
