### PR TITLE
Move to keyword so that we can use the regression test as a quick val…

### PR DESCRIPTION
**Pull request by mhagen-vmware**

### CODE REVIEW

**Comment by emlin** [comment]
Well, just curious, can't we make the test case one keyword, in just it's original place?

**Comment by emlin** [comment]
LGTM to the code

**Comment by mhagen-vmware** [comment]
1. Then any test that wants to use it would need to pull in the regression robot file as a resource.
2. You can't have a test cases table in a resource.

**Comment by andrewtchin** [comment]
lgtm

**Pull request merged**
