### PR TITLE
Allow volume stores which already exist to be added

### PR DESCRIPTION
**Pull request by fdawg4l**
This is a fix for a regression.  We should be able to add volume stores with existing volumes.

### CODE REVIEW

**Comment by mdubya66** [comment]
Do we need a regression test? Is there no bug filed for the regression it is fixing?

**Comment by fdawg4l** [comment]
@mdubya66 there is no regression test yet.  We also don't support VCH restart because of an open issue.  We can't test this without supporting VCH restart.

On the plus side, there are unit tests which tickle this.  That's how I found it.  I'll talk to @mhagen-vmware about getting CI to run them since they require a VM with access to the esx box its on.

**Comment by hmahmood** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by fdawg4l** [comment]
.

**Pull request merged**
