### PR TITLE
Add UT for cmd/rpctool

### LINKED ISSUE #361: Add no test classes into UT coverage report
Investigate how to show all testable classes in unit test coverage, instead of only the classes with test files.
So far, for some classes, go cannot find test files, so the file is not listed in coverage, for example, https://github.com/vmware/vic/blob/master/tether/cmd/proxy/tether.go
To make the coverage report more real.

### PR DESCRIPTION
**Pull request by emlin**
Fixes #361

### CODE REVIEW

**Comment by caglar10ur** [comment]
Hmm this literally runs the rpctool so I not sure whether we should be moving this into integration test or keep it here. Any opinions anyone?

**Comment by emlin** [comment]
I think this is for unit test, and integration test will focus on end-2-end functions. So I add this test.
But it might be a little bit duplicate with integration test. So I'm open for it.

**Comment by andrewtchin** [comment]
I agree this looks like an end to end test being run with the unit test framework. We need a way to mark files that aren't unit testable.

**Comment by emlin** [comment]
That's fine. If we don't add unit test for it, there is no unit test coverage calculated for that.
Then I'll close this pull request and wait future's integration test.

**Pull request closed without merging**
