### PR TITLE
Create friendly name in appropriate docker format

### LINKED ISSUE #1368: docker ps data issues
docker ps output:
```
vagrant@devbox:~/vic$ docker -H 192.168.78.245:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
da3dc0f41403        busybox             "sh"                11 weeks ago        Stopped                                 leepy_lalande
91e80e811118        busybox             "sh"                11 weeks ago        Stopped                                 ovial_rosalind
4335f5876269        busybox             "sh"                11 weeks ago        Stopped                                 onely_feynman
aeb59497ca6b        busybox             "top"               11 weeks ago        Stopped                                 istracted_visvesvaraya
6302afde43f9        busybox             "top"               11 weeks ago        Stopped                                 wesome_mcnulty
d7db62e90542        busybox             "top"               11 weeks ago        Stopped                                 ad_northcutt
20e5a5524467        busybox             "/bin/ash"          11 weeks ago        Stopped                                 etermined_austin
```

There are two major issues with this:
1. 11 weeks ago - I think this is likely the image creation time, not the container creation time.
2. the name is missing it's first character meaning it's not usable without guesswork

### PR DESCRIPTION
**Pull request by cgtexmex**
The friendly name of the container should be prefixed with a forward
slash "/".  This change addresses that need and will allow the
friendly name to render correctly during `docker ps`

Partially Fixes #1368

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by hickeng** [comment]
LGTM

**Comment by cgtexmex** [comment]
rebase

**Pull request merged**
