### PR TITLE
Purge prior component launch status during upgrade

### LINKED ISSUE #2624: Upgrade does not wait for components to start
**Expected behavior:**
After upgrading vic-machine blocks until the appliance has successfully launched, and rolls back if that doesn't happen in a reasonable time frame.

**Actual behavior:**
vic-machine doesn't block until the component have launched or validate function.

** Diagnosis**
This is a combination of two things:
* adding client authentication means that unless a client cert is supplied it's not always possible to access the DOCKER_API endpoint to confirm function. This resulted in the endpoint check moving out of the standard startAppliance path and into the callers that need it.
* session.started is persisted across reboots, so we don't block waiting for that either as they would be marked as successful from the previous initialization.

We have possible parts of solutions :
1. allow the host certificate to be used for client verification - that means we *always* have a cert available that can be used for the client auth if we have access to the config. This requires not masking the host private key from the API however.
2. make `session.started` non-persistent, and/or clear it on the shutdown path. Doing this would mean we need to split into `status` and `state` so that we can persist `status` which could contain errors such as `no such file` vs state which is contingent on the VM running.

### PR DESCRIPTION
**Pull request by hickeng**
If the Started status is not purged then we don't block or correctly report component
status in the case of failure.
This PR re-enables the blocking on component launch.
We should not purge IP address so we can maintain a stable address if DHCP so we
will not block on that.

In combination with #2703 which blocks waiting for API response:
Fixes #2624

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

**Comment by hmahmood** [comment]
lgtm

**Comment by hickeng** [comment]
poke

**Pull request merged**
