### PR TITLE
Sort chidren files before delete them recursively

### LINKED ISSUE #1649: imageMetadata/metaData was not found when removing VIC using VSAN datastore
**VIC Version:**

0.1 / master / 3190

I was able to successfully deploy VIC using a vsanDatastore.
However on removal, I got the  errors shown below.
On checking the datastore afterwards, the VIC folder persists but is completely empty.

```
root@photon-NaTv5i8IA [ /workspace/vic ]# ./vic-machine-linux delete -t 10.27.51.103 -u 'administrator@vsphere.local' -p 'VMware123!' --compute-resource Mgmt
INFO[2016-07-25T10:58:50Z] ### Removing VCH ####
INFO[2016-07-25T10:58:50Z] Removing VMs
INFO[2016-07-25T10:58:55Z] Removing images
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687/imageMetadata/metaData was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687/imageMetadata/metaData}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687/imageMetadata/metaData was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687/imageMetadata was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687/imageMetadata}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687/imageMetadata was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629/imageMetadata/metaData was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629/imageMetadata/metaData}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629/imageMetadata/metaData was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/b05baf071fd542c3146f08e5f20ad63e76fa4b4bd91f274c4838ddc41f3409f8/imageMetadata/metaData was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/b05baf071fd542c3146f08e5f20ad63e76fa4b4bd91f274c4838ddc41f3409f8/imageMetadata/metaData}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/b05baf071fd542c3146f08e5f20ad63e76fa4b4bd91f274c4838ddc41f3409f8/imageMetadata/metaData was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629/imageMetadata was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629/imageMetadata}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629/imageMetadata was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d/imageMetadata/metaData was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d/imageMetadata/metaData}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d/imageMetadata/metaData was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d/imageMetadata was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d/imageMetadata}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d/imageMetadata was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7/imageMetadata/metaData was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7/imageMetadata/metaData}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7/imageMetadata/metaData was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd/imageMetadata was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd/imageMetadata}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd/imageMetadata was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7/imageMetadata was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7/imageMetadata}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7/imageMetadata was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/6685b215489379f00c1b399db75a4e4aa6546e4f2a3519145c14a2c7d5612be7/imageMetadata was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/6685b215489379f00c1b399db75a4e4aa6546e4f2a3519145c14a2c7d5612be7/imageMetadata}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/6685b215489379f00c1b399db75a4e4aa6546e4f2a3519145c14a2c7d5612be7/imageMetadata was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/scratch/imageMetadata was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/scratch/imageMetadata}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/scratch/imageMetadata was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976/imageMetadata/metaData was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976/imageMetadata/metaData}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976/imageMetadata/metaData was not found})
ERRO[2016-07-25T10:58:56Z] Operation failed: File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976/imageMetadata was not found - (&{{} %!!(MISSING)s(*types.FileNotFound=&{{{{<nil> []}} [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976/imageMetadata}}) File [vsanDatastore] VIC/4206659e-8ee5-383b-9d70-5c5f4a17eb03/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976/imageMetadata was not found})
INFO[2016-07-25T10:58:57Z] Removing appliance VM network devices
INFO[2016-07-25T10:58:58Z] Removing VCH vSphere extension
INFO[2016-07-25T10:59:04Z] Removing Resource Pool "virtual-container-host"
INFO[2016-07-25T10:59:04Z] Completed successfully
root@photon-NaTv5i8IA [ /workspace/vic ]#
```

**Expected behavior:**
That the removal operation completes without errors.

**Actual behavior:**
As above.

### PR DESCRIPTION
**Pull request by emlin**
Fixes #1649 

  On vSan, sometimes we have to delete files before folder, otherwise delete failed.
  But vsphere query children method doesn't guarantee orders, even if I specify the sort parameter. So the solution is to sort result after query. then delete will be happen and no operation error reported because files are already deleted by folder deletion.

### CODE REVIEW

**Comment by hmahmood** [comment]
Why can't we just delete the children of a folder first (recursively) before deleting the folder?

**Comment by emlin** [comment]
> Why can't we just delete the children of a folder first (recursively) before deleting the folder?

Datastore browser has two kinds of query. One is to query out all direct children, another is to query out all children in that folder.
And there is no efficient way to detect if the file type, directory or file.
Recursively query direct children is not efficient, so my solution is to query out all children. 

Originally I thought that interface is sorted, as there is sort parameter, but actually sorting parameter does not work, so this PR is to add manually sort after query.

**Comment by hmahmood** [comment]
Well looking at the current code, we first get a list of all file recursively, then we go through that list to append paths, then we sort, and then we go over the list to delete. That does not sound very efficient. 

To check if a FileInfo object is a file or folder, can't we just type assert if it is a [FolderFileInfo](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.host.DatastoreBrowser.FolderInfo.html) object?

**Comment by emlin** [comment]
I checked the files returned by govmomi, only FileInfo object returned, no matter it's file or folder.
And a major issue for the result is that, it will return same directory info multiple times. So the children for multiple dirs are actually mixed returned.
For example, following gonna be a result
```
dir1/a
dir1/b 
dir2/a
dir2/b
dir1/a/meta
dir1/a/image
```
So that's the only way to have all paths appended to array, and then sort it globally.

**Comment by hmahmood** [comment]
Are you setting fileType to true here: https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.host.DatastoreBrowser.FileInfo.Details.html

**Comment by emlin** [comment]
Yes

**Comment by emlin** [comment]
Here is one real output still kept in my dev env, in case you're interested.
```
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/f905badeb5584b0128449fc7cdbae428ba1d767dd71b2912aa388f66c9beab27/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/94d6eea646bcb0a705c2b343eff1459e2de800ad95fb1f5d2536603d87d5b9a3/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/b05baf071fd542c3146f08e5f20ad63e76fa4b4bd91f274c4838ddc41f3409f8/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/119df6bf2a3a69b832a4e06fc3ccd63ec125612163a29c65f0a3f1538678d4a2/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/20ee5880928952d357ff01332b0497f01d4b6eb04f401008f3d93103c819c919/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/968c69f186734255a864498d3e55e0babe7f0c1fd443a81d32303022e1058ab2/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/3035387b9e834c466cd957662b14b5548c7b2bed1fc8057a2e80793bddd04d92/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/bb4eabee84bf75165ff4d9b2a68868c24e96174bf7ced05f8c0289a0004f23bd/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/94d6eea646bcb0a705c2b343eff1459e2de800ad95fb1f5d2536603d87d5b9a3/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/94d6eea646bcb0a705c2b343eff1459e2de800ad95fb1f5d2536603d87d5b9a3/94d6eea646bcb0a705c2b343eff1459e2de800ad95fb1f5d2536603d87d5b9a3.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7.vmdk
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/f905badeb5584b0128449fc7cdbae428ba1d767dd71b2912aa388f66c9beab27/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/f905badeb5584b0128449fc7cdbae428ba1d767dd71b2912aa388f66c9beab27/f905badeb5584b0128449fc7cdbae428ba1d767dd71b2912aa388f66c9beab27.vmdk
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/3035387b9e834c466cd957662b14b5548c7b2bed1fc8057a2e80793bddd04d92/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/3035387b9e834c466cd957662b14b5548c7b2bed1fc8057a2e80793bddd04d92/3035387b9e834c466cd957662b14b5548c7b2bed1fc8057a2e80793bddd04d92.vmdk
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/bb4eabee84bf75165ff4d9b2a68868c24e96174bf7ced05f8c0289a0004f23bd/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/bb4eabee84bf75165ff4d9b2a68868c24e96174bf7ced05f8c0289a0004f23bd/bb4eabee84bf75165ff4d9b2a68868c24e96174bf7ced05f8c0289a0004f23bd.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d.vmdk
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/scratch/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/scratch/scratch.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/6685b215489379f00c1b399db75a4e4aa6546e4f2a3519145c14a2c7d5612be7/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/6685b215489379f00c1b399db75a4e4aa6546e4f2a3519145c14a2c7d5612be7/6685b215489379f00c1b399db75a4e4aa6546e4f2a3519145c14a2c7d5612be7.vmdk
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/scratch
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/20ee5880928952d357ff01332b0497f01d4b6eb04f401008f3d93103c819c919
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/119df6bf2a3a69b832a4e06fc3ccd63ec125612163a29c65f0a3f1538678d4a2
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/bb4eabee84bf75165ff4d9b2a68868c24e96174bf7ced05f8c0289a0004f23bd
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/b05baf071fd542c3146f08e5f20ad63e76fa4b4bd91f274c4838ddc41f3409f8
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/94d6eea646bcb0a705c2b343eff1459e2de800ad95fb1f5d2536603d87d5b9a3
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/f905badeb5584b0128449fc7cdbae428ba1d767dd71b2912aa388f66c9beab27
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/20ee5880928952d357ff01332b0497f01d4b6eb04f401008f3d93103c819c919/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/20ee5880928952d357ff01332b0497f01d4b6eb04f401008f3d93103c819c919/20ee5880928952d357ff01332b0497f01d4b6eb04f401008f3d93103c819c919.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/968c69f186734255a864498d3e55e0babe7f0c1fd443a81d32303022e1058ab2/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/968c69f186734255a864498d3e55e0babe7f0c1fd443a81d32303022e1058ab2/968c69f186734255a864498d3e55e0babe7f0c1fd443a81d32303022e1058ab2.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/parentMap
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/parentMap
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629.vmdk
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/119df6bf2a3a69b832a4e06fc3ccd63ec125612163a29c65f0a3f1538678d4a2/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/119df6bf2a3a69b832a4e06fc3ccd63ec125612163a29c65f0a3f1538678d4a2/119df6bf2a3a69b832a4e06fc3ccd63ec125612163a29c65f0a3f1538678d4a2.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/6685b215489379f00c1b399db75a4e4aa6546e4f2a3519145c14a2c7d5612be7/imageMetadata/metaData
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976.vmdk
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/b05baf071fd542c3146f08e5f20ad63e76fa4b4bd91f274c4838ddc41f3409f8/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2/images/b05baf071fd542c3146f08e5f20ad63e76fa4b4bd91f274c4838ddc41f3409f8/b05baf071fd542c3146f08e5f20ad63e76fa4b4bd91f274c4838ddc41f3409f8.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/f3b2532b03016417772325817c7c7b6e44fe4396442ff88f49e9d17411a53976
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/scratch
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/755b4eb93a9e13712e221b01e0206dbdc31827b1dc6a6d2a51c13baeb51fb9c7
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/963493e54e682e698aee7ff1dc6ac9eb4234484bf58caccbebd4058619fd7d8d
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/f3bf4daa2ff24f73b6fc9acae1626ba9a23ab8c14af5fcbb06c2284773fd7629
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/a2295636c7aa7aeaaf8aba834ed7a9863a2a8f3e87464c8ab9bd659d4d668687
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/3035387b9e834c466cd957662b14b5548c7b2bed1fc8057a2e80793bddd04d92
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/6685b215489379f00c1b399db75a4e4aa6546e4f2a3519145c14a2c7d5612be7
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/968c69f186734255a864498d3e55e0babe7f0c1fd443a81d32303022e1058ab2
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/scratch/imageMetadata
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77/images/scratch/scratch.vmdk
	delete_test.go:339: [vsanDatastore] VIC/420663b3-205e-86d8-04de-3e706a6bfb77
	delete_test.go:339: [vsanDatastore] VIC/4206bb20-7bf0-c8fb-3595-78eea1a435c2
```

**Comment by hmahmood** [comment]
Minimizing vsphere calls trumps sorting and iterating in memory... LGTM

**Comment by emlin** [comment]
That's right. That's a trade off based on our files number. 
Ideally vsphere can support datastore files deletion, with empty folder or not parameter, so we don't need this workaround for vSAN issue.

**Comment by andrewtchin** [comment]
lgtm

**Comment by caglar10ur** [comment]
@emlin can you add a summary of the problem as a comment to that new function so that readers of that file understands why we sort first instead deleting them

**Comment by emlin** [comment]
sure

**Comment by emlin** [comment]
♻️

**Comment by emlin** [comment]
https://ci.vmware.run/vmware/vic/3328

**Pull request merged**
