### PR TITLE
Portlayer becomes zombie after receiving a signal

### LINKED ISSUE #1244: Portlayer becomes zombie after signal
Sending a signal to the port-layer turns it into a zombie - it shuts down as a server, but the process doesn't exit so it's never relaunched.

```
time="2016-06-26T06:58:39Z" level=debug msg="Shutting down udpserver" 
time="2016-06-26T06:58:39Z" level=debug msg="Shutting down tcpserver" 
time="2016-06-26T06:58:39Z" level=debug msg="UDP server exited" 
time="2016-06-26T06:58:39Z" level=debug msg="TCP server exited" 
```

### PR DESCRIPTION
**Pull request by caglar10ur**
graceful and our signal handler races and we end up with unexpected
results.

This modifies swagger's server template to

- Disable graceful's signal handling,
- Add 3 second timeout for graceful shutdowns,
- Introduce Stop function which calls underlying Stop call with 3 sec.
timeout value

cmd/port-layer-server now calls that Stop when it receives a signal

ServerShutdown nows logs some output while shutting down the server

Fixes #1244

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

That template tho, yowza.. looks challenging to maintain.  Maybe I just need to learn more about go-swagger.  Do you have a link to the upstream template, just curious to see a diff.

**Comment by mdubya66** [comment]
Lgtm

**Comment by caglar10ur** [comment]
```find . -name server.gotmpl | xargs diff -u``` should show you the diff between this version and vendor'ed version. In a nutshell changes are

- adds a new const called timeout (3 sec.)
- adds domainSocket, httpServer and httpsServer into the Server struct so that we can get them later in the Stop (they were local to NewServer call before)
- converts ```&graceful.Server{Server: new(http.Server)}```
 calls to ```&graceful.Server{Server: new(http.Server), NoSignalHandling: true, Timeout: timeout}```
- adds a Stop method on Server struct which calls Stop on underlying graceful.Server

**Comment by caglar10ur** [comment]
```
diff -u vendor/github.com/go-swagger/go-swagger/generator/templates/server/server.gotmpl lib/apiservers/templates/server/server.gotmpl--- vendor/github.com/go-swagger/go-swagger/generator/templates/server/server.gotmpl	2016-07-21 11:22:34.000000000 -0700
+++ lib/apiservers/templates/server/server.gotmpl	2016-07-21 16:11:32.000000000 -0700
@@ -19,6 +19,10 @@

 //go:generate swagger generate server -t ../.. -A {{ pascalize .Name }} -f ./swagger.yml

+const (
+    timeout = 3 * time.Second
+)
+
 // NewServer creates a new api {{ humanize .Name }} server but does not configure it
 func NewServer(api *{{ .Package }}.{{ pascalize .Name }}API) *Server {
 	s := new(Server)
@@ -43,16 +47,19 @@
 // Server for the {{ humanize .Name }} API
 type Server struct { {{ if (contains .ExtraSchemes "unix") }}
   SocketPath flags.Filename `long:"socket-path" description:"the unix socket to listen on" default:"/var/run/{{ dasherize .Name }}.sock"`
+	domainSocket *graceful.Server
 	domainSocketL net.Listener
 	{{ end }}{{ if (hasInsecure .Schemes) }}
 	Host string `long:"host" description:"the IP to listen on" default:"localhost" env:"HOST"`
 	Port int    `long:"port" description:"the port to listen on for insecure connections, defaults to a random value" env:"PORT"`
+	httpServer *graceful.Server
 	httpServerL   net.Listener{{ end }}{{ if (hasSecure .Schemes) }}

 	TLSHost           string         `long:"tls-host" description:"the IP to listen on for tls, when not specified it's the same as --host" env:"TLS_HOST"`
 	TLSPort           int            `long:"tls-port" description:"the port to listen on for secure connections, defaults to a random value" env:"TLS_PORT"`
 	TLSCertificate    flags.Filename `long:"tls-certificate" description:"the certificate to use for secure connections" required:"true" env:"TLS_CERTIFICATE"`
 	TLSCertificateKey flags.Filename `long:"tls-key" description:"the private key to use for secure conections" required:"true" env:"TLS_PRIVATE_KEY"`
+	httpsServer *graceful.Server
 	httpsServerL  net.Listener{{ end }}

 	{{ if .ExcludeSpec }}Spec flags.Filename `long:"spec" description:"the swagger specification to serve"`{{ end }}
@@ -81,42 +88,48 @@
     }
   }
 	{{ if (contains .ExtraSchemes "unix") }}
-  domainSocket := &graceful.Server{Server: new(http.Server)}
-  domainSocket.Handler = s.handler
+  s.domainSocket = &graceful.Server{Server: new(http.Server),
+                    NoSignalHandling: true,
+                    Timeout: timeout}
+  s.domainSocket.Handler = s.handler

   fmt.Printf("serving {{ humanize .Name }} at unix://%s\n", s.SocketPath)
   {{ if or (hasInsecure .Schemes) (hasSecure .Schemes) }}go func(l net.Listener){
-  {{ end }}if err := domainSocket.Serve(l); err != nil {
+  {{ end }}if err := s.domainSocket.Serve(l); err != nil {
       {{ if or (hasInsecure .Schemes) (hasSecure .Schemes) }}log.Fatalln(err){{ else }}return err{{ end }}
     }
   {{ if or (hasInsecure .Schemes) (hasSecure .Schemes) }}}(s.domainSocketL){{ end }}
   {{ end }}{{ if (hasInsecure .Schemes) }}
-	httpServer := &graceful.Server{Server: new(http.Server)}
-	httpServer.Handler = s.handler
+    s.httpServer = &graceful.Server{Server: new(http.Server),
+                    NoSignalHandling: true,
+                    Timeout: timeout}
+	s.httpServer.Handler = s.handler

 	fmt.Printf("serving {{ humanize .Name }} at http://%s\n", s.httpServerL.Addr())
   {{ if (hasSecure .Schemes) }}go func(l net.Listener) {
   {{ else }}l := s.httpServerL
-		{{ end }}if err := httpServer.Serve(tcpKeepAliveListener{l.(*net.TCPListener)}); err != nil {
+		{{ end }}if err := s.httpServer.Serve(tcpKeepAliveListener{l.(*net.TCPListener)}); err != nil {
 			{{ if (hasSecure .Schemes) }}log.Fatalln(err){{ else }}return err{{ end }}
 		}
   {{ if (hasSecure .Schemes) }}}(s.httpServerL){{ end }}
 {{ end }}{{ if (hasSecure .Schemes) }}
-	httpsServer := &graceful.Server{Server: new(http.Server)}
-	httpsServer.Handler = s.handler
-	httpsServer.TLSConfig = new(tls.Config)
-	httpsServer.TLSConfig.NextProtos = []string{"http/1.1"}
+    s.httpsServer = &graceful.Server{Server: new(http.Server),
+                    NoSignalHandling: true,
+                    Timeout: timeout}
+	s.httpsServer.Handler = s.handler
+	s.httpsServer.TLSConfig = new(tls.Config)
+	s.httpsServer.TLSConfig.NextProtos = []string{"http/1.1"}
 	// https://www.owasp.org/index.php/Transport_Layer_Protection_Cheat_Sheet#Rule_-_Only_Support_Strong_Protocols
-	httpsServer.TLSConfig.MinVersion = tls.VersionTLS11
-	httpsServer.TLSConfig.Certificates = make([]tls.Certificate, 1)
-	httpsServer.TLSConfig.Certificates[0], err = tls.LoadX509KeyPair(string(s.TLSCertificate), string(s.TLSCertificateKey))
+	s.httpsServer.TLSConfig.MinVersion = tls.VersionTLS11
+	s.httpsServer.TLSConfig.Certificates = make([]tls.Certificate, 1)
+	s.httpsServer.TLSConfig.Certificates[0], err = tls.LoadX509KeyPair(string(s.TLSCertificate), string(s.TLSCertificateKey))
 	if err != nil {
 		return err
 	}

 	fmt.Printf("serving {{ humanize .Name }} at https://%s\n", s.httpsServerL.Addr())
-  wrapped := tls.NewListener(tcpKeepAliveListener{s.httpsServerL.(*net.TCPListener)}, httpsServer.TLSConfig)
-  if err := httpsServer.Serve(wrapped); err != nil {
+  wrapped := tls.NewListener(tcpKeepAliveListener{s.httpsServerL.(*net.TCPListener)}, s.httpsServer.TLSConfig)
+  if err := s.httpsServer.Serve(wrapped); err != nil {
     return err
   }
   {{ end }}
@@ -171,6 +184,26 @@
 	return nil
 }

+// Stop instructs the server to halt operations
+func (s *Server) Stop() {
+	{{ if (contains .ExtraSchemes "unix") }}
+    if s.domainSocket != nil {
+        s.domainSocket.Stop(timeout)
+    }
+    {{ end }}
+
+    {{ if (hasInsecure .Schemes) }}
+    if s.httpServer != nil {
+        s.httpServer.Stop(timeout)
+    }
+    {{ end }}
+
+	{{ if (hasSecure .Schemes) }}
+    if s.httpsServer != nil {
+        s.httpsServer.Stop(timeout)
+    }
+    {{ end }}
+}
 // tcpKeepAliveListener is copied from the stdlib net/http package

 // tcpKeepAliveListener sets TCP keep-alive timeouts on accepted
```

**Comment by caglar10ur** [comment]
I realized I can just paste it here :)

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
♻️

**Pull request merged**
