### PR TITLE
Use vendored sources for test dependencies

### LINKED ISSUE #687: Fix integration test dependency provisioning
tests/run_test.sh current does the following:

* Installs bats, bats-assert, bats-support via git clone into the vic git tree

* Removes bats, bats-assert, bats-support directories after the tests are run

* Installs docker via curl https://get.docker.com/ | sh

* Installs jq and git via apt-get

* Installs govc via go get (and does not update)

Changing to do the following:

* Install bats, bats-assert, bats-support similar to how we do for go tooling and don't remove after the tests run

* Don't install docker (devbox provision.sh script already does this)

* Don't install jq or git (devbox provision.sh script already does this)

* Install govc via go install (using the vendored govc)

### PR DESCRIPTION
**Pull request by dougm**
Fixes #687

### CODE REVIEW

**Comment by fdawg4l** [comment]
🐑 🇮🇹

**Comment by fdawg4l** [comment]
@dougm if you lgtm this yourself too, you'll have the 2 required approvals to check this in.

**Comment by mdubya66** [comment]
lgtm

**Comment by dougm** [comment]
rebase cleared my lgtm

**Comment by fdawg4l** [comment]
lgtm

**Pull request merged**
