### PR TITLE
Change container VM directory to pretty name in VMFS

### LINKED ISSUE #2023: change container VM directory in VMFS
Container VM name is changed from ID-><name>-ID to make slightly easy to read. But the VM folder in datastore is not changed, if the datastore is not vSAN.
This issue is to track the change for VMFS file system.

### PR DESCRIPTION
**Pull request by emlin**
Fixes #2023 

This change will make the vm name and vm directory consistent. Also updated integration test for it.

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

**Comment by hmahmood** [comment]
lgtm

**Comment by emlin** [comment]
♻️

**Comment by emlin** [comment]
♻️

**Pull request merged**
