### PR TITLE
Attempt cleanup in the case of an individual test case failure

### LINKED ISSUE #1788: vic-machine create test doesn't clean up failed VCHs
I'm seeing the following from https://ci.vmware.run/vmware/vic/3578
```
Installer completed successfully: VCH-3578-8242...
| PASS |
------------------------------------------------------------------------------
Create VCH - target URL                                               
Running vic-machine create - target URL

Installing VCH to test server...
Installer completed successfully: VCH-3578-1398...
| FAIL |
1 != 0
------------------------------------------------------------------------------
Create VCH - full params                                              
Running vic-machine create

Installing VCH to test server...
Installer completed successfully: VCH-3578-2972...
| PASS |
```

However when I check vic-machine.log I see that VCH-3578-1398 installed successfully without error - the error turns out to have been during pull (the regression tests).

Suite teardown ran, but it didn't remove this failed VCH.

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Fixes #1788

### CODE REVIEW

**Comment by hickeng** [comment]
If we do this right now it's going to be even harder to find examples of the "Is docker running" problem.

**Comment by mhagen-vmware** [comment]
Hey @hickeng are we good to merge this now?

**Comment by mhagen-vmware** [comment]
@hickeng ping

**Comment by mhagen-vmware** [comment]
@hickeng ping

**Comment by hickeng** [comment]
@mhagen-vmware think we're good to merge this - as best I can tell we've addressed the appliance stability problem. We *should* have a log collection approach for the appliance initialization scenario however, otherwise we're going to have real issues diagnosing these problems if it occurs again.

**Comment by matthewavery** [comment]
lgtm

**Comment by kjplatz** [comment]
:+1:

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
