### PR TITLE
Check file not found error

### LINKED ISSUE #2662: vic-machine delete failed if image store path is configured and not created before delete
Create vch with image store path set e.g. --image-store datastore/custom/images.
After creation is finished or not, delete image store path datastore/custom/images, and then run vic-machine delete. 
```
INFO[2016-10-11T14:20:56-05:00] ### Removing VCH ####                        
INFO[2016-10-11T14:20:58-05:00]                                              
INFO[2016-10-11T14:20:58-05:00] VCH ID: VirtualMachine:vm-2828               
INFO[2016-10-11T14:20:59-05:00] Removing VMs                                 
INFO[2016-10-11T14:21:00-05:00] Removing volume stores...                    
INFO[2016-10-11T14:21:00-05:00] Removing appliance VM network devices        
INFO[2016-10-11T14:21:00-05:00] No network device attached                   
INFO[2016-10-11T14:21:00-05:00] Collecting 57d35220-06d2-4004-8aba-0e7f8b52eef7 vpxd.log 
ERRO[2016-10-11T14:21:00-05:00] File [Datastore] line/images was not found   
ERRO[2016-10-11T14:21:00-05:00] --------------------                         
ERRO[2016-10-11T14:21:00-05:00] vic-machine-linux failed: delete failed
```

### PR DESCRIPTION
**Pull request by emlin**
Fixes #2662

### CODE REVIEW

**Comment by hmahmood** [comment]
lgtm

**Comment by dougm** [comment]
lgtm

**Comment by hickeng** [comment]
LGTM

**Comment by emlin** [comment]
make sure full ci pass

**Comment by emlin** [comment]
♻️

**Comment by emlin** [comment]
got those cases passed locally

**Comment by emlin** [comment]
got those cases passed locally

**Pull request merged**
