### PR TITLE
Not sending credentials with every request for REST client

### PR DESCRIPTION
**Pull request by hmahmood**

### CODE REVIEW

**Comment by mdubya66** [comment]
what should happen to this @hmahmood

**Comment by hmahmood** [comment]
Need to investigate @dougm suggestion. Otherwise, this could merged as is (pending another review of course).

**Comment by mdubya66** [comment]
@hickeng how would you prefer we proceed?

**Comment by hickeng** [comment]
I'd prefer to chase down @dougm suggestion - particularly given the current PR looks like something went wrong in a rebase or merge update.

**Comment by hmahmood** [comment]
PR is fixed. I would like to merge this in the interim, and open an issue to investigate @dougm 's suggestion.

**Comment by hmahmood** [comment]
Issue to track investigating @dougm 's suggestion: https://github.com/vmware/vic/issues/7332

**Pull request merged**
