### PR TITLE
Write and implement longevity test [skip ci]

### LINKED ISSUE #1848: Write and execute longevity test plan
As a customer of VIC, I want to be assured that VIC has been put through a longevity test so that I can be assured that it works for long periods of time without failure.

### PR DESCRIPTION
**Pull request by mhagen-vmware**
Written to run for about 2-3 days.

Fixes #1848

### CODE REVIEW

**Comment by matthewavery** [comment]
Looks like this uninstalls the VCH at the end of each iteration. Does this mean we are installing and uninstalling the vch repeatedly during this test?

**Comment by mhagen-vmware** [comment]
Yep

**Comment by matthewavery** [comment]
LGTM - disregard my skepticism, Was wearing my stress test thinking hat for some reason

**Comment by mhagen-vmware** [comment]
.

**Comment by anchal-agrawal** [comment]
LGTM 🐑  🇮🇹

**Comment by mhagen-vmware** [comment]
.

**Comment by mhagen-vmware** [comment]
.

**Pull request merged**
